# Generated by Django 5.2.1 on 2025-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identification_number',
            field=models.CharField(default=1234567891, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
