# Generated by Django 5.2.1 on 2025-07-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('BRANCH_MANAGER', 'branch_manager'), ('TECHNICIAN', 'technician'), ('SALESPERSON', 'salesperson'), ('ACCOUNTANT', 'accountant'), ('INVENTORY_MANAGER', 'inventory_manager'), ('RECEPTIONIST', 'receptionist'), ('CRM', 'crm'), ('CUSTOMER', 'customer')], default='RECEPTIONIST', max_length=50),
        ),
    ]
