# Generated by Django 5.2.1 on 2025-08-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactus_page_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('description', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('twitter', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_en',
        ),
    ]
