# Generated by Django 5.2.1 on 2025-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_branch_is_deleted_branchusers_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
