# Generated by Django 5.2.1 on 2025-08-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tenantsettings_remove_page_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
