# Generated by Django 5.2.1 on 2025-08-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tenantsettings_created_at_tenantsettings_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='account_number',
            field=models.CharField(blank=True, default='123456789', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='address',
            field=models.CharField(blank=True, default='123 Default St, Default City, Default Country', max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='bank_name',
            field=models.CharField(blank=True, default='Default Bank', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='city',
            field=models.CharField(blank=True, default='Default City', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='country',
            field=models.CharField(blank=True, default='Default Country', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='date_format',
            field=models.CharField(blank=True, default='YYYY-MM-DD', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='iban',
            field=models.CharField(blank=True, default='DE89370400440532013000', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='postal_code',
            field=models.CharField(blank=True, default='12345', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='seo_description',
            field=models.TextField(blank=True, default='Default SEO Description'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='seo_keywords',
            field=models.CharField(blank=True, default='keyword1, keyword2', max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='seo_title',
            field=models.CharField(blank=True, default='Default SEO Title', max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='state',
            field=models.CharField(blank=True, default='Default State', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='swift_code',
            field=models.CharField(blank=True, default='DEUTDEDBFRA', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='time_format',
            field=models.CharField(blank=True, default='24', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='business_name',
            field=models.CharField(default='Optics Tenant', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='description',
            field=models.TextField(blank=True, default='This is a default description for the tenant settings.'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='email',
            field=models.EmailField(blank=True, default='email@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.facebook.com'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='phone',
            field=models.CharField(blank=True, default='123-456-7890', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#0000FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='secondary_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='tiktok',
            field=models.URLField(blank=True, default='https://www.tiktok.com'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='twitter',
            field=models.URLField(blank=True, default='https://www.twitter.com'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='website',
            field=models.URLField(blank=True, default='https://www.example.com'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='whatsapp', max_length=20),
        ),
    ]
