# Generated by Django 5.2.1 on 2025-08-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tenantsettings_account_number_tenantsettings_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
    ]
