# Generated by Django 5.2.1 on 2025-08-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_page_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='sectian_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
