# Generated by Django 5.2.1 on 2025-08-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_page_content_page_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='page',
            name='status',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together={('slug', 'language')},
        ),
        migrations.AddField(
            model_name='page',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_description',
            field=models.TextField(blank=True, default='hus', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_keywords',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagecontent', to='users.page'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='seo_title',
            field=models.CharField(blank=True, default='hus', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='page',
            table='pages',
        ),
        migrations.AlterModelTable(
            name='pagecontent',
            table='page_translations',
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='sectian_id',
        ),
    ]
