# Generated by Django 5.2.1 on 2025-08-21 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_page_options_remove_page_content_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together={('slug', 'language')},
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.page'),
        ),
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together={('page', 'language'), ('slug', 'language')},
        ),
    ]
