# Generated by Django 5.2.1 on 2025-08-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_pagecontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together={('page', 'language')},
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='new', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='slug',
        ),
    ]
