# Generated by Django 5.2.1 on 2025-08-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_pagecontent_unique_together_page_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsettings',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='time_format',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='timezone',
        ),
    ]
