# Generated by Django 5.2.9 on 2025-12-20 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('CL', 'Contact Lenses'), ('SL', 'Spectacle Lenses'), ('FR', 'Frames'), ('AX', 'Accessories'), ('OT', 'Other'), ('DV', 'Devices'), ('All', 'All')], default='All', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('usku', models.CharField(editable=False, max_length=64, unique=True)),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
            },
        ),
        migrations.CreateModel(
            name='ContactLensVariantExpirationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Contact Lens Variant Expiration Date',
                'verbose_name_plural': 'Contact Lens Variant Expiration Dates',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('CL', 'Contact Lenses'), ('SL', 'Spectacle Lenses'), ('FR', 'Frames'), ('AX', 'Accessories'), ('OT', 'Other'), ('DV', 'Devices')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, editable=False)),
                ('usku', models.CharField(editable=False, help_text='Unique product SKU generated automatically', max_length=64, unique=True)),
                ('variant_type', models.CharField(choices=[('basic', 'Basic'), ('frames', 'Frames'), ('stockLenses', 'Stock Lenses'), ('rxLenses', 'Rx Lenses'), ('contactLenses', 'Contact Lenses'), ('custom', 'Custom')], default='basic', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('answer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_image', models.ImageField(blank=True, null=True, upload_to='products/marketing/')),
                ('seo_image_alt', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('unisex', 'Unisex'), ('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='unisex', max_length=10)),
                ('age_group', models.CharField(blank=True, choices=[('adult', 'Adult'), ('child', 'Child'), ('senior', 'Senior')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('offer', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('question', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('max_stock_level', models.PositiveIntegerField(default=100)),
                ('min_stock_level', models.PositiveIntegerField(default=0)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('last_sale', models.DateTimeField(blank=True, null=True)),
                ('allow_backorder', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase/Restock'), ('sale', 'Sale'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Stock Adjustment'), ('damage', 'Damage/Loss'), ('return', 'Customer Return'), ('reserve', 'Reserve Stock'), ('release', 'Release Reserved')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('transfer_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('shipped', 'Shipped'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_by', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_sent', models.PositiveIntegerField(default=0)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(max_length=50, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContactLensVariant',
            fields=[
                ('productvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productvariant')),
                ('spherical', models.CharField(blank=True, choices=[('-30.00', '-30.00'), ('-29.75', '-29.75'), ('-29.50', '-29.50'), ('-29.25', '-29.25'), ('-29.00', '-29.00'), ('-28.75', '-28.75'), ('-28.50', '-28.50'), ('-28.25', '-28.25'), ('-28.00', '-28.00'), ('-27.75', '-27.75'), ('-27.50', '-27.50'), ('-27.25', '-27.25'), ('-27.00', '-27.00'), ('-26.75', '-26.75'), ('-26.50', '-26.50'), ('-26.25', '-26.25'), ('-26.00', '-26.00'), ('-25.75', '-25.75'), ('-25.50', '-25.50'), ('-25.25', '-25.25'), ('-25.00', '-25.00'), ('-24.75', '-24.75'), ('-24.50', '-24.50'), ('-24.25', '-24.25'), ('-24.00', '-24.00'), ('-23.75', '-23.75'), ('-23.50', '-23.50'), ('-23.25', '-23.25'), ('-23.00', '-23.00'), ('-22.75', '-22.75'), ('-22.50', '-22.50'), ('-22.25', '-22.25'), ('-22.00', '-22.00'), ('-21.75', '-21.75'), ('-21.50', '-21.50'), ('-21.25', '-21.25'), ('-21.00', '-21.00'), ('-20.75', '-20.75'), ('-20.50', '-20.50'), ('-20.25', '-20.25'), ('-20.00', '-20.00'), ('-19.75', '-19.75'), ('-19.50', '-19.50'), ('-19.25', '-19.25'), ('-19.00', '-19.00'), ('-18.75', '-18.75'), ('-18.50', '-18.50'), ('-18.25', '-18.25'), ('-18.00', '-18.00'), ('-17.75', '-17.75'), ('-17.50', '-17.50'), ('-17.25', '-17.25'), ('-17.00', '-17.00'), ('-16.75', '-16.75'), ('-16.50', '-16.50'), ('-16.25', '-16.25'), ('-16.00', '-16.00'), ('-15.75', '-15.75'), ('-15.50', '-15.50'), ('-15.25', '-15.25'), ('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00'), ('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00'), ('+06.25', '+06.25'), ('+06.50', '+06.50'), ('+06.75', '+06.75'), ('+07.00', '+07.00'), ('+07.25', '+07.25'), ('+07.50', '+07.50'), ('+07.75', '+07.75'), ('+08.00', '+08.00'), ('+08.25', '+08.25'), ('+08.50', '+08.50'), ('+08.75', '+08.75'), ('+09.00', '+09.00'), ('+09.25', '+09.25'), ('+09.50', '+09.50'), ('+09.75', '+09.75'), ('+10.00', '+10.00'), ('+10.25', '+10.25'), ('+10.50', '+10.50'), ('+10.75', '+10.75'), ('+11.00', '+11.00'), ('+11.25', '+11.25'), ('+11.50', '+11.50'), ('+11.75', '+11.75'), ('+12.00', '+12.00'), ('+12.25', '+12.25'), ('+12.50', '+12.50'), ('+12.75', '+12.75'), ('+13.00', '+13.00'), ('+13.25', '+13.25'), ('+13.50', '+13.50'), ('+13.75', '+13.75'), ('+14.00', '+14.00'), ('+14.25', '+14.25'), ('+14.50', '+14.50'), ('+14.75', '+14.75'), ('+15.00', '+15.00'), ('+15.25', '+15.25'), ('+15.50', '+15.50'), ('+15.75', '+15.75'), ('+16.00', '+16.00'), ('+16.25', '+16.25'), ('+16.50', '+16.50'), ('+16.75', '+16.75'), ('+17.00', '+17.00'), ('+17.25', '+17.25'), ('+17.50', '+17.50'), ('+17.75', '+17.75'), ('+18.00', '+18.00'), ('+18.25', '+18.25'), ('+18.50', '+18.50'), ('+18.75', '+18.75'), ('+19.00', '+19.00'), ('+19.25', '+19.25'), ('+19.50', '+19.50'), ('+19.75', '+19.75'), ('+20.00', '+20.00'), ('+20.25', '+20.25'), ('+20.50', '+20.50'), ('+20.75', '+20.75'), ('+21.00', '+21.00'), ('+21.25', '+21.25'), ('+21.50', '+21.50'), ('+21.75', '+21.75'), ('+22.00', '+22.00'), ('+22.25', '+22.25'), ('+22.50', '+22.50'), ('+22.75', '+22.75'), ('+23.00', '+23.00'), ('+23.25', '+23.25'), ('+23.50', '+23.50'), ('+23.75', '+23.75'), ('+24.00', '+24.00'), ('+24.25', '+24.25'), ('+24.50', '+24.50'), ('+24.75', '+24.75'), ('+25.00', '+25.00'), ('+25.25', '+25.25'), ('+25.50', '+25.50'), ('+25.75', '+25.75'), ('+26.00', '+26.00'), ('+26.25', '+26.25'), ('+26.50', '+26.50'), ('+26.75', '+26.75'), ('+27.00', '+27.00'), ('+27.25', '+27.25'), ('+27.50', '+27.50'), ('+27.75', '+27.75'), ('+28.00', '+28.00'), ('+28.25', '+28.25'), ('+28.50', '+28.50'), ('+28.75', '+28.75'), ('+29.00', '+29.00'), ('+29.25', '+29.25'), ('+29.50', '+29.50'), ('+29.75', '+29.75'), ('+30.00', '+30.00')], default=None, max_length=20)),
                ('cylinder', models.CharField(blank=True, choices=[('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00')], default=None, max_length=20)),
                ('axis', models.CharField(blank=True, default=None, max_length=20)),
                ('addition', models.CharField(blank=True, choices=[('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00')], default=None, max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productvariant', models.Model),
        ),
        migrations.CreateModel(
            name='FrameVariant',
            fields=[
                ('productvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productvariant',),
        ),
        migrations.CreateModel(
            name='RxLensVariant',
            fields=[
                ('productvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productvariant')),
                ('addition', models.CharField(blank=True, choices=[('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00')], default=None, max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productvariant', models.Model),
        ),
        migrations.CreateModel(
            name='StokLensVariant',
            fields=[
                ('productvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productvariant')),
                ('spherical', models.CharField(choices=[('-30.00', '-30.00'), ('-29.75', '-29.75'), ('-29.50', '-29.50'), ('-29.25', '-29.25'), ('-29.00', '-29.00'), ('-28.75', '-28.75'), ('-28.50', '-28.50'), ('-28.25', '-28.25'), ('-28.00', '-28.00'), ('-27.75', '-27.75'), ('-27.50', '-27.50'), ('-27.25', '-27.25'), ('-27.00', '-27.00'), ('-26.75', '-26.75'), ('-26.50', '-26.50'), ('-26.25', '-26.25'), ('-26.00', '-26.00'), ('-25.75', '-25.75'), ('-25.50', '-25.50'), ('-25.25', '-25.25'), ('-25.00', '-25.00'), ('-24.75', '-24.75'), ('-24.50', '-24.50'), ('-24.25', '-24.25'), ('-24.00', '-24.00'), ('-23.75', '-23.75'), ('-23.50', '-23.50'), ('-23.25', '-23.25'), ('-23.00', '-23.00'), ('-22.75', '-22.75'), ('-22.50', '-22.50'), ('-22.25', '-22.25'), ('-22.00', '-22.00'), ('-21.75', '-21.75'), ('-21.50', '-21.50'), ('-21.25', '-21.25'), ('-21.00', '-21.00'), ('-20.75', '-20.75'), ('-20.50', '-20.50'), ('-20.25', '-20.25'), ('-20.00', '-20.00'), ('-19.75', '-19.75'), ('-19.50', '-19.50'), ('-19.25', '-19.25'), ('-19.00', '-19.00'), ('-18.75', '-18.75'), ('-18.50', '-18.50'), ('-18.25', '-18.25'), ('-18.00', '-18.00'), ('-17.75', '-17.75'), ('-17.50', '-17.50'), ('-17.25', '-17.25'), ('-17.00', '-17.00'), ('-16.75', '-16.75'), ('-16.50', '-16.50'), ('-16.25', '-16.25'), ('-16.00', '-16.00'), ('-15.75', '-15.75'), ('-15.50', '-15.50'), ('-15.25', '-15.25'), ('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00'), ('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00'), ('+06.25', '+06.25'), ('+06.50', '+06.50'), ('+06.75', '+06.75'), ('+07.00', '+07.00'), ('+07.25', '+07.25'), ('+07.50', '+07.50'), ('+07.75', '+07.75'), ('+08.00', '+08.00'), ('+08.25', '+08.25'), ('+08.50', '+08.50'), ('+08.75', '+08.75'), ('+09.00', '+09.00'), ('+09.25', '+09.25'), ('+09.50', '+09.50'), ('+09.75', '+09.75'), ('+10.00', '+10.00'), ('+10.25', '+10.25'), ('+10.50', '+10.50'), ('+10.75', '+10.75'), ('+11.00', '+11.00'), ('+11.25', '+11.25'), ('+11.50', '+11.50'), ('+11.75', '+11.75'), ('+12.00', '+12.00'), ('+12.25', '+12.25'), ('+12.50', '+12.50'), ('+12.75', '+12.75'), ('+13.00', '+13.00'), ('+13.25', '+13.25'), ('+13.50', '+13.50'), ('+13.75', '+13.75'), ('+14.00', '+14.00'), ('+14.25', '+14.25'), ('+14.50', '+14.50'), ('+14.75', '+14.75'), ('+15.00', '+15.00'), ('+15.25', '+15.25'), ('+15.50', '+15.50'), ('+15.75', '+15.75'), ('+16.00', '+16.00'), ('+16.25', '+16.25'), ('+16.50', '+16.50'), ('+16.75', '+16.75'), ('+17.00', '+17.00'), ('+17.25', '+17.25'), ('+17.50', '+17.50'), ('+17.75', '+17.75'), ('+18.00', '+18.00'), ('+18.25', '+18.25'), ('+18.50', '+18.50'), ('+18.75', '+18.75'), ('+19.00', '+19.00'), ('+19.25', '+19.25'), ('+19.50', '+19.50'), ('+19.75', '+19.75'), ('+20.00', '+20.00'), ('+20.25', '+20.25'), ('+20.50', '+20.50'), ('+20.75', '+20.75'), ('+21.00', '+21.00'), ('+21.25', '+21.25'), ('+21.50', '+21.50'), ('+21.75', '+21.75'), ('+22.00', '+22.00'), ('+22.25', '+22.25'), ('+22.50', '+22.50'), ('+22.75', '+22.75'), ('+23.00', '+23.00'), ('+23.25', '+23.25'), ('+23.50', '+23.50'), ('+23.75', '+23.75'), ('+24.00', '+24.00'), ('+24.25', '+24.25'), ('+24.50', '+24.50'), ('+24.75', '+24.75'), ('+25.00', '+25.00'), ('+25.25', '+25.25'), ('+25.50', '+25.50'), ('+25.75', '+25.75'), ('+26.00', '+26.00'), ('+26.25', '+26.25'), ('+26.50', '+26.50'), ('+26.75', '+26.75'), ('+27.00', '+27.00'), ('+27.25', '+27.25'), ('+27.50', '+27.50'), ('+27.75', '+27.75'), ('+28.00', '+28.00'), ('+28.25', '+28.25'), ('+28.50', '+28.50'), ('+28.75', '+28.75'), ('+29.00', '+29.00'), ('+29.25', '+29.25'), ('+29.50', '+29.50'), ('+29.75', '+29.75'), ('+30.00', '+30.00')], max_length=20)),
                ('cylinder', models.CharField(blank=True, choices=[('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00')], default=None, max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productvariant', models.Model),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimensions',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Dimensions'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_type',
            field=models.ForeignKey(limit_choices_to={'attribute__name': 'Product Type'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_product_type', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='warranty',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Warranty'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_warranty', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Weight'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_weight', to='products.attributevalue'),
        ),
        migrations.CreateModel(
            name='ExtraVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_set', to='products.attribute')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributevalue_set', to='products.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariant_set', to='products.productvariant')),
                ('variant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extravariantattribute_set', to='products.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='FlexiblePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customergroup')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='products.productvariant')),
            ],
            options={
                'ordering': ['-priority', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='products.category'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supply_code', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
