# Generated by Django 5.2.9 on 2026-06-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Related Invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Related Purchase Order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='products.purchaseorder'),
        ),
    ]
