# Generated by Django 5.2.9 on 2026-01-24 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_options_alter_branchusers_options_and_more'),
        ('crm', '0004_alter_campaign_options_alter_claimdocument_options_and_more'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='productvariantanswer',
            options={'verbose_name': 'Product Variant Answer', 'verbose_name_plural': 'Product Variant Answers'},
        ),
        migrations.AlterModelOptions(
            name='productvariantmarketing',
            options={'verbose_name': 'Product Variant Marketing', 'verbose_name_plural': 'Product Variant Marketing'},
        ),
        migrations.AlterModelOptions(
            name='productvariantoffer',
            options={'verbose_name': 'Product Variant Offer', 'verbose_name_plural': 'Product Variant Offers'},
        ),
        migrations.AlterModelOptions(
            name='productvariantquestion',
            options={'verbose_name': 'Product Variant Question', 'verbose_name_plural': 'Product Variant Questions'},
        ),
        migrations.AlterModelOptions(
            name='productvariantreview',
            options={'verbose_name': 'Product Variant Review', 'verbose_name_plural': 'Product Variant Reviews'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute', verbose_name='Attribute'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='unique_key',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='Unique Key'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='product_type',
            field=models.CharField(choices=[('CL', 'Contact Lenses'), ('SL', 'Spectacle Lenses'), ('FR', 'Frames'), ('AX', 'Accessories'), ('OT', 'Other'), ('DV', 'Devices'), ('All', 'All')], default='All', max_length=50, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch', verbose_name='Specific Branch'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer', verbose_name='Specific Customer'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customergroup', verbose_name='Customer Group'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Quantity'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimum Quantity'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rules', to='crm.partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='pricing_tier',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale_1', 'Wholesale - Level 1'), ('wholesale_2', 'Wholesale - Level 2'), ('wholesale_3', 'Wholesale - Level 3 (VIP)'), ('distributor', 'Distributor')], max_length=20, null=True, verbose_name='Pricing Tier'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='productvariantanswer',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='productvariantanswer',
            name='answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Answered By'),
        ),
        migrations.AlterField(
            model_name='productvariantanswer',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='products.productvariantquestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='age_group',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('child', 'Child'), ('senior', 'Senior')], max_length=20, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Unisex'), ('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='unisex', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/marketing/', verbose_name='SEO Image'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='seo_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO Image Alt Text'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='productvariantmarketing',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='products.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AlterField(
            model_name='productvariantoffer',
            name='ProductVariant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AlterField(
            model_name='productvariantoffer',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='productvariantoffer',
            name='offer',
            field=models.CharField(max_length=100, verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='productvariantoffer',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='productvariantquestion',
            name='ProductVariant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='products.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AlterField(
            model_name='productvariantquestion',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Asked By'),
        ),
        migrations.AlterField(
            model_name='productvariantquestion',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='productvariantreview',
            name='ProductVariant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AlterField(
            model_name='productvariantreview',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='productvariantreview',
            name='review',
            field=models.TextField(verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='productvariantreview',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payment Terms'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
