# Generated by Django 5.2.9 on 2026-01-31 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_attribute_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_variant_by_hash',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_usku_0d67b5_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='main_group',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='usku',
            new_name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='usku',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='factory_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(default=django.utils.timezone.now, editable=False, help_text='Unique product variant SKU generated automatically', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('main_group', 'brand', 'model')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='products_pr_sku_dcab68_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('sku',), name='unique_variant_by_hash'),
        ),
    ]
