# Generated by Django 5.2.6 on 2025-10-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_stockmovements_products_st_stocks__aaa873_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='bridge_width',
            new_name='bridge_width_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='dimensions',
            new_name='dimensions_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='frame_color',
            new_name='frame_color_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='frame_material',
            new_name='frame_material_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='frame_shape',
            new_name='frame_shape_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='lens_base_curve',
            new_name='lens_base_curve_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='lens_coatings',
            new_name='lens_coatings_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='lens_color',
            new_name='lens_color_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='lens_diameter',
            new_name='lens_diameter_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='lens_material',
            new_name='lens_material_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='lens_type',
            new_name='lens_type_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='lens_water_content',
            new_name='lens_water_content_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='replacement_schedule',
            new_name='replacement_schedule_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='temple_length',
            new_name='temple_length_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='unit',
            new_name='unit_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='warranty',
            new_name='warranty_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='weight',
            new_name='weight_id',
        ),
    ]
