# Generated by Django 5.2.9 on 2026-06-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stockmovement_invoice_stockmovement_purchase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rxlensvariant',
            name='addition',
        ),
        migrations.RemoveField(
            model_name='rxlensvariant',
            name='right_or_left',
        ),
    ]
