# Generated by Django 5.2.9 on 2026-01-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_name_alter_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rxlensvariant',
            name='right_or_left',
            field=models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left')], help_text='Specify if lens is for right (R) or left (L) eye', max_length=5, null=True),
        ),
    ]
