# Generated by Django 5.2.9 on 2026-06-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_rxlensvariant_addition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibleprice',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='products.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='flexibleprice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='products.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='flexibleprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='products.product', verbose_name='Specific Model'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='products.productvariant', verbose_name='Specific Variant'),
        ),
    ]
