# Generated by Django 5.2.9 on 2026-07-09 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_flexibleprice_brand_flexibleprice_category_and_more'),
        ('sales', '0005_alter_creditnote_credit_note_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_number'], name='products_st_referen_c7aa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['invoice'], name='products_st_invoice_02e759_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['purchase_order'], name='products_st_purchas_3cd7af_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='products_st_created_792bf6_idx'),
        ),
    ]
