# Generated by Django 5.2.9 on 2026-02-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_purchase_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Optional manufacturer for the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.manufacturer'),
        ),
    ]
