# Generated by Django 5.2.9 on 2026-08-01 16:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_stockmovement_products_st_referen_c7aa1c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.CharField(choices=[('standard', 'Standard (15%)'), ('zero_rated', 'Zero-Rated (0% Medical)'), ('exempt', 'Exempt')], default='standard', max_length=20, verbose_name='Tax Category'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, help_text='Numeric barcode for POS scanners', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='min_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Selling Price'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tax_category',
            field=models.CharField(choices=[('standard', 'Standard (15%)'), ('zero_rated', 'Zero-Rated (0% Medical)'), ('exempt', 'Exempt')], default='standard', max_length=20, verbose_name='Tax Category'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Tax Rate %'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customs_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Customs Cost'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_consignment',
            field=models.BooleanField(default=False, verbose_name='Consignment Purchase Order'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='other_landed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Other Landed Cost'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping Cost'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='landed_cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Landed Cost Per Unit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_consignment',
            field=models.BooleanField(default=False, help_text='Indicates if stock is vendor consignment inventory', verbose_name='Consignment Stock'),
        ),
    ]
