# Generated by Django 5.2.6 on 2025-10-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_coatings_id',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='lens_coatings',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute_id__name': 'Coatings'}, related_name='%(class)s_lens_coatings', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
