# Generated by Django 5.2.9 on 2026-02-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_manufacturer_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Policy Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Pricing Policy',
                'verbose_name_plural': 'Pricing Policies',
            },
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase/Restock'), ('sale', 'Sale'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Stock Adjustment'), ('damage', 'Damage/Loss'), ('return', 'Customer Return'), ('return_to_supplier', 'Return to Supplier'), ('reserve', 'Reserve Stock'), ('release', 'Release Reserved')], max_length=20),
        ),
        migrations.AddField(
            model_name='flexibleprice',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flexible_prices', to='products.pricingpolicy', verbose_name='Pricing Policy'),
        ),
    ]
