# Generated by Django 5.2.9 on 2026-01-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('crm', '0004_add_wholesale_support'),
        ('products', '0007_stock_last_cost_stockmovement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibleprice',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الخصم'),
        ),
        migrations.AddField(
            model_name='flexibleprice',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للكمية'),
        ),
        migrations.AddField(
            model_name='flexibleprice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flexibleprice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rules', to='crm.partner', verbose_name='شريك'),
        ),
        migrations.AddField(
            model_name='flexibleprice',
            name='pricing_tier',
            field=models.CharField(blank=True, choices=[('retail', 'تجزئة'), ('wholesale_1', 'جملة - المستوى 1'), ('wholesale_2', 'جملة - المستوى 2'), ('wholesale_3', 'جملة - المستوى 3 (VIP)'), ('distributor', 'موزع')], max_length=20, null=True, verbose_name='مستوى التسعير'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch', verbose_name='فرع محدد'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer', verbose_name='عميل محدد'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customergroup', verbose_name='مجموعة عملاء'),
        ),
        migrations.AlterField(
            model_name='flexibleprice',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للكمية'),
        ),
        migrations.AddIndex(
            model_name='flexibleprice',
            index=models.Index(fields=['variant', 'pricing_tier'], name='products_fl_variant_721999_idx'),
        ),
        migrations.AddIndex(
            model_name='flexibleprice',
            index=models.Index(fields=['variant', 'customer'], name='products_fl_variant_2a26aa_idx'),
        ),
        migrations.AddIndex(
            model_name='flexibleprice',
            index=models.Index(fields=['variant', 'partner'], name='products_fl_variant_85afa0_idx'),
        ),
    ]
