# Generated by Django 5.2.6 on 2025-10-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productvariant_lens_coatings_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LensCoating',
        ),
    ]
