# Generated by Django 5.2.9 on 2026-01-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_wholesale_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, editable=False, help_text='Auto-generated description based on variant specifications'),
        ),
    ]
