# Generated by Django 5.2.6 on 2025-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_lenscoating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='SKU (Stock Keeping Unit)', max_length=50, null=True, unique=True),
        ),
    ]
