# Generated by Django 5.2.6 on 2025-10-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productvariant_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='lens_coatings',
            new_name='lens_coatings_id',
        ),
    ]
