# Generated by Django 5.2.6 on 2025-10-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_lens_coatings_productvariant_lens_coatings_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute_id', 'value')},
        ),
    ]
