# Generated by Django 5.2.6 on 2025-10-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_attributevalue_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_type_id',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_type_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Product Type'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_product_type', to='products.attributevalue'),
        ),
    ]
