# Generated by Django 5.2.6 on 2025-10-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productvariant_lens_type_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Attribute Value', 'verbose_name_plural': 'Attribute Values'},
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='unique_key',
            field=models.CharField(default='', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('CL', 'Contact Lenses'), ('SL', 'Spectacle Lenses'), ('FR', 'Frames'), ('AX', 'Accessories'), ('OT', 'Other'), ('DV', 'Devices')], max_length=50),
        ),
    ]
