# Generated by Django 5.2.6 on 2025-10-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_attributevalue_options_attributevalue_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='product_type',
            field=models.CharField(choices=[('CL', 'Contact Lenses'), ('SL', 'Spectacle Lenses'), ('FR', 'Frames'), ('AX', 'Accessories'), ('OT', 'Other'), ('DV', 'Devices'), ('All', 'All')], default='All', max_length=50),
        ),
    ]
