# Generated by Django 5.2.6 on 2025-10-14 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_options_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usku',
            field=models.CharField(default=django.utils.timezone.now, editable=False, help_text='Unique product SKU generated automatically', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
