# Generated by Django 5.2.6 on 2025-10-14 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_usku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_water_content_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='spherical',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='replacement_schedule_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='cylinder',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='addition',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='axis',
        ),
        migrations.CreateModel(
            name='ContactLensVariantExpiration_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('variant_type', models.CharField(max_length=50)),
                ('variant_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FrameVariant',
            fields=[
                ('productvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productvariant',),
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='dimensions_id',
            new_name='dimensions',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='product_type_id',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='warranty_id',
            new_name='warranty',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='weight_id',
            new_name='weight',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_cee51f_idx',
            old_name='products_pr_product_101f29_idx',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='bridge_width_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='frame_color_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='frame_material_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='frame_shape_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_base_curve_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_coatings_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_color_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_diameter_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_material_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='temple_length_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='product',
            name='variant_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('frames', 'Frames'), ('stockLenses', 'Stock Lenses'), ('rxLenses', 'Rx Lenses'), ('contactLenses', 'Contact Lenses'), ('custom', 'Custom')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='usku',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='ContactLensVariant',
            fields=[
                ('productvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productvariant')),
                ('spherical', models.CharField(blank=True, choices=[('-30.00', '-30.00'), ('-29.75', '-29.75'), ('-29.50', '-29.50'), ('-29.25', '-29.25'), ('-29.00', '-29.00'), ('-28.75', '-28.75'), ('-28.50', '-28.50'), ('-28.25', '-28.25'), ('-28.00', '-28.00'), ('-27.75', '-27.75'), ('-27.50', '-27.50'), ('-27.25', '-27.25'), ('-27.00', '-27.00'), ('-26.75', '-26.75'), ('-26.50', '-26.50'), ('-26.25', '-26.25'), ('-26.00', '-26.00'), ('-25.75', '-25.75'), ('-25.50', '-25.50'), ('-25.25', '-25.25'), ('-25.00', '-25.00'), ('-24.75', '-24.75'), ('-24.50', '-24.50'), ('-24.25', '-24.25'), ('-24.00', '-24.00'), ('-23.75', '-23.75'), ('-23.50', '-23.50'), ('-23.25', '-23.25'), ('-23.00', '-23.00'), ('-22.75', '-22.75'), ('-22.50', '-22.50'), ('-22.25', '-22.25'), ('-22.00', '-22.00'), ('-21.75', '-21.75'), ('-21.50', '-21.50'), ('-21.25', '-21.25'), ('-21.00', '-21.00'), ('-20.75', '-20.75'), ('-20.50', '-20.50'), ('-20.25', '-20.25'), ('-20.00', '-20.00'), ('-19.75', '-19.75'), ('-19.50', '-19.50'), ('-19.25', '-19.25'), ('-19.00', '-19.00'), ('-18.75', '-18.75'), ('-18.50', '-18.50'), ('-18.25', '-18.25'), ('-18.00', '-18.00'), ('-17.75', '-17.75'), ('-17.50', '-17.50'), ('-17.25', '-17.25'), ('-17.00', '-17.00'), ('-16.75', '-16.75'), ('-16.50', '-16.50'), ('-16.25', '-16.25'), ('-16.00', '-16.00'), ('-15.75', '-15.75'), ('-15.50', '-15.50'), ('-15.25', '-15.25'), ('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00'), ('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00'), ('+06.25', '+06.25'), ('+06.50', '+06.50'), ('+06.75', '+06.75'), ('+07.00', '+07.00'), ('+07.25', '+07.25'), ('+07.50', '+07.50'), ('+07.75', '+07.75'), ('+08.00', '+08.00'), ('+08.25', '+08.25'), ('+08.50', '+08.50'), ('+08.75', '+08.75'), ('+09.00', '+09.00'), ('+09.25', '+09.25'), ('+09.50', '+09.50'), ('+09.75', '+09.75'), ('+10.00', '+10.00'), ('+10.25', '+10.25'), ('+10.50', '+10.50'), ('+10.75', '+10.75'), ('+11.00', '+11.00'), ('+11.25', '+11.25'), ('+11.50', '+11.50'), ('+11.75', '+11.75'), ('+12.00', '+12.00'), ('+12.25', '+12.25'), ('+12.50', '+12.50'), ('+12.75', '+12.75'), ('+13.00', '+13.00'), ('+13.25', '+13.25'), ('+13.50', '+13.50'), ('+13.75', '+13.75'), ('+14.00', '+14.00'), ('+14.25', '+14.25'), ('+14.50', '+14.50'), ('+14.75', '+14.75'), ('+15.00', '+15.00'), ('+15.25', '+15.25'), ('+15.50', '+15.50'), ('+15.75', '+15.75'), ('+16.00', '+16.00'), ('+16.25', '+16.25'), ('+16.50', '+16.50'), ('+16.75', '+16.75'), ('+17.00', '+17.00'), ('+17.25', '+17.25'), ('+17.50', '+17.50'), ('+17.75', '+17.75'), ('+18.00', '+18.00'), ('+18.25', '+18.25'), ('+18.50', '+18.50'), ('+18.75', '+18.75'), ('+19.00', '+19.00'), ('+19.25', '+19.25'), ('+19.50', '+19.50'), ('+19.75', '+19.75'), ('+20.00', '+20.00'), ('+20.25', '+20.25'), ('+20.50', '+20.50'), ('+20.75', '+20.75'), ('+21.00', '+21.00'), ('+21.25', '+21.25'), ('+21.50', '+21.50'), ('+21.75', '+21.75'), ('+22.00', '+22.00'), ('+22.25', '+22.25'), ('+22.50', '+22.50'), ('+22.75', '+22.75'), ('+23.00', '+23.00'), ('+23.25', '+23.25'), ('+23.50', '+23.50'), ('+23.75', '+23.75'), ('+24.00', '+24.00'), ('+24.25', '+24.25'), ('+24.50', '+24.50'), ('+24.75', '+24.75'), ('+25.00', '+25.00'), ('+25.25', '+25.25'), ('+25.50', '+25.50'), ('+25.75', '+25.75'), ('+26.00', '+26.00'), ('+26.25', '+26.25'), ('+26.50', '+26.50'), ('+26.75', '+26.75'), ('+27.00', '+27.00'), ('+27.25', '+27.25'), ('+27.50', '+27.50'), ('+27.75', '+27.75'), ('+28.00', '+28.00'), ('+28.25', '+28.25'), ('+28.50', '+28.50'), ('+28.75', '+28.75'), ('+29.00', '+29.00'), ('+29.25', '+29.25'), ('+29.50', '+29.50'), ('+29.75', '+29.75'), ('+30.00', '+30.00')], default=None, max_length=20, null=True)),
                ('cylinder', models.CharField(blank=True, choices=[('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00')], default=None, max_length=20, null=True)),
                ('axis', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('addition', models.CharField(blank=True, choices=[('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00')], default=None, max_length=20, null=True)),
                ('lens_base_curve', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Base Curve'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_base_curve', to='products.attributevalue')),
                ('lens_coatings', models.ManyToManyField(blank=True, limit_choices_to={'attribute_id__name': 'Coatings'}, related_name='%(class)s_lens_coatings', to='products.attributevalue')),
                ('lens_color', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_color', to='products.attributevalue')),
                ('lens_diameter', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Diameter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_diameter', to='products.attributevalue')),
                ('lens_material', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Material'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_material', to='products.attributevalue')),
                ('lens_water_content_id', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Water Content'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_water_content', to='products.attributevalue')),
                ('replacement_schedule_id', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Replacement Schedule'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_replacement_schedule', to='products.attributevalue')),
                ('units', models.ForeignKey(blank=True, default=None, help_text='Unit of measurement box piesces', limit_choices_to={'attribute_id__name': 'Unit'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_unit', to='products.attributevalue')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productvariant', models.Model),
        ),
        migrations.AddField(
            model_name='extravariantattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributes'),
        ),
        migrations.AddField(
            model_name='extravariantattribute',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='bridge_width',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Width'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bridge_width', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='frame_color',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_color', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='frame_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Material'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_frame_material', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='frame_shape',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Shape'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_frame_shape', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='temple_length',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Length'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_temple_length', to='products.attributevalue'),
        ),
        migrations.CreateModel(
            name='StokLensVariant',
            fields=[
                ('productvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productvariant')),
                ('spherical', models.CharField(blank=True, choices=[('-30.00', '-30.00'), ('-29.75', '-29.75'), ('-29.50', '-29.50'), ('-29.25', '-29.25'), ('-29.00', '-29.00'), ('-28.75', '-28.75'), ('-28.50', '-28.50'), ('-28.25', '-28.25'), ('-28.00', '-28.00'), ('-27.75', '-27.75'), ('-27.50', '-27.50'), ('-27.25', '-27.25'), ('-27.00', '-27.00'), ('-26.75', '-26.75'), ('-26.50', '-26.50'), ('-26.25', '-26.25'), ('-26.00', '-26.00'), ('-25.75', '-25.75'), ('-25.50', '-25.50'), ('-25.25', '-25.25'), ('-25.00', '-25.00'), ('-24.75', '-24.75'), ('-24.50', '-24.50'), ('-24.25', '-24.25'), ('-24.00', '-24.00'), ('-23.75', '-23.75'), ('-23.50', '-23.50'), ('-23.25', '-23.25'), ('-23.00', '-23.00'), ('-22.75', '-22.75'), ('-22.50', '-22.50'), ('-22.25', '-22.25'), ('-22.00', '-22.00'), ('-21.75', '-21.75'), ('-21.50', '-21.50'), ('-21.25', '-21.25'), ('-21.00', '-21.00'), ('-20.75', '-20.75'), ('-20.50', '-20.50'), ('-20.25', '-20.25'), ('-20.00', '-20.00'), ('-19.75', '-19.75'), ('-19.50', '-19.50'), ('-19.25', '-19.25'), ('-19.00', '-19.00'), ('-18.75', '-18.75'), ('-18.50', '-18.50'), ('-18.25', '-18.25'), ('-18.00', '-18.00'), ('-17.75', '-17.75'), ('-17.50', '-17.50'), ('-17.25', '-17.25'), ('-17.00', '-17.00'), ('-16.75', '-16.75'), ('-16.50', '-16.50'), ('-16.25', '-16.25'), ('-16.00', '-16.00'), ('-15.75', '-15.75'), ('-15.50', '-15.50'), ('-15.25', '-15.25'), ('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00'), ('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00'), ('+06.25', '+06.25'), ('+06.50', '+06.50'), ('+06.75', '+06.75'), ('+07.00', '+07.00'), ('+07.25', '+07.25'), ('+07.50', '+07.50'), ('+07.75', '+07.75'), ('+08.00', '+08.00'), ('+08.25', '+08.25'), ('+08.50', '+08.50'), ('+08.75', '+08.75'), ('+09.00', '+09.00'), ('+09.25', '+09.25'), ('+09.50', '+09.50'), ('+09.75', '+09.75'), ('+10.00', '+10.00'), ('+10.25', '+10.25'), ('+10.50', '+10.50'), ('+10.75', '+10.75'), ('+11.00', '+11.00'), ('+11.25', '+11.25'), ('+11.50', '+11.50'), ('+11.75', '+11.75'), ('+12.00', '+12.00'), ('+12.25', '+12.25'), ('+12.50', '+12.50'), ('+12.75', '+12.75'), ('+13.00', '+13.00'), ('+13.25', '+13.25'), ('+13.50', '+13.50'), ('+13.75', '+13.75'), ('+14.00', '+14.00'), ('+14.25', '+14.25'), ('+14.50', '+14.50'), ('+14.75', '+14.75'), ('+15.00', '+15.00'), ('+15.25', '+15.25'), ('+15.50', '+15.50'), ('+15.75', '+15.75'), ('+16.00', '+16.00'), ('+16.25', '+16.25'), ('+16.50', '+16.50'), ('+16.75', '+16.75'), ('+17.00', '+17.00'), ('+17.25', '+17.25'), ('+17.50', '+17.50'), ('+17.75', '+17.75'), ('+18.00', '+18.00'), ('+18.25', '+18.25'), ('+18.50', '+18.50'), ('+18.75', '+18.75'), ('+19.00', '+19.00'), ('+19.25', '+19.25'), ('+19.50', '+19.50'), ('+19.75', '+19.75'), ('+20.00', '+20.00'), ('+20.25', '+20.25'), ('+20.50', '+20.50'), ('+20.75', '+20.75'), ('+21.00', '+21.00'), ('+21.25', '+21.25'), ('+21.50', '+21.50'), ('+21.75', '+21.75'), ('+22.00', '+22.00'), ('+22.25', '+22.25'), ('+22.50', '+22.50'), ('+22.75', '+22.75'), ('+23.00', '+23.00'), ('+23.25', '+23.25'), ('+23.50', '+23.50'), ('+23.75', '+23.75'), ('+24.00', '+24.00'), ('+24.25', '+24.25'), ('+24.50', '+24.50'), ('+24.75', '+24.75'), ('+25.00', '+25.00'), ('+25.25', '+25.25'), ('+25.50', '+25.50'), ('+25.75', '+25.75'), ('+26.00', '+26.00'), ('+26.25', '+26.25'), ('+26.50', '+26.50'), ('+26.75', '+26.75'), ('+27.00', '+27.00'), ('+27.25', '+27.25'), ('+27.50', '+27.50'), ('+27.75', '+27.75'), ('+28.00', '+28.00'), ('+28.25', '+28.25'), ('+28.50', '+28.50'), ('+28.75', '+28.75'), ('+29.00', '+29.00'), ('+29.25', '+29.25'), ('+29.50', '+29.50'), ('+29.75', '+29.75'), ('+30.00', '+30.00')], default=None, max_length=20, null=True)),
                ('cylinder', models.CharField(blank=True, choices=[('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00')], default=None, max_length=20, null=True)),
                ('lens_coatings', models.ManyToManyField(blank=True, limit_choices_to={'attribute_id__name': 'Coatings'}, related_name='%(class)s_lens_coatings', to='products.attributevalue')),
                ('lens_color', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_color', to='products.attributevalue')),
                ('lens_diameter', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Diameter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_diameter', to='products.attributevalue')),
                ('lens_material', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Material'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_material', to='products.attributevalue')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productvariant', models.Model),
        ),
        migrations.CreateModel(
            name='RxLensVariant',
            fields=[
                ('productvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productvariant')),
                ('addition', models.CharField(blank=True, choices=[('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00')], default=None, max_length=20, null=True)),
                ('lens_base_curve', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Base Curve'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_base_curve', to='products.attributevalue')),
                ('lens_coatings', models.ManyToManyField(blank=True, limit_choices_to={'attribute_id__name': 'Coatings'}, related_name='%(class)s_lens_coatings', to='products.attributevalue')),
                ('lens_color', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_color', to='products.attributevalue')),
                ('lens_diameter', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Diameter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_diameter', to='products.attributevalue')),
                ('lens_material', models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Material'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_material', to='products.attributevalue')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productvariant', models.Model),
        ),
        migrations.AddField(
            model_name='contactlensvariantexpiration_date',
            name='contact_lens_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.contactlensvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='extravariantattribute',
            unique_together={('variant_type', 'variant_id', 'attribute')},
        ),
    ]
