# Generated by Django 5.2.6 on 2025-10-14 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_productvariant_lens_water_content_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactLensVariantExpiration_date',
            new_name='ContactLensVariantExpirationDate',
        ),
        migrations.AlterModelOptions(
            name='contactlensvariantexpirationdate',
            options={'verbose_name': 'Contact Lens Variant Expiration Date', 'verbose_name_plural': 'Contact Lens Variant Expiration Dates'},
        ),
        migrations.RenameField(
            model_name='contactlensvariant',
            old_name='lens_water_content_id',
            new_name='lens_water_content',
        ),
        migrations.RenameField(
            model_name='contactlensvariant',
            old_name='replacement_schedule_id',
            new_name='replacement_schedule',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='extravariantattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='lens_color',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute_id__name': 'Color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_color', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='lens_diameter',
            field=models.ForeignKey(default=1, limit_choices_to={'attribute_id__name': 'Diameter'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_diameter', to='products.attributevalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactlensvariant',
            name='lens_diameter',
            field=models.ForeignKey(default=1, limit_choices_to={'attribute_id__name': 'Diameter'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_diameter', to='products.attributevalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extravariantattribute',
            name='variant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='framevariant',
            name='bridge_width',
            field=models.ForeignKey(default=1, limit_choices_to={'attribute_id__name': 'Width'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bridge_width', to='products.attributevalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='framevariant',
            name='frame_color',
            field=models.ForeignKey(default=1, limit_choices_to={'attribute_id__name': 'Color'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_color', to='products.attributevalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='framevariant',
            name='temple_length',
            field=models.ForeignKey(default=1, limit_choices_to={'attribute_id__name': 'Length'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_temple_length', to='products.attributevalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product_type',
            field=models.ForeignKey(default=1, limit_choices_to={'attribute_id__name': 'Product Type'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_product_type', to='products.attributevalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rxlensvariant',
            name='lens_diameter',
            field=models.ForeignKey(default=1, limit_choices_to={'attribute_id__name': 'Diameter'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_diameter', to='products.attributevalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stoklensvariant',
            name='lens_diameter',
            field=models.ForeignKey(default=1, limit_choices_to={'attribute_id__name': 'Diameter'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_diameter', to='products.attributevalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stoklensvariant',
            name='spherical',
            field=models.CharField(choices=[('-30.00', '-30.00'), ('-29.75', '-29.75'), ('-29.50', '-29.50'), ('-29.25', '-29.25'), ('-29.00', '-29.00'), ('-28.75', '-28.75'), ('-28.50', '-28.50'), ('-28.25', '-28.25'), ('-28.00', '-28.00'), ('-27.75', '-27.75'), ('-27.50', '-27.50'), ('-27.25', '-27.25'), ('-27.00', '-27.00'), ('-26.75', '-26.75'), ('-26.50', '-26.50'), ('-26.25', '-26.25'), ('-26.00', '-26.00'), ('-25.75', '-25.75'), ('-25.50', '-25.50'), ('-25.25', '-25.25'), ('-25.00', '-25.00'), ('-24.75', '-24.75'), ('-24.50', '-24.50'), ('-24.25', '-24.25'), ('-24.00', '-24.00'), ('-23.75', '-23.75'), ('-23.50', '-23.50'), ('-23.25', '-23.25'), ('-23.00', '-23.00'), ('-22.75', '-22.75'), ('-22.50', '-22.50'), ('-22.25', '-22.25'), ('-22.00', '-22.00'), ('-21.75', '-21.75'), ('-21.50', '-21.50'), ('-21.25', '-21.25'), ('-21.00', '-21.00'), ('-20.75', '-20.75'), ('-20.50', '-20.50'), ('-20.25', '-20.25'), ('-20.00', '-20.00'), ('-19.75', '-19.75'), ('-19.50', '-19.50'), ('-19.25', '-19.25'), ('-19.00', '-19.00'), ('-18.75', '-18.75'), ('-18.50', '-18.50'), ('-18.25', '-18.25'), ('-18.00', '-18.00'), ('-17.75', '-17.75'), ('-17.50', '-17.50'), ('-17.25', '-17.25'), ('-17.00', '-17.00'), ('-16.75', '-16.75'), ('-16.50', '-16.50'), ('-16.25', '-16.25'), ('-16.00', '-16.00'), ('-15.75', '-15.75'), ('-15.50', '-15.50'), ('-15.25', '-15.25'), ('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00'), ('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00'), ('+06.25', '+06.25'), ('+06.50', '+06.50'), ('+06.75', '+06.75'), ('+07.00', '+07.00'), ('+07.25', '+07.25'), ('+07.50', '+07.50'), ('+07.75', '+07.75'), ('+08.00', '+08.00'), ('+08.25', '+08.25'), ('+08.50', '+08.50'), ('+08.75', '+08.75'), ('+09.00', '+09.00'), ('+09.25', '+09.25'), ('+09.50', '+09.50'), ('+09.75', '+09.75'), ('+10.00', '+10.00'), ('+10.25', '+10.25'), ('+10.50', '+10.50'), ('+10.75', '+10.75'), ('+11.00', '+11.00'), ('+11.25', '+11.25'), ('+11.50', '+11.50'), ('+11.75', '+11.75'), ('+12.00', '+12.00'), ('+12.25', '+12.25'), ('+12.50', '+12.50'), ('+12.75', '+12.75'), ('+13.00', '+13.00'), ('+13.25', '+13.25'), ('+13.50', '+13.50'), ('+13.75', '+13.75'), ('+14.00', '+14.00'), ('+14.25', '+14.25'), ('+14.50', '+14.50'), ('+14.75', '+14.75'), ('+15.00', '+15.00'), ('+15.25', '+15.25'), ('+15.50', '+15.50'), ('+15.75', '+15.75'), ('+16.00', '+16.00'), ('+16.25', '+16.25'), ('+16.50', '+16.50'), ('+16.75', '+16.75'), ('+17.00', '+17.00'), ('+17.25', '+17.25'), ('+17.50', '+17.50'), ('+17.75', '+17.75'), ('+18.00', '+18.00'), ('+18.25', '+18.25'), ('+18.50', '+18.50'), ('+18.75', '+18.75'), ('+19.00', '+19.00'), ('+19.25', '+19.25'), ('+19.50', '+19.50'), ('+19.75', '+19.75'), ('+20.00', '+20.00'), ('+20.25', '+20.25'), ('+20.50', '+20.50'), ('+20.75', '+20.75'), ('+21.00', '+21.00'), ('+21.25', '+21.25'), ('+21.50', '+21.50'), ('+21.75', '+21.75'), ('+22.00', '+22.00'), ('+22.25', '+22.25'), ('+22.50', '+22.50'), ('+22.75', '+22.75'), ('+23.00', '+23.00'), ('+23.25', '+23.25'), ('+23.50', '+23.50'), ('+23.75', '+23.75'), ('+24.00', '+24.00'), ('+24.25', '+24.25'), ('+24.50', '+24.50'), ('+24.75', '+24.75'), ('+25.00', '+25.00'), ('+25.25', '+25.25'), ('+25.50', '+25.50'), ('+25.75', '+25.75'), ('+26.00', '+26.00'), ('+26.25', '+26.25'), ('+26.50', '+26.50'), ('+26.75', '+26.75'), ('+27.00', '+27.00'), ('+27.25', '+27.25'), ('+27.50', '+27.50'), ('+27.75', '+27.75'), ('+28.00', '+28.00'), ('+28.25', '+28.25'), ('+28.50', '+28.50'), ('+28.75', '+28.75'), ('+29.00', '+29.00'), ('+29.25', '+29.25'), ('+29.50', '+29.50'), ('+29.75', '+29.75'), ('+30.00', '+30.00')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='extravariantattribute',
            unique_together={('variant_type', 'variant_id', 'attribute', 'value')},
        ),
    ]
