# Generated by Django 5.2.6 on 2025-10-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_contactlensvariantexpiration_date_contactlensvariantexpirationdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extravariantattribute',
            name='variant_id',
        ),
        migrations.AddField(
            model_name='extravariantattribute',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productvariant_set', to='products.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extravariantattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_set', to='products.attributes'),
        ),
        migrations.AlterField(
            model_name='extravariantattribute',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributevalue_set', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='extravariantattribute',
            name='variant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extravariantattribute_set', to='products.attributes'),
        ),
    ]
