# Generated by Django 5.2.9 on 2026-06-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrecord',
            name='dependent_name',
            field=models.CharField(blank=True, help_text='If the prescription is for a family member or dependent, enter their name here.', max_length=100, null=True, verbose_name='Dependent Name'),
        ),
    ]
