# Generated by Django 5.2.9 on 2025-12-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionrecord',
            old_name='a_v_left',
            new_name='segment_height_left',
        ),
        migrations.RenameField(
            model_name='prescriptionrecord',
            old_name='a_v_right',
            new_name='segment_height_right',
        ),
        migrations.RenameField(
            model_name='prescriptionrecord',
            old_name='sigmant_left',
            new_name='visual_acuity_left',
        ),
        migrations.RenameField(
            model_name='prescriptionrecord',
            old_name='sigmant_right',
            new_name='visual_acuity_right',
        ),
    ]
