export interface FormConfig {
  schemaName?: string;
  createAlias?: string;
  retrieveAlias?: string;
  updateAlias?: string;
  hardDeleteAlias?: string;
  createSuccessMessage?: string;
  createErrorMessage?: string;
  updateSuccessMessage?: string;
  updateErrorMessage?: string;
  title?: string;
  detailsTitle?: string;
  createTitle?: string;
  updateTitle?: string;
  fields: string[];
  detailsField: string[];
  listAlias?: string;
  userConfig?:object,
  showResetButton?:boolean,
  showBackButton?:boolean,
  className?:string
}

export const formsConfig: Record<string, FormConfig> = {

  client:{
    schemaName: 'ClientRequest',
    listAlias: 'tenants_clients_list',
    createAlias: 'tenants_register_create',
    retrieveAlias: 'tenants_clients_retrieve',
    updateAlias: 'tenants_clients_partial_update',
    hardDeleteAlias: 'tenants_clients_destroy',
    fields:["name","max_branches","max_users"],
    detailsField:[ "name","max_branches","max_users","website","is_active","paid_until", ],
  },
  registerTenant:{
    schemaName: 'RegisterTenantRequest',
    listAlias: 'tenants_register_list',
    createAlias: 'tenants_register_create',
    retrieveAlias: 'tenants_register_retrieve',
    updateAlias: 'tenants_register_partial_update',
    hardDeleteAlias: 'tenants_register_destroy',
    fields:["name","email"],
    detailsField:["name","email","password"],
  },
  domain:{
    retrieveAlias: 'tenants_domain_retrieve',
    fields:["domain"],
    detailsField:["domain","is_active"],
  },
  payment:{
    retrieveAlias: 'tenants_payments_retrieve',
    fields:["amount","transaction_id","status","client"],
    detailsField:["amount","transaction_id","status","client","created_at","updated_at","method","currency"],
  },
  subscriptionPlan:{
    schemaName: 'SubscriptionPlanRequest',
    listAlias: 'tenants_subscription_plans_list',
    createAlias: 'tenants_subscription_plans_create',
    updateAlias: 'tenants_subscription_plans_update',
    retrieveAlias: 'tenants_subscription_plans_retrieve',
    hardDeleteAlias: 'tenants_subscription_plans_destroy',
    fields:["name","max_users","max_branches","description"],
    detailsField:["name","max_users","max_branches","description","month_price","year_price","currency","discount"],
  },

  role:{
    schemaName: 'PatchedRoleRequest',
    listAlias: 'users_roles_list',
    createAlias: 'users_roles_create',
    retrieveAlias: 'users_roles_retrieve',
    updateAlias: 'users_roles_partial_update',
    hardDeleteAlias: 'users_roles_destroy',
    fields:["name","description"],
    detailsField:["name","description","is_active","is_deleted"],
  },
  user: {
    schemaName: 'UserRequest',
    listAlias: 'users_users_list',
    createAlias: 'users_users_create',
    retrieveAlias: 'users_users_retrieve',
    updateAlias: 'users_users_partial_update',
    hardDeleteAlias: 'users_users_destroy',
    fields:["username","email","phone","role","is_active"],
    detailsField:["username","email","phone","role","is_active","address","website"],
  },
  permissions:{
    schemaName: 'PermissionRequest',
    listAlias: 'users_permissions_list',
    createAlias: 'users_permissions_create',
    retrieveAlias: 'users_permissions_retrieve',
    updateAlias: 'users_permissions_partial_update',
    hardDeleteAlias: 'users_permissions_destroy',
    fields:["code","description"],
    detailsField:["code","description"],
  },
  rolePermission:{
    schemaName: 'RolePermissionRequest',
    listAlias: 'users_role_permissions_list',
    createAlias: 'users_role_permissions_create',
    retrieveAlias: 'users_role_permissions_retrieve',
    updateAlias: 'users_role_permissions_partial_update',
    hardDeleteAlias: 'users_role_permissions_destroy',
    fields:["role","permission"],
    detailsField:["role","permission"],
  },
  contactUs:{
    schemaName: 'ContactUsRequest',
    listAlias: 'users_contact_us_list',
    createAlias: 'users_contact_us_create',
    retrieveAlias: 'users_contact_us_retrieve',
    updateAlias: 'users_contact_us_partial_update',
    hardDeleteAlias: 'users_contact_us_destroy',
    fields:["name","email","phone","message"],
    detailsField:["name","email","phone","message","created_at","updated_at","is_deleted","is_active"],
  },
  tenant_settings:{
    schemaName: 'TenantSettingsRequest',
    listAlias: 'users_tenant_settings_list',
    createAlias: 'users_tenant_settings_create',
    retrieveAlias: 'users_tenant_settings_retrieve',
    updateAlias: 'users_tenant_settings_partial_update',
    hardDeleteAlias: 'users_tenant_settings_destroy',
    fields:["business_name","phone","email"],
    detailsField:["business_name","phone","email","facebook","instagram","twitter","linkedin","description","is_active","is_deleted"],
  },
  department: {
    schemaName: 'Department',
    createAlias: 'hrm_departments_create',
    listAlias: 'hrm_departments_list',
    retrieveAlias: 'hrm_departments_retrieve',
    updateAlias: 'hrm_departments_partial_update',
    hardDeleteAlias: 'hrm_departments_destroy',
    createSuccessMessage: 'Department created successfully',
    createErrorMessage: 'Failed to create department',
    updateSuccessMessage: 'Department updated successfully',
    updateErrorMessage: 'Failed to update department',
    title: 'Department',
    detailsTitle: 'Department Details',
    createTitle: 'Add Department',
    updateTitle: 'Update Department',
    fields:["name","description"],
    detailsField:["name","description","is_active","is_deleted"],
    showResetButton:true,
    showBackButton:true,
    className:"",
    userConfig:{},

  },
  supplier: {
    schemaName: 'SupplierRequest',
    listAlias: 'products_suppliers_list',
    createAlias: 'products_suppliers_create',
    retrieveAlias: 'products_suppliers_retrieve',
    updateAlias: 'products_suppliers_partial_update',
    hardDeleteAlias: 'products_suppliers_destroy',
    createSuccessMessage: 'Supplier created successfully',
    createErrorMessage: 'Failed to create supplier',
    updateSuccessMessage: 'Supplier updated successfully',
    updateErrorMessage: 'Failed to update supplier',
    title: 'Supplier',
    detailsTitle: 'Supplier Details',
    createTitle: 'Add Supplier',
    updateTitle: 'Update Supplier',
    fields:["name","email","phone"],
    detailsField:["name","email","phone","address","website","is_active","is_deleted"],

  },
  branch: {
    schemaName: 'BranchRequest',
    listAlias: 'branches_branches_list',
    createAlias: 'branches_branches_create',
    retrieveAlias: 'branches_branches_retrieve',
    updateAlias: 'branches_branches_partial_update',
    hardDeleteAlias: 'branches_branches_destroy',
    fields:["name","description"],
    detailsField:["name","description","is_active","is_deleted"],
    showResetButton:true,
    showBackButton:true,
    className:"",
    userConfig:{},

  },
  employees:{
    schemaName: 'EmployeeRequest',
    listAlias: 'hrm_employees_list',
    createAlias: 'hrm_employees_create',
    retrieveAlias: 'hrm_employees_retrieve',
    updateAlias: 'hrm_employees_partial_update',
    hardDeleteAlias: 'hrm_employees_destroy',
    createSuccessMessage: 'Employee created successfully',
    createErrorMessage: 'Failed to create employee',
    updateSuccessMessage: 'Employee updated successfully',
    updateErrorMessage: 'Failed to update employee',
    title: 'Employee',
    detailsTitle: 'Employee Details',
    createTitle: 'Add Employee',
    updateTitle: 'Update Employee',
    fields:["name","email","phone"],
    detailsField:["name","email","phone","address","website","is_active","is_deleted"],
    showResetButton:true,
    showBackButton:true,
    className:"",
    userConfig:{},
  },
  customer:{
    schemaName: 'CustomerRequest',
    listAlias: 'crm_customers_list',
    createAlias: 'crm_customers_create',
    retrieveAlias: 'crm_customers_retrieve',
    updateAlias: 'crm_customers_partial_update',
    hardDeleteAlias: 'crm_customers_destroy',
    createSuccessMessage: 'Customer created successfully',
    createErrorMessage: 'Failed to create customer',
    updateSuccessMessage: 'Customer updated successfully',
    updateErrorMessage: 'Failed to update customer',
    title: 'Customer',
    detailsTitle: 'Customer Details',
    createTitle: 'Add Customer',
    updateTitle: 'Update Customer',
    fields:["name","email","phone"],
    detailsField:["name","email","phone","address","website","is_active","is_deleted"],
    showResetButton:true,
    showBackButton:true,
    className:"",
    userConfig:{},
  },
  manufacturer:{
    schemaName: 'ManufacturerRequest',
    listAlias: 'products_manufacturers_list',
    createAlias: 'products_manufacturers_create',
    retrieveAlias: 'products_manufacturers_retrieve',
    updateAlias: 'products_manufacturers_partial_update',
    hardDeleteAlias: 'products_manufacturers_destroy',
    createSuccessMessage: 'Manufacturer created successfully',
    createErrorMessage: 'Failed to create manufacturer',
    updateSuccessMessage: 'Manufacturer updated successfully',
    updateErrorMessage: 'Failed to update manufacturer',
    title: 'Manufacturer',
    detailsTitle: 'Manufacturer Details',
    createTitle: 'Add Manufacturer',
    updateTitle: 'Update Manufacturer',
    fields:["name","email","phone"],
    detailsField:["name","email","phone","address","website","is_active","is_deleted"],
    showResetButton:true,
    showBackButton:true,
    className:"",
    userConfig:{},
  },
  subscription:{
    schemaName: 'SubscriptionPlanRequest',
    listAlias: 'tenants_subscription_plans_list',
    createAlias: 'tenants_subscription_plans_create',
    retrieveAlias: 'tenants_subscription_plans_retrieve',
    updateAlias: 'tenants_subscription_plans_partial_update',
    hardDeleteAlias: 'tenants_subscription_plans_destroy',
    createSuccessMessage: 'Subscription Plan created successfully',
    createErrorMessage: 'Failed to create subscription plan',
    updateSuccessMessage: 'Subscription Plan updated successfully',
    updateErrorMessage: 'Failed to update subscription plan',
    title: 'Subscription Plan',
    detailsTitle: 'Subscription Plan Details',
    createTitle: 'Add Subscription Plan',
    updateTitle: 'Update Subscription Plan',
    fields:["name","email","phone"],
    detailsField:[
      "name",
      "email",
      "phone",
      "address",
      "website",
      "is_active",
      "is_deleted",
    ],
    showResetButton:true,
    showBackButton:true,
    className:"",
    userConfig:{ }
  },
};
