# Generated by Django 5.2.1 on 2025-08-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_genericpage_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='careerspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='genericpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='privacypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='supportpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='termspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='CareersPage',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='FAQPage',
        ),
        migrations.DeleteModel(
            name='GenericPage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='PrivacyPage',
        ),
        migrations.DeleteModel(
            name='SupportPage',
        ),
        migrations.DeleteModel(
            name='TermsPage',
        ),
    ]
