# Generated by Django 5.2.1 on 2025-08-13 18:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_contactpage_body_contactpage_banner_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='tech_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='tech_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
