# Generated by Django 5.2.6 on 2025-12-17 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchusers',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='branchusers',
            unique_together={('branch_id', 'employee_id')},
        ),
    ]
