# Generated by Django 5.2.9 on 2025-12-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('hrm', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchusers',
            unique_together={('branch', 'employee')},
        ),
        migrations.AddField(
            model_name='branchusers',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='branches.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchusers',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_branches', to='hrm.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='branches.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hrm.employee')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='branchusers',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='branchusers',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='branchusers',
            name='status',
        ),
    ]
