# Generated by Django 5.2.9 on 2026-01-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('hrm', '0003_alter_attendance_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='branchusers',
            options={'verbose_name': 'Branch User', 'verbose_name_plural': 'Branch Users'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start_time'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='allows_online_orders',
            field=models.BooleanField(default=True, verbose_name='Allows Online Orders'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='Branch Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('store', 'Store'), ('branch', 'Branch')], max_length=10, verbose_name='Branch Type'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.TextField(blank=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_main_branch',
            field=models.BooleanField(default=False, verbose_name='Is Main Branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='Operating Hours'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='branchusers',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='branchusers',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_branches', to='hrm.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='branchusers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='branchusers',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hrm.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
