# Generated by Django 5.2.9 on 2026-06-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='additional_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Additional Number'),
        ),
        migrations.AddField(
            model_name='branch',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Building Number'),
        ),
        migrations.AddField(
            model_name='branch',
            name='cr_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='CR Number (Sub)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='branch',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='branch',
            name='receipt_footer',
            field=models.TextField(blank=True, help_text='Text printed at the bottom (e.g. Return Policy)', verbose_name='Receipt Footer'),
        ),
        migrations.AddField(
            model_name='branch',
            name='receipt_header',
            field=models.TextField(blank=True, help_text='Text printed at the top of the receipt', verbose_name='Receipt Header'),
        ),
        migrations.AddField(
            model_name='branch',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street Name'),
        ),
        migrations.AddField(
            model_name='branch',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax Number (VAT)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, verbose_name='Full Address (Legacy)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.CharField(default='Saudi Arabia', max_length=100, verbose_name='Country'),
        ),
    ]
