# Generated by Django 5.2.9 on 2026-08-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_additional_number_branch_building_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='zatca_certificate',
            field=models.TextField(blank=True, verbose_name='ZATCA Stamp Certificate'),
        ),
        migrations.AddField(
            model_name='branch',
            name='zatca_csid',
            field=models.TextField(blank=True, verbose_name='ZATCA CSID Token'),
        ),
        migrations.AddField(
            model_name='branch',
            name='zatca_environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('simulation', 'Simulation'), ('production', 'Production')], default='sandbox', max_length=20, verbose_name='ZATCA Environment'),
        ),
        migrations.AddField(
            model_name='branch',
            name='zatca_private_key',
            field=models.TextField(blank=True, verbose_name='ZATCA Private Key (ECDSA)'),
        ),
    ]
