# Generated by Django 5.2.9 on 2026-08-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_zatca_certificate_branch_zatca_csid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Shift Name')),
                ('day_of_week', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20, verbose_name='Day of Week')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='branches.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Branch Shift Template',
                'verbose_name_plural': 'Branch Shift Templates',
                'unique_together': {('branch', 'name', 'day_of_week')},
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shifts', to='branches.branchshifttemplate', verbose_name='Shift Template'),
        ),
    ]
