# Generated by Django 5.2.9 on 2026-06-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stockmovement_invoice_stockmovement_purchase_order'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='products.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='invoicetype',
            name='action_type',
            field=models.CharField(choices=[('sale', 'Sale (Decrease Stock, Increase Revenue)'), ('purchase', 'Purchase (Increase Stock, Increase Payable)'), ('return_sale', 'Sale Return (Increase Stock, Decrease Revenue)'), ('return_purchase', 'Purchase Return (Decrease Stock, Decrease Payable)'), ('neutral', 'Neutral (No Stock Impact)')], default='sale', help_text='Defines how this invoice affects stock and accounting', max_length=20, verbose_name='Action Type'),
        ),
    ]
