# Generated by Django 5.2.9 on 2026-01-24 20:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_options_alter_branchusers_options_and_more'),
        ('crm', '0004_alter_campaign_options_alter_claimdocument_options_and_more'),
        ('prescriptions', '0003_alter_prescriptionrecord_options_and_more'),
        ('products', '0003_alter_attribute_options_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['payment', 'installment_number'], 'verbose_name': 'Installment', 'verbose_name_plural': 'Installments'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.PositiveIntegerField(verbose_name='Installment Number'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='sales.payment', verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_branch', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='branches.branchusers', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_customer', to='crm.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return_purchase', 'Purchase Return'), ('return_sale', 'Sale Return')], default='sale', max_length=20, verbose_name='Invoice Type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_order', to='sales.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('confirmed', 'Confirmed')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_variant', to='products.productvariant', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_branch', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_customer', to='crm.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_partner_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.customerpartnerlink', verbose_name='Customer Partner Link'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_share',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount due from customer directly', max_digits=12, verbose_name='Customer Share'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected Delivery Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('insurance', 'Insurance'), ('bnpl', 'Installment'), ('corporate', 'Corporate'), ('wholesale', 'Wholesale')], default='cash', max_length=20, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='partner_share',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount due from partner (insurance/installment)', max_digits=12, verbose_name='Partner Share'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branchusers', verbose_name='Sales Person'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='prescriptions.prescriptionrecord', verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_variant', to='products.productvariant', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bnpl_order_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='BNPL Order ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, verbose_name='Card Brand'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, verbose_name='Card Last 4 Digits'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cheque_bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True, verbose_name='Cheque Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cheque Number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='SAR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='Gateway Response'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Installment Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installments_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Installments Count'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='Is Installment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Refund Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Refund Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transfer_bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transfer Reference'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='payment_icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
    ]
