# Generated by Django 5.2.9 on 2026-01-09 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_partner_and_insurance_models'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_partner_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.customerpartnerlink', verbose_name='ربط العميل بالشريك'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_share',
            field=models.DecimalField(decimal_places=2, default=0, help_text='المبلغ المستحق من العميل مباشرة', max_digits=12, verbose_name='حصة العميل'),
        ),
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.partner', verbose_name='الشريك'),
        ),
        migrations.AddField(
            model_name='order',
            name='partner_share',
            field=models.DecimalField(decimal_places=2, default=0, help_text='المبلغ المستحق من الشريك (تأمين/تقسيط)', max_digits=12, verbose_name='حصة الشريك'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('bank_transfer', 'تحويل بنكي'), ('mada', 'مدى'), ('visa', 'فيزا'), ('master', 'ماستر كارد'), ('apple_pay', 'Apple Pay'), ('stc_pay', 'STC Pay'), ('tabby', 'تابي'), ('tamara', 'تمارا'), ('insurance', 'تأمين'), ('credit', 'آجل'), ('mixed', 'مختلط')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل'), ('insurance', 'تأمين'), ('bnpl', 'تقسيط'), ('corporate', 'شركات'), ('wholesale', 'جملة')], default='cash', max_length=20),
        ),
    ]
