# Generated by Django 5.2.9 on 2026-06-18 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_customer_contract_end_date_and_more'),
        ('sales', '0002_invoice_purchase_order_invoicetype_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_partner', to='crm.partner', verbose_name='Partner (B2B/Insurance)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partner_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Partner Amount (Insurance/B2B)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Patient Amount (Copay/Cash)'),
        ),
        migrations.AddField(
            model_name='order',
            name='partner_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Partner Amount (Insurance/B2B)'),
        ),
        migrations.AddField(
            model_name='order',
            name='patient_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Patient Amount (Copay/Cash)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_customer', to='crm.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_customer', to='crm.customer', verbose_name='Customer'),
        ),
    ]
