# Generated by Django 5.2.9 on 2026-02-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_taxrate'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0007_pricingpolicy_alter_stockmovement_movement_type_and_more'),
        ('sales', '0002_alter_installment_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='SAR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type_code',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return_purchase', 'Purchase Return'), ('return_sale', 'Sale Return')], default='sale', max_length=20, verbose_name='Invoice Type Code (Legacy)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pricing_policy_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pricing Policy Snapshot'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tax Snapshot'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount (Base)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount_foreign',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount (Foreign)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount (Base Currency)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_foreign',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount (Foreign Currency)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gl_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts', verbose_name='GL Account (Asset)'),
        ),
        migrations.CreateModel(
            name='InvoiceTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tax Amount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='sales.invoice', verbose_name='Invoice')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.taxrate', verbose_name='Tax Rate')),
            ],
            options={
                'verbose_name': 'Invoice Tax',
                'verbose_name_plural': 'Invoice Taxes',
            },
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Invoice Type Name')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.pricingpolicy', verbose_name='Pricing Policy')),
                ('revenue_account', models.ForeignKey(limit_choices_to={'account_type': 'revenue'}, on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts', verbose_name='Revenue GL Account')),
            ],
            options={
                'verbose_name': 'Invoice Type',
                'verbose_name_plural': 'Invoice Types',
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.invoicetype', verbose_name='Invoice Type'),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Allocated Amount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='sales.invoice', verbose_name='Invoice')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='sales.invoiceitem', verbose_name='Invoice Item (Optional)')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'unique_together': {('payment', 'invoice', 'invoice_item')},
            },
        ),
    ]
