# Generated by Django 5.2.9 on 2026-06-19 10:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_additional_number_branch_building_number_and_more'),
        ('crm', '0004_remove_customer_contract_end_date_and_more'),
        ('products', '0005_flexibleprice_brand_flexibleprice_category_and_more'),
        ('sales', '0003_invoice_partner_invoice_partner_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='current_invoice_hash',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Current Invoice Hash (ZATCA)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Invoice UUID (ZATCA)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='previous_invoice_hash',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Previous Invoice Hash (ZATCA)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_tax_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='ZATCA Tax Number (Final)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='Subtotal (Before Tax)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5, verbose_name='Tax Percent'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='Subtotal (Before Tax)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5, verbose_name='Tax Percent'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Invoice Number (Draft/Internal)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('confirmed', 'Confirmed'), ('pending_clearance', 'Pending Clearance'), ('cleared', 'Cleared (ZATCA)'), ('rejected', 'Rejected (ZATCA)'), ('reported', 'Reported (ZATCA)')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=4, editable=False, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=4, editable=False, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Unit Price'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5, verbose_name='Tax Rate')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Paid Amount')),
                ('patient_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Patient Amount (Copay/Cash)')),
                ('partner_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Partner Amount (Insurance/B2B)')),
                ('credit_note_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Credit Note Number')),
                ('credit_note_uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Credit Note UUID (ZATCA)')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason for Issuance')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('confirmed', 'Confirmed'), ('pending_clearance', 'Pending Clearance'), ('cleared', 'Cleared (ZATCA)'), ('rejected', 'Rejected (ZATCA)'), ('reported', 'Reported (ZATCA)')], default='draft', max_length=20, verbose_name='Status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Date')),
                ('zatca_tax_number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='ZATCA Tax Number (Final)')),
                ('previous_hash', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Previous Hash (ZATCA)')),
                ('current_hash', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Current Hash (ZATCA)')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_branch', to='branches.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_notes', to='branches.branchusers', verbose_name='Created By')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_customer', to='crm.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.invoice', verbose_name='Original Invoice')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_partner', to='crm.partner', verbose_name='Partner (B2B/Insurance)')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Unit Price')),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Discount Amount')),
                ('tax_percent', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5, verbose_name='Tax Percent')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='Tax Amount')),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='Subtotal (Before Tax)')),
                ('total_price', models.DecimalField(decimal_places=4, editable=False, max_digits=12, verbose_name='Total Price')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.creditnote', verbose_name='Credit Note')),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_variant', to='products.productvariant', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Credit Note Item',
                'verbose_name_plural': 'Credit Note Items',
            },
        ),
    ]
