# Generated by Django 5.2.9 on 2026-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_currency_invoice_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Date'),
        ),
    ]
