# Generated by Django 5.2.9 on 2026-06-19 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_current_invoice_hash_invoice_invoice_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='credit_note_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Credit Note UUID (ZATCA)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Invoice UUID (ZATCA)'),
        ),
    ]
