# Generated by Django 5.2.9 on 2026-02-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_options_alter_branchusers_options_and_more'),
        ('sales', '0004_invoice_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to='branches.branchusers', verbose_name='Created By'),
        ),
    ]
