# Generated by Django 5.2.9 on 2026-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_additional_number_branch_building_number_and_more'),
        ('crm', '0004_remove_customer_contract_end_date_and_more'),
        ('products', '0006_stockmovement_products_st_referen_c7aa1c_idx_and_more'),
        ('sales', '0005_alter_creditnote_credit_note_uuid_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-created_at'], name='sales_invoi_status_2c31ad_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-created_at'], name='sales_invoi_custome_707b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['branch', '-created_at'], name='sales_invoi_branch__be4446_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='sales_invoi_created_a99f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='sales_order_status_72c80a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='sales_order_custome_edf486_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', '-created_at'], name='sales_order_branch__9c63ee_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='sales_order_created_8a4d37_idx'),
        ),
    ]
