# Generated by Django 5.2.9 on 2026-08-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_invoice_sales_invoi_status_2c31ad_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetax',
            old_name='tax',
            new_name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='invoicetax',
            name='base_amount',
        ),
        migrations.AddField(
            model_name='invoicetax',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxable Amount'),
            preserve_default=False,
        ),
    ]
