# Generated by Django 5.2.1 on 2025-08-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
