# Generated by Django 5.2.1 on 2025-07-30 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 17, 3, 37, 841062, tzinfo=datetime.timezone.utc), verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 17, 3, 37, 841012, tzinfo=datetime.timezone.utc), verbose_name='Token Expires At'),
        ),
    ]
