# Generated by Django 5.2.1 on 2025-08-02 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 14, 2, 16, 166289, tzinfo=datetime.timezone.utc), verbose_name='Token Expires At'),
        ),
    ]
