# Generated by Django 5.2.1 on 2025-07-31 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_pendingtenantrequest_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 17, 17, 46, 123481, tzinfo=datetime.timezone.utc), verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 17, 17, 46, 123384, tzinfo=datetime.timezone.utc), verbose_name='Token Expires At'),
        ),
    ]
