# Generated by Django 5.2.1 on 2025-07-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_pendingtenantrequest_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtenantrequest',
            name='max_branches',
            field=models.IntegerField(default=1, verbose_name='Max Branches'),
        ),
    ]
