# Generated by Django 5.2.1 on 2025-08-01 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_payment_status_alter_pendingtenantrequest_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 31, 10, 27, 57, 504177, tzinfo=datetime.timezone.utc), verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 10, 27, 57, 504052, tzinfo=datetime.timezone.utc), verbose_name='Token Expires At'),
        ),
    ]
