# Generated by Django 5.2.1 on 2025-08-02 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_pendingtenantrequest_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 15, 1, 22, 544222, tzinfo=datetime.timezone.utc), verbose_name='Token Expires At'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('egp', 'EGP'), ('sar', 'SAR'), ('aud', 'AUD'), ('eur', 'EUR')], default='USD', max_length=10),
        ),
    ]
