# Generated by Django 5.2.1 on 2025-07-29 15:20

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_pendingtenantrequest_max_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('max_users', models.IntegerField()),
                ('max_products', models.IntegerField()),
                ('max_branches', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_branches',
            field=models.IntegerField(default=1, verbose_name='Max Branches'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_products',
            field=models.IntegerField(default=200, verbose_name='Max Products'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_users',
            field=models.IntegerField(default=1, verbose_name='Max Users'),
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='trial', max_length=20, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='pendingtenantrequest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='pendingtenantrequest',
            name='requested_plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='trial', max_length=20, verbose_name='Requested Plan'),
        ),
        migrations.AddField(
            model_name='pendingtenantrequest',
            name='token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 15, 19, 48, 859476, tzinfo=datetime.timezone.utc), verbose_name='Token Expires At'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 15, 19, 48, 859556, tzinfo=datetime.timezone.utc), verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='max_products',
            field=models.IntegerField(default=200, verbose_name='Max Products'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='max_users',
            field=models.IntegerField(default=1, verbose_name='Max Users'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True, verbose_name='Schema Name'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.client')),
            ],
        ),
    ]
