# Generated by Django 5.2.1 on 2025-07-29 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_subscriptionplan_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 15, 24, 51, 758292, tzinfo=datetime.timezone.utc), verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 15, 24, 51, 758231, tzinfo=datetime.timezone.utc), verbose_name='Token Expires At'),
        ),
    ]
