# Generated by Django 5.2.1 on 2025-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_pendingtenantrequest_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='token_expires_at',
            field=models.DateTimeField(verbose_name='Token Expires At'),
        ),
    ]
