# Generated by Django 5.2.1 on 2025-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('egp', 'EGP'), ('sar', 'SAR'), ('aud', 'AUD'), ('eur', 'EUR')], default='USD', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.PositiveIntegerField(default=30, verbose_name='Months'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_years',
            field=models.PositiveIntegerField(default=365, verbose_name='Years'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_branches',
            field=models.PositiveIntegerField(default=1, verbose_name='Max Branches'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_products',
            field=models.PositiveIntegerField(default=200, verbose_name='Max Products'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.PositiveIntegerField(default=1, verbose_name='Max Users'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='month_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Month Price'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='year_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Year Price'),
        ),
    ]
