# Generated by Django 5.2.1 on 2025-08-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.PositiveIntegerField(default=30, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_years',
            field=models.PositiveIntegerField(default=365, verbose_name='Year'),
        ),
    ]
