# Generated by Django 5.2.1 on 2025-08-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_subscriptionplan_duration_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_years',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='month_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='year_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Year'),
        ),
    ]
