# Generated by Django 5.2.9 on 2026-06-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('branches', '0002_initial'),
        ('hrm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='employees', to='branches.branch', verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_main_office',
            field=models.BooleanField(default=False, verbose_name='Is Main Office'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll', to='accounting.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
