# Generated by Django 5.2.9 on 2026-06-18 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_account_user_remove_journalentry_account_and_more'),
        ('hrm', '0003_employee_branches_employee_is_main_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll', to='accounting.generaljournal', verbose_name='Journal Entry'),
        ),
    ]
