# Generated by Django 5.2.1 on 2025-06-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
