# Generated by Django 5.2.1 on 2025-07-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('employee', 'Employee'), ('hr', 'HR'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('delivery', 'Delivery'), ('customer_service', 'Customer Service')], max_length=100),
        ),
    ]
