# Generated by Django 5.2.1 on 2025-07-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0007_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('hr', 'HR'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('delivery', 'Delivery'), ('customer_service', 'Customer Service')], default='employee', max_length=100),
        ),
    ]
