# Generated by Django 5.2.1 on 2025-07-30 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('branch_code', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('branch_type', models.CharField(choices=[('store', 'Store'), ('branch', 'Branch')], max_length=10)),
                ('country', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_main_branch', models.BooleanField(default=False)),
                ('allows_online_orders', models.BooleanField(default=True)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='BranchUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('status', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.employee')),
            ],
            options={
                'unique_together': {('branch_id', 'employee_id')},
            },
        ),
    ]
