# Generated by Django 5.2.1 on 2025-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchusers',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff')], default='manger', max_length=10),
            preserve_default=False,
        ),
    ]
