# Generated by Django 5.2.1 on 2025-07-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0009_alter_employee_hire_date'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchusers',
            old_name='branch',
            new_name='branch_id',
        ),
        migrations.RenameField(
            model_name='branchusers',
            old_name='employee',
            new_name='employee_id',
        ),
        migrations.AlterUniqueTogether(
            name='branchusers',
            unique_together={('branch_id', 'employee_id')},
        ),
        migrations.RemoveField(
            model_name='branchusers',
            name='role',
        ),
    ]
