# Generated by Django 5.2.1 on 2025-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_branch_branchusers_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
