# Generated by Django 5.2.1 on 2025-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_branch_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
