import { FormConfig } from "@/src/shared/types/formConfig";
export const formsConfig: Record<string, FormConfig> = {

  // TENANT APP
  clients: {
    // schemaName: 'ClientRequest',
    listAlias: "tenants_clients_list",
    createAlias: 'tenants_clients_create',
    retrieveAlias: "tenants_clients_retrieve",
    partialUpdateAlias: 'tenants_clients_partial_update',
    filterAlias: "tenants_clients_filter_options_retrieve",
    // hardDeleteAlias: 'tenants_clients_destroy',
    fields: ["name", "max_branches", "max_users"],
    detailsField: [
      "name",
      "max_branches",
      "max_users",
      "website",
      "is_active",
      "paid_until",
    ],
    isViewOnly: true,
  },
  domain: {
    schemaName: "DomainRequest",
    listAlias: "tenants_domain_list",
    createAlias: "tenants_domain_create",
    partialUpdateAlias: "tenants_domain_partial_update",
    hardDeleteAlias: "tenants_domain_destroy",
    retrieveAlias: "tenants_domain_retrieve",
    filterAlias: "tenants_domain_filter_options_retrieve",
    fields: ["domain"],
    detailsField: ["domain", "is_active", "tenant", "id"],
    isViewOnly: false,
  },
  "register-tenants": {
    schemaName: "RegisterTenantRequest",
    listAlias: "tenants_registers_list",
    createAlias: "tenants_register_create", //tenants_registers_create
    retrieveAlias: "tenants_registers_retrieve",
    partialUpdateAlias: "tenants_registers_partial_update",
    filterAlias: "tenants_registers_filter_options_retrieve",
    hardDeleteAlias: "tenants_registers_destroy",
    fields: ["name", "email"],
    detailsField: ["name", "email"],
  },
  "subscription-plans": {
    schemaName: "SubscriptionPlanRequest",
    listAlias: "tenants_subscription_plans_list",
    createAlias: "tenants_subscription_plans_create",
    partialUpdateAlias: "tenants_subscription_plans_partial_update",
    retrieveAlias: "tenants_subscription_plans_retrieve",
    hardDeleteAlias: "tenants_subscription_plans_destroy",
    filterAlias: "tenants_subscription_plans_filter_options_retrieve",
    fields: ["name", "max_users", "max_branches", "description"],
    detailsField: [
      "name",
      "max_users",
      "max_branches",
      "description",
      "month_price",
      "year_price",
      "currency",
      "discount",
    ],
  },
  "tenants-activate": {
    retrieveAlias: "tenants_activate_retrieve",
  },
  "tenants_create_payment_order": {
    createAlias: "tenants_create_payment_order_create",
  },
  "tenants_paypal_cancel": {
    retrieveAlias: "tenants_paypal_cancel_retrieve",
  },
  "tenants_paypal_execute": {
    createAlias: "tenants_paypal_execute_create"
  },
  "tenants_paypal_webhook": {
    createAlias: "tenants_paypal_webhook_create",
  },

  // USERS APP
  "app-health": {
    retrieveAlias: "users_health_retrieve",
  },
  "contact-us": {
    schemaName: "ContactUsRequest",
    listAlias: "users_contact_us_list",
    createAlias: "users_contact_us_create",
    retrieveAlias: "users_contact_us_retrieve",
    partialUpdateAlias: "users_contact_us_partial_update",
    hardDeleteAlias: "users_contact_us_destroy",
    filterAlias: "users_contact_us_filter_options_retrieve",
    fields: ["name", "email", "phone", "message"],
    detailsField: [
      "name",
      "email",
      "phone",
      "message",
      "created_at",
      "updated_at",
      "is_active",
    ],
  },
  "login": {
    createAlias: "users_login_create",
  },
  "logout": {
    createAlias: "users_logout_create",
  },
  pages: {
    schemaName: "PageRequest",
    listAlias: "users_pages_list",
    createAlias: "users_pages_create",
    retrieveAlias: "users_pages_retrieve",
    partialUpdateAlias: "users_pages_partial_update",
    hardDeleteAlias: "users_pages_destroy",
    fields: ["name", "slug", "is_published"],
    filterAlias: "users_pages_filter_options_retrieve",
    detailsField: ["name", "slug", "is_published", "is_active"],
  },
  "password-reset": {
    createAlias: "users_password_reset_create",
  },
  "password-reset-confirm": {
    createAlias: "users_password_reset_confirm_create",
  },
  permissions: {
    schemaName: "PermissionRequest",
    listAlias: "users_permissions_list",
    createAlias: "users_permissions_create",
    retrieveAlias: "users_permissions_retrieve",
    partialUpdateAlias: "users_permissions_partial_update",
    hardDeleteAlias: "users_permissions_destroy",
    filterAlias: "users_permissions_filter_options_retrieve",
    fields: ["code", "description"],
    detailsField: ["code", "description", "is_active"],
  },
  "public-pages": {
    // listAlias: "users_public_pages_list",
    retrieveAlias: "users_public_pages_retrieve",
    detailsField: [],
    isViewOnly: true,
  },
  "register-users": {
    createAlias: "users_register_create",
  },
  "role-permissions": {
    schemaName: "RolePermissionRequest",
    listAlias: "users_role_permissions_list",
    createAlias: "users_role_permissions_create",
    retrieveAlias: "users_role_permissions_retrieve",
    partialUpdateAlias: "users_role_permissions_partial_update",
    hardDeleteAlias: "users_role_permissions_destroy",
    filterAlias: "users_role_permissions_filter_options_retrieve",
    fields: ["role_name", "permission_name"],
    detailsField: [
      "role_name",
      "permission_name",
      "is_active",
      "role",
      "permission",
    ],
  },
  roles: {
    schemaName: "PatchedRoleRequest",
    listAlias: "users_roles_list",
    createAlias: "users_roles_create",
    retrieveAlias: "users_roles_retrieve",
    filterAlias: "users_roles_filter_options_retrieve",
    partialUpdateAlias: "users_roles_partial_update",
    hardDeleteAlias: "users_roles_destroy",
    fields: ["name", "description", "permission_ids"],
    detailsField: ["name", "description", "permissions", "is_active"],
  },
  "tenant-settings": {
    schemaName: "TenantSettingsRequest",
    listAlias: "users_tenant_settings_list",
    createAlias: "users_tenant_settings_create",
    retrieveAlias: "users_tenant_settings_retrieve",
    partialUpdateAlias: "users_tenant_settings_partial_update",
    hardDeleteAlias: "users_tenant_settings_destroy",
    filterAlias: "users_tenant_settings_filter_options_retrieve",
    fields: ["business_name", "phone", "email"],
    detailsField: [
      "business_name",
      "phone",
      "email",
      "facebook",
      "instagram",
      "twitter",
      "linkedin",
      "website",
      "description",
      "is_active",
    ],
  },
  "user-profile": {
    retrieveAlias: "users_profile_retrieve",
  },
  users: {
    schemaName: "UserRequest",
    listAlias: "users_users_list",
    createAlias: "users_users_create",
    retrieveAlias: "users_users_retrieve",
    partialUpdateAlias: "users_users_partial_update",
    hardDeleteAlias: "users_users_destroy",
    filterAlias: "users_users_filter_options_retrieve",
    fields: ["username", "email", "phone", "roles", "is_active"],
    detailsField: [
      "username",
      "email",
      "phone",
      "roles",
      "is_active",
      "is_staff",
    ],
  },

  // CRM APP
  "crm-campaigns": {
    schemaName: "CampaignRequest",
    listAlias: "crm_campaigns_list",
    createAlias: "crm_campaigns_create",
    retrieveAlias: "crm_campaigns_retrieve",
    partialUpdateAlias: "crm_campaigns_partial_update",
    hardDeleteAlias: "crm_campaigns_destroy",
    filterAlias: "crm_campaigns_filter_options_retrieve",
    fields: ["name", "description"],
    detailsField: ["name", "description", "start_date", "end_date"],
  },
  "crm-claim-documents": {
    schemaName: "ClaimDocumentRequest",
    listAlias: "crm_claim_documents_list",
    createAlias: "crm_claim_documents_create",
    retrieveAlias: "crm_claim_documents_retrieve",
    partialUpdateAlias: "crm_claim_documents_partial_update",
    updateAlias: "crm_claim_documents_update",
    filterAlias: "crm_claim_documents_filter_options_retrieve",
    hardDeleteAlias: "crm_claim_documents_destroy",
    fields: ["document_type", "title", "created_at"],
    detailsField: [
      "claim",
      "document_type",
      "document_type_display",
      "title",
      "file",
      "notes",
      "created_at",
    ],
  },
  "crm-claim-items": {
    schemaName: "ClaimItemRequest",
    listAlias: "crm_claim_items_list",
    createAlias: "crm_claim_items_create",
    retrieveAlias: "crm_claim_items_retrieve",
    updateAlias: "crm_claim_items_update",
    partialUpdateAlias: "crm_claim_items_partial_update",
    filterAlias: "crm_claim_items_filter_options_retrieve",
    hardDeleteAlias: "crm_claim_items_destroy",
    fields: ["description", "quantity", "total_price", "approved_amount"],
    detailsField: [
      "claim",
      "order_item",
      "description",
      "quantity",
      "unit_price",
      "total_price",
      "claim_amount",
      "approved_amount",
      "insurance_code",
    ],
  },
  "crm-complaints": {
    schemaName: "ComplaintRequest",
    listAlias: "crm_complaints_list",
    createAlias: "crm_complaints_create",
    retrieveAlias: "crm_complaints_retrieve",
    partialUpdateAlias: "crm_complaints_partial_update",
    hardDeleteAlias: "crm_complaints_destroy",
    filterAlias: "crm_complaints_filter_options_retrieve",
    fields: ["customer_name", "description"],
    detailsField: ["customer_name", "description", "status", "is_active"],
  },
  "crm-contacts": {
    schemaName: "ContactRequest",
    listAlias: "crm_contact_us_list",
    createAlias: "crm_contact_us_create",
    retrieveAlias: "crm_contact_us_retrieve",
    partialUpdateAlias: "crm_contact_us_partial_update",
    hardDeleteAlias: "crm_contact_us_destroy",
    filterAlias: "crm_contact_us_filter_options_retrieve",
    fields: ["name", "email", "phone"],
    detailsField: ["name", "email", "phone", "message", "is_active"],
  },
  "crm-customer-groups": {
    schemaName: "CustomerGroupRequest",
    listAlias: "crm_customer_groups_list",
    createAlias: "crm_customer_groups_create",
    retrieveAlias: "crm_customer_groups_retrieve",
    partialUpdateAlias: "crm_customer_groups_partial_update",
    hardDeleteAlias: "crm_customer_groups_destroy",
    filterAlias: "crm_customer_groups_filter_options_retrieve",
    fields: ["name", "description"],
    detailsField: ["name", "description", "customers_name", "is_active"],
  },
  "crm-customer-partner-links": {
    schemaName: "CustomerPartnerLinkRequest",
    listAlias: "crm_customer_partner_links_list",
    createAlias: "crm_customer_partner_links_create",
    retrieveAlias: "crm_customer_partner_links_retrieve",
    updateAlias: "crm_customer_partner_links_update",
    partialUpdateAlias: "crm_customer_partner_links_partial_update",
    filterAlias: "crm_customer_partner_links_filter_options_retrieve",
    hardDeleteAlias: "crm_customer_partner_links_destroy",
    fields: ["customer_name", "partner_name", "policy_number", "is_active"],
    detailsField: [
      "customer",
      "customer_name",
      "partner",
      "partner_name",
      "partner_type",
      "membership_number",
      "policy_number",
      "coverage_start",
      "coverage_end",
      "annual_limit",
      "remaining_limit",
      "patient_share_percentage",
      "max_patient_share",
      "insurance_class",
      "is_active",
      "is_coverage_active",
      "notes",
    ],
  },
  "crm-customers": {
    schemaName: "CustomerRequest",
    listAlias: "crm_customers_list",
    createAlias: "crm_customers_create",
    retrieveAlias: "crm_customers_retrieve",
    partialUpdateAlias: "crm_customers_partial_update",
    hardDeleteAlias: "crm_customers_destroy",
    filterAlias: "crm_customers_filter_options_retrieve",
    fields: ["first_name", "last_name", "identification_number"],
    detailsField: [
      "first_name",
      "last_name",
      "identification_number",
      "email",
      "phone",
      "date_of_birth",
      "is_vip",
      "is_active",
    ],
  },
  "crm-documents": {
    schemaName: "DocumentRequest",
    listAlias: "crm_documents_list",
    createAlias: "crm_documents_create",
    retrieveAlias: "crm_documents_retrieve",
    partialUpdateAlias: "crm_documents_partial_update",
    hardDeleteAlias: "crm_documents_destroy",
    filterAlias: "crm_documents_filter_options_retrieve",
    fields: ["title", "customer_name"],
    detailsField: ["title", "customer_name", "file", "is_active"],
  },
  "crm-insurance-claims": {
    schemaName: "InsuranceClaimRequest",
    listAlias: "crm_insurance_claims_list",
    createAlias: "crm_insurance_claims_create",
    retrieveAlias: "crm_insurance_claims_retrieve",
    updateAlias: "crm_insurance_claims_update",
    partialUpdateAlias: "crm_insurance_claims_partial_update",
    filterAlias: "crm_insurance_claims_filter_options_retrieve",
    hardDeleteAlias: "crm_insurance_claims_destroy",
    fields: [
      "claim_number",
      "order_number",
      "partner_name",
      "total_amount",
      "status",
    ],
    detailsField: [
      "claim_number",
      "external_claim_number",
      "order",
      "order_number",
      "partner",
      "partner_name",
      "customer_partner_link",
      "customer_name",
      "claim_date",
      "submission_date",
      "response_date",
      "payment_date",
      "total_amount",
      "claim_amount",
      "approved_amount",
      "paid_amount",
      "patient_share",
      "status",
      "status_display",
      "rejection_reason",
      "partial_reason",
      "notes",
      "internal_notes",
      "created_at",
      "updated_at",
    ],
  },
  "crm-interactions": {
    schemaName: "InteractionRequest",
    listAlias: "crm_interactions_list",
    createAlias: "crm_interactions_create",
    retrieveAlias: "crm_interactions_retrieve",
    partialUpdateAlias: "crm_interactions_partial_update",
    hardDeleteAlias: "crm_interactions_destroy",
    filterAlias: "crm_interactions_filter_options_retrieve",
    fields: ["customer_name", "interaction_type"],
    detailsField: ["customer_name", "interaction_type", "notes", "is_active"],
  },
  "crm-opportunities": {
    schemaName: "OpportunityRequest",
    listAlias: "crm_opportunities_list",
    createAlias: "crm_opportunities_create",
    retrieveAlias: "crm_opportunities_retrieve",
    partialUpdateAlias: "crm_opportunities_partial_update",
    hardDeleteAlias: "crm_opportunities_destroy",
    filterAlias: "crm_opportunities_filter_options_retrieve",
    fields: ["name", "stage", "expected_revenue", "close_date"],
    detailsField: ["customer_name", "stage", "title", "close_date", "amount"],
  },
  "crm-partner-branches": {
    schemaName: "PartnerBranchRequest",
    listAlias: "crm_partner_branches_list",
    createAlias: "crm_partner_branches_create",
    retrieveAlias: "crm_partner_branches_retrieve",
    updateAlias: "crm_partner_branches_update",
    partialUpdateAlias: "crm_partner_branches_partial_update",
    filterAlias: "crm_partner_branches_filter_options_retrieve",
    hardDeleteAlias: "crm_partner_branches_destroy",
    fields: ["partner_name", "branch_name", "is_active"],
    detailsField: [
      "partner",
      "partner_name",
      "branch",
      "branch_name",
      "special_discount",
      "is_active",
    ],
  },
  "crm-partner-price-list-items": {
    schemaName: "PartnerPriceListItemRequest",
    listAlias: "crm_partner_price_list_items_list",
    createAlias: "crm_partner_price_list_items_create",
    retrieveAlias: "crm_partner_price_list_items_retrieve",
    partialUpdateAlias: "crm_partner_price_list_items_partial_update",
    updateAlias: "crm_partner_price_list_items_update",
    filterAlias: "crm_partner_price_list_items_filter_options_retrieve",
    hardDeleteAlias: "crm_partner_price_list_items_destroy",
    fields: ["product_name", "special_price", "special_discount"],
    detailsField: [
      "price_list",
      "product",
      "product_name",
      "variant",
      "variant_sku",
      "category",
      "category_name",
      "special_price",
      "special_discount",
    ],
  },
  "crm-partner-price-lists": {
    schemaName: "PartnerPriceListRequest",
    listAlias: "crm_partner_price_lists_list",
    createAlias: "crm_partner_price_lists_create",
    retrieveAlias: "crm_partner_price_lists_retrieve",
    updateAlias: "crm_partner_price_lists_update",
    partialUpdateAlias: "crm_partner_price_lists_partial_update",
    filterAlias: "crm_partner_price_lists_filter_options_retrieve",
    hardDeleteAlias: "crm_partner_price_lists_destroy",
    fields: ["name", "partner_name", "price_type", "is_active"],
    detailsField: [
      "partner",
      "partner_name",
      "name",
      "description",
      "price_type",
      "adjustment_value",
      "valid_from",
      "valid_until",
      "applies_to_all",
      "items_count",
      "is_active",
    ],
  },
  "crm-partner-settlements": {
    schemaName: "PartnerSettlementRequest",
    listAlias: "crm_partner_settlements_list",
    createAlias: "crm_partner_settlements_create",
    retrieveAlias: "crm_partner_settlements_retrieve",
    updateAlias: "crm_partner_settlements_update",
    partialUpdateAlias: "crm_partner_settlements_partial_update",
    filterAlias: "crm_partner_settlements_filter_options_retrieve",
    hardDeleteAlias: "crm_partner_settlements_destroy",
    fields: [
      "settlement_number",
      "partner_name",
      "period_start",
      "period_end",
      "total_amount",
      "status_display",
    ],
    detailsField: [
      "settlement_number",
      "partner",
      "partner_name",
      "settlement_date",
      "period_start",
      "period_end",
      "total_claims",
      "total_amount",
      "adjustments",
      "net_amount",
      "status",
      "status_display",
      "payment_date",
      "payment_reference",
      "notes",
    ],
  },
  "crm-partners": {
    schemaName: "PartnerRequest",
    listAlias: "crm_partners_list",
    createAlias: "crm_partners_create",
    retrieveAlias: "crm_partners_retrieve",
    updateAlias: "crm_partners_update",
    partialUpdateAlias: "crm_partners_partial_update",
    filterAlias: "crm_partners_filter_options_retrieve",
    hardDeleteAlias: "crm_partners_destroy",
    fields: [
      "code",
      "name",
      "partner_type_display",
      "phone",
      "current_balance",
      "is_active",
    ],
    detailsField: [
      "code",
      "name",
      "name_en",
      "partner_type",
      "partner_type_display",
      "logo",
      "contact_person",
      "phone",
      "email",
      "website",
      "address",
      "contract_number",
      "contract_start",
      "contract_end",
      "is_contract_active",
      "payment_terms",
      "default_discount",
      "credit_limit",
      "current_balance",
      "available_credit",
      "patient_share_percentage",
      "tax_number",
      "notes",
      "is_active",
    ],
  },


  "products-flexible-prices": {
    schemaName: "FlexiblePriceRequest",
    listAlias: "products_flexible_prices_list",
    createAlias: "products_flexible_prices_create",
    retrieveAlias: "products_flexible_prices_retrieve",
    updateAlias: "products_flexible_prices_update",
    partialUpdateAlias: "products_flexible_prices_partial_update",
    hardDeleteAlias: "products_flexible_prices_destroy",
    fields: [
      "variant",
      "special_price",
      "discount_percentage",
      "min_quantity",
      "start_date",
      "end_date",
    ],
    detailsField: [
      "variant",
      "customer",
      "customer_group",
      "branch",
      "pricing_tier",
      "partner",
      "special_price",
      "discount_percentage",
      "start_date",
      "end_date",
      "min_quantity",
      "max_quantity",
      "currency",
      "priority",
      "active",
      "pricing_policy",
      "notes",
    ],
  },
  "crm-subscriptions": {
    schemaName: "SubscriptionRequest",
    listAlias: "crm_subscriptions_list",
    createAlias: "crm_subscriptions_create",
    retrieveAlias: "crm_subscriptions_retrieve",
    partialUpdateAlias: "crm_subscriptions_partial_update",
    hardDeleteAlias: "crm_subscriptions_destroy",
    filterAlias: "crm_subscriptions_filter_options_retrieve",
    fields: ["name", "description"],
    detailsField: ["name", "description", "is_active"],
  },
  "crm-tasks": {
    schemaName: "TaskRequest",
    listAlias: "crm_tasks_list",
    createAlias: "crm_tasks_create",
    retrieveAlias: "crm_tasks_retrieve",
    partialUpdateAlias: "crm_tasks_partial_update",
    hardDeleteAlias: "crm_tasks_destroy",
    filterAlias: "crm_tasks_filter_options_retrieve",
    fields: ["customer_name", "description"],
    detailsField: [
      "customer_name",
      "description",
      "title",
      "opportunity",
      "priority",
      "completed",
      "due_date",
      "is_active",
    ],
  },
  "crm_customer_partner_links_by_customer": {
    createAlias: "crm_customer_partner_links_by_customer_list",
  },
  "crm_customer_partner_links_deactivate": {
    createAlias: "crm_customer_partner_links_deactivate_create",
  },
  "crm_insurance_claims_approve": {
    createAlias: "crm_insurance_claims_approve_create",
  },
  "crm_insurance_claims_approved_unpaid": {
    createAlias: "crm_insurance_claims_approved_unpaid_list",
  },
  "crm_insurance_claims_choices": {
    createAlias: "crm_insurance_claims_choices_retrieve",
  },
  "crm_insurance_claims_mark_paid": {
    createAlias: "crm_insurance_claims_mark_paid_create"
  },
  "crm_insurance_claims_pending": {
    createAlias: "crm_insurance_claims_pending_list",
  },
  "crm_insurance_claims_reject": {
    createAlias: "crm_insurance_claims_reject_create"
  },
  "crm_insurance_claims_submit": {
    createAlias: "crm_insurance_claims_submit_create",
  },
  "crm_partner_settlements_calculate": {
    createAlias: "crm_partner_settlements_calculate_create",
  },
  "crm_partner_settlements_confirm": {
    createAlias: "crm_partner_settlements_confirm_create",
  },
  "crm_partner_settlements_mark_paid": {
    createAlias: "crm_partner_settlements_mark_paid_create",
  },
  "crm_partners_bnpl_providers": {
    listAlias: "crm_partners_bnpl_providers_list",
  },
  "crm_partners_by_type": {
    createAlias: "crm_partners_by_type_list",
  },
  "crm_partners_choices": {
    createAlias: "crm_partners_choices_retrieve",
  },
  "crm_partners_claims_summary": {
    createAlias: "crm_partners_claims_summary_retrieve",
  },
  "crm_partners_customers": {
    createAlias: "crm_partners_customers_list",
  },
  "crm_partners_insurance_companies": {
    createAlias: "crm_partners_insurance_companies_list",
  },

  // HRM APP
  "hrm-attendance": {
    schemaName: "AttendanceRequest",
    listAlias: "hrm_attendances_list",
    createAlias: "hrm_attendances_create",
    retrieveAlias: "hrm_attendances_retrieve",
    partialUpdateAlias: "hrm_attendances_partial_update",
    hardDeleteAlias: "hrm_attendances_destroy",
    filterAlias: "hrm_attendances_filter_options_retrieve",
    fields: ["employee_name", "date"],
    detailsField: [
      "employee_name",
      "date",
      "hours_worked",
      "check_in",
      "check_out",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "hrm-departments": {
    schemaName: "DepartmentRequest",
    listAlias: "hrm_departments_list",
    createAlias: "hrm_departments_create",
    retrieveAlias: "hrm_departments_retrieve",
    partialUpdateAlias: "hrm_departments_partial_update",
    hardDeleteAlias: "hrm_departments_destroy",
    filterAlias: "hrm_departments_filter_options_retrieve",
    fields: ["name", "description"],
    detailsField: ["name", "description", "is_active", "location"],
  },
  "hrm-employee-leave": {
    schemaName: "LeaveRequest",
    listAlias: "hrm_leaves_list",
    createAlias: "hrm_leaves_create",
    retrieveAlias: "hrm_leaves_retrieve",
    partialUpdateAlias: "hrm_leaves_partial_update",
    hardDeleteAlias: "hrm_leaves_destroy",
    filterAlias: "hrm_leaves_filter_options_retrieve",
    fields: ["user_name", "department_name", "email", "phone"],
    detailsField: [
      "user_name",
      "hire_date",
      "salary",
      "position",
      "department_name",
      "email",
      "phone",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "hrm-employees": {
    schemaName: "EmployeeRequest",
    listAlias: "hrm_employees_list",
    createAlias: "hrm_employees_create",
    retrieveAlias: "hrm_employees_retrieve",
    partialUpdateAlias: "hrm_employees_partial_update",
    hardDeleteAlias: "hrm_employees_destroy",
    filterAlias: "hrm_employees_filter_options_retrieve",
    fields: ["user_name", "department_name", "email", "phone"],
    detailsField: [
      "user_name",
      "hire_date",
      "salary",
      "position",
      "department_name",
      "email",
      "phone",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "hrm-notifications": {
    schemaName: "NotificationRequest",
    listAlias: "hrm_notifications_list",
    createAlias: "hrm_notifications_create",
    retrieveAlias: "hrm_notifications_retrieve",
    partialUpdateAlias: "hrm_notifications_partial_update",
    hardDeleteAlias: "hrm_notifications_destroy",
    filterAlias: "hrm_notifications_filter_options_retrieve",
    fields: ["employee_name", "notification_type", "is_active"],
    detailsField: [
      "employee_name",
      "notification_type",
      "message",
      "is_read",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "hrm-payroll": {
    schemaName: "PayrollRequest",
    listAlias: "hrm_payrolls_list",
    createAlias: "hrm_payrolls_create",
    retrieveAlias: "hrm_payrolls_retrieve",
    partialUpdateAlias: "hrm_payrolls_partial_update",
    hardDeleteAlias: "hrm_payrolls_destroy",
    filterAlias: "hrm_payrolls_filter_options_retrieve",
    fields: ["employee_name", "month"],
    detailsField: [
      "employee_name",
      "basic_salary",
      "bonuses",
      "deductions",
      "net_salary",
      "month",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "hrm-performance-review": {
    schemaName: "PerformanceReviewRequest",
    listAlias: "hrm_performance_reviews_list",
    createAlias: "hrm_performance_reviews_create",
    retrieveAlias: "hrm_performance_reviews_retrieve",
    partialUpdateAlias: "hrm_performance_reviews_partial_update",
    hardDeleteAlias: "hrm_performance_reviews_destroy",
    filterAlias: "hrm_performance_reviews_filter_options_retrieve",
    fields: ["employee_name", "month"],
    detailsField: [
      "employee_name",
      "review_date",
      "rating",
      "comments",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "hrm-tasks": {
    schemaName: "TaskRequest",
    listAlias: "hrm_tasks_list",
    createAlias: "hrm_tasks_create",
    retrieveAlias: "hrm_tasks_retrieve",
    partialUpdateAlias: "hrm_tasks_partial_update",
    hardDeleteAlias: "hrm_tasks_destroy",
    filterAlias: "hrm_tasks_filter_options_retrieve",
    fields: ["employee_name", "month"],
    detailsField: [
      "employee_name",
      "review_date",
      "rating",
      "comments",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "hrm_employee_form_options": {
    retrieveAlias: "hrm_employee_form_options_retrieve",
  },

  // PRODUCTS / INVENTORY APP
  "attribute-values": {
    schemaName: "AttributeValueRequest",
    listAlias: "products_attribute_values_list",
    createAlias: "products_attribute_values_create",
    retrieveAlias: "products_attribute_values_retrieve",
    partialUpdateAlias: "products_attribute_values_partial_update",
    hardDeleteAlias: "products_attribute_values_destroy",
    filterAlias: "products_attribute_values_filter_options_retrieve",
    fields: ["attribute", "value", "attribute_name", "label"],
    detailsField: ["attribute_id", "value", "attribute_name", "is_active"],
  },
  attributes: {
    schemaName: "AttributeRequest",
    listAlias: "products_attributes_list",
    createAlias: "products_attributes_create",
    retrieveAlias: "products_attributes_retrieve",
    partialUpdateAlias: "products_attributes_partial_update",
    hardDeleteAlias: "products_attributes_destroy",
    filterAlias: "products_attributes_filter_options_retrieve",
    fields: ["name", "is_active"],
    detailsField: ["name", "description", "is_active"],
  },
  brands: {
    schemaName: "BrandRequest",
    listAlias: "products_brands_list",
    createAlias: "products_brands_create",
    retrieveAlias: "products_brands_retrieve",
    partialUpdateAlias: "products_brands_partial_update",
    hardDeleteAlias: "products_brands_destroy",
    filterAlias: "products_brands_filter_options_retrieve",
    fields: ["name", "email", "phone"],
    detailsField: [
      "name",
      "country",
      "website",
      "description",
      "logo",
      "is_active",
      "product_type",
    ],
  },
  categories: {
    schemaName: "CategoryRequest",
    listAlias: "products_categories_list",
    createAlias: "products_categories_create",
    retrieveAlias: "products_categories_retrieve",
    partialUpdateAlias: "products_categories_partial_update",
    hardDeleteAlias: "products_categories_destroy",
    filterAlias: "products_categories_filter_options_retrieve",
    fields: ["name", "description", "parent_name"],
    detailsField: [
      "name",
      "description",
      "parent_id",
      "parent_name",
      "is_active",
    ],
  },
  manufacturers: {
    schemaName: "ManufacturerRequest",
    listAlias: "products_manufacturers_list",
    createAlias: "products_manufacturers_create",
    retrieveAlias: "products_manufacturers_retrieve",
    partialUpdateAlias: "products_manufacturers_partial_update",
    hardDeleteAlias: "products_manufacturers_destroy",
    filterAlias: "products_manufacturers_filter_options_retrieve",
    fields: ["name", "email", "phone"],
    detailsField: ["name", "email", "phone", "country", "website", "is_active"],
  },
  "pricing-policies": {
    schemaName: "PricingPolicyRequest",
    listAlias: "products_pricing_policies_list",
    createAlias: "products_pricing_policies_create",
    retrieveAlias: "products_pricing_policies_retrieve",
    partialUpdateAlias: "products_pricing_policies_partial_update",
    hardDeleteAlias: "products_pricing_policies_destroy",
    filterAlias: "products_pricing_policies_filter_options_retrieve",
    fields: ["name", "is_active", "description"],
    detailsField: ["name", "is_active", "description"],
  },
  product: {
    schemaName: "ProductRequest",
    listAlias: "products_products_list",
    createAlias: "products_products_create",
    retrieveAlias: "products_products_retrieve",
    partialUpdateAlias: "products_products_partial_update",
    hardDeleteAlias: "products_products_destroy",
    filterAlias: "products_products_filter_options_retrieve",
    fields: ["name", "category_name", "brand_name"],
    detailsField: [
      "name",
      "description",
      "category_name",
      "category_id",
      "brand_name",
      "brand_id",
      "manufacturer_name",
      "manufacturer_id",
      "supplier_name",
      "supplier_id",
      "model",
      "main_group",
      "is_active",
    ],
  },
  "product-answers": {
    schemaName: "ProductVariantAnswerRequest",
    listAlias: "products_answers_list",
    createAlias: "products_answers_create",
    retrieveAlias: "products_answers_retrieve",
    updateAlias: "products_answers_update",
    hardDeleteAlias: "products_answers_destroy",
    partialUpdateAlias: "products_answers_partial_update",
    filterAlias: "products_answers_filter_options_retrieve",
    fields: ["question_id", "answer", "answered_by"],
    detailsField: [
      "question_id",
      "answer",
      "answered_by",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "product-images": {
    schemaName: "ProductImageRequest",
    listAlias: "products_product_images_list",
    createAlias: "products_product_images_create",
    retrieveAlias: "products_product_images_retrieve",
    partialUpdateAlias: "products_product_images_partial_update",
    hardDeleteAlias: "products_product_images_destroy",
    filterAlias: "products_product_images_filter_options_retrieve",
    fields: ["name", "category_name", "brand_name"],
    detailsField: [
      "name",
      "description",
      "category_name",
      "category_id",
      "brand_name",
      "brand_id",
      "manufacturer_name",
      "manufacturer_id",
      "supplier_name",
      "supplier_id",
      "model",
      "type",
      "is_active",
    ],
  },
  "product-marketing": {
    schemaName: "ProductVariantMarketingRequest",
    listAlias: "products_marketing_list",
    createAlias: "products_marketing_create",
    retrieveAlias: "products_marketing_retrieve",
    updateAlias: "products_marketing_update",
    hardDeleteAlias: "products_marketing_destroy",
    partialUpdateAlias: "products_marketing_partial_update",
    filterAlias: "products_marketing_filter_options_retrieve",
    fields: ["variant_name", "title", "slug", "gender"],
    detailsField: [
      "variant",
      "variant_name",
      "title",
      "description",
      "meta_title",
      "meta_description",
      "meta_keywords",
      "slug",
      "seo_image",
      "seo_image_alt",
      "gender",
      "age_group",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "product-offers": {
    schemaName: "ProductVariantOfferRequest",
    listAlias: "products_offers_list",
    createAlias: "products_offers_create",
    retrieveAlias: "products_offers_retrieve",
    updateAlias: "products_offers_update",
    hardDeleteAlias: "products_offers_destroy",
    partialUpdateAlias: "products_offers_partial_update",
    filterAlias: "products_offers_filter_options_retrieve",
    fields: ["ProductVariant_id", "offer", "start_date", "end_date"],
    detailsField: [
      "ProductVariant_id",
      "offer",
      "start_date",
      "end_date",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "product-questions": {
    schemaName: "ProductVariantQuestionRequest",
    listAlias: "products_questions_list",
    createAlias: "products_questions_create",
    retrieveAlias: "products_questions_retrieve",
    updateAlias: "products_questions_update",
    hardDeleteAlias: "products_questions_destroy",
    partialUpdateAlias: "products_questions_partial_update",
    filterAlias: "products_questions_filter_options_retrieve",
    fields: ["ProductVariant_id", "question", "asked_by"],
    detailsField: [
      "ProductVariant_id",
      "question",
      "asked_by",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "product-reviews": {
    schemaName: "ProductVariantReviewRequest",
    listAlias: "products_reviews_list",
    createAlias: "products_reviews_create",
    retrieveAlias: "products_reviews_retrieve",
    updateAlias: "products_reviews_update",
    filterAlias: "products_reviews_filter_options_retrieve",
    hardDeleteAlias: "products_reviews_destroy",
    partialUpdateAlias: "products_reviews_partial_update",
    fields: ["ProductVariant_id", "rating", "review", "reviewed_by"],
    detailsField: [
      "ProductVariant_id",
      "rating",
      "review",
      "reviewed_by",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "product-stock-transfer-items": {
    schemaName: "StockTransferItemRequest",
    listAlias: "products_stock_transfer_items_list",
    createAlias: "products_stock_transfer_items_create",
    retrieveAlias: "products_stock_transfer_items_retrieve",
    updateAlias: "products_stock_transfer_items_update",
    hardDeleteAlias: "products_stock_transfer_items_destroy",
    partialUpdateAlias: "products_stock_transfer_items_partial_update",
    filterAlias: "products_stock_transfer_items_filter_options_retrieve",
    fields: [
      "transfer",
      "variant_name",
      "quantity_requested",
      "quantity_sent",
      "quantity_received",
    ],
    detailsField: [
      "transfer",
      "variant",
      "variant_name",
      "variant_sku",
      "product_name",
      "quantity_requested",
      "quantity_sent",
      "quantity_received",
      "unit_cost",
      "created_at",
      "updated_at",
    ],
  },
  "product-stock-transfers": {
    schemaName: "StockTransferRequest",
    listAlias: "products_stock_transfers_list",
    createAlias: "products_stock_transfers_create",
    retrieveAlias: "products_stock_transfers_retrieve",
    updateAlias: "products_stock_transfers_update",
    hardDeleteAlias: "products_stock_transfers_destroy",
    partialUpdateAlias: "products_stock_transfers_partial_update",
    filterAlias: "products_stock_transfers_filter_options_retrieve",
    fields: [
      "transfer_number",
      "from_branch_name",
      "to_branch_name",
      "status",
    ],
    detailsField: [
      "transfer_number",
      "from_branch",
      "from_branch_name",
      "to_branch",
      "to_branch_name",
      "status",
      "status_display",
      "notes",
      "items_count",
      "approved_date",
      "shipped_date",
      "received_date",
      "requested_by",
      "created_at",
      "updated_at",
    ],
  },
  "product-supplier": {
    schemaName: "ProductSupplierRequest",
    listAlias: "products_product_suppliers_list",
    createAlias: "products_product_suppliers_create",
    retrieveAlias: "products_product_suppliers_retrieve",
    partialUpdateAlias: "products_product_suppliers_partial_update",
    hardDeleteAlias: "products_product_suppliers_destroy",
    filterAlias: "products_product_suppliers_filter_options_retrieve",
    fields: ["name", "category_name", "brand_name"],
    detailsField: [
      "name",
      "description",
      "category_name",
      "category_id",
      "brand_name",
      "brand_id",
      "manufacturer_name",
      "manufacturer_id",
      "supplier_name",
      "supplier_id",
      "model",
      "type",
      "is_active",
    ],
  },
  "product-variants": {
    schemaName: "ProductVariantRequest",
    listAlias: "products_variants_list",
    createAlias: "products_variants_create",
    retrieveAlias: "products_variants_retrieve",
    partialUpdateAlias: "products_variants_partial_update",
    hardDeleteAlias: "products_variants_destroy",
    filterAlias: "products_variants_filter_options_retrieve",
    fields: ["name", "category_name", "brand_name"],
    detailsField: [
      "name",
      "description",
      "category_name",
      "category_id",
      "brand_name",
      "brand_id",
      "manufacturer_name",
      "manufacturer_id",
      "supplier_name",
      "supplier_id",
      "model",
      "type",
      "is_active",
    ],
  },
  "products-import-csv": {
    createAlias: "products_products_import_csv_create",
  },
  "products-stocks-low-stock": {
    listAlias: "products_stocks_low_stock_list",
  },
  "products_branches_active": {
    listAlias: "products_branches_active_list",
  },
  "products_branches_low_stock": {
    listAlias: "products_branches_low_stock_list",
  },
  "products_branches_main": {
    retrieveAlias: "products_branches_main_retrieve",
  },
  "products_orders_fulfillment_check": {
    createAlias: "products_orders_fulfillment_check_create",
  },
  "products_products_import_csv": {
    createAlias: "products_products_import_csv_create",
  },
  "products_stock_movements_adjustment": {
    createAlias: "products_stock_movements_adjustment_create",
  },
  "products_stock_movements_by_stock": {
    listAlias: "products_stock_movements_by_stock_list",
  },
  "products_stock_movements_purchase": {
    createAlias: "products_stock_movements_purchase_create",
  },
  "products_stock_transfers_approve": {
    createAlias: "products_stock_transfers_approve_create",
  },
  "products_stock_transfers_cancel": {
    createAlias: "products_stock_transfers_cancel_create",
  },
  "products_stock_transfers_incoming": {
    listAlias: "products_stock_transfers_incoming_list",
  },
  "products_stock_transfers_outgoing": {
    listAlias: "products_stock_transfers_outgoing_list",
  },
  "products_stock_transfers_pending": {
    listAlias: "products_stock_transfers_pending_list",
  },
  "products_stock_transfers_receive": {
    createAlias: "products_stock_transfers_receive_create",
  },
  "products_stock_transfers_ship": {
    createAlias: "products_stock_transfers_ship_create",
  },
  "products_stock_transfers_submit": {
    createAlias: "products_stock_transfers_submit_create",
  },
  "products_stocks_by_branch": {
    createAlias: "products_stocks_by_branch_list",
  },
  "products_stocks_out_of_stock": {
    createAlias: "products_stocks_out_of_stock_list",
  },
  "products_stocks_stores_only": {
    createAlias: "products_stocks_stores_only_list",
  },
  "products_variants_nearest_branch": {
    retrieveAlias: "products_variants_nearest_branch_retrieve",
  },
  "products_variants_stock_summary": {
    retrieveAlias: "products_variants_stock_summary_retrieve",
  },
  "products_variants_total_stock": {
    retrieveAlias: "products_variants_total_stock_retrieve",
  },
  "purchase-orders": {
    schemaName: "PurchaseOrderCreateRequest",
    listAlias: "products_purchase_orders_list",
    createAlias: "products_purchase_orders_create",
    retrieveAlias: "products_purchase_orders_retrieve",
    partialUpdateAlias: "products_purchase_orders_partial_update",
    hardDeleteAlias: "products_purchase_orders_destroy",
    filterAlias: "products_purchase_orders_filter_options_retrieve",
    fields: ["order_number", "supplier_name", "branch_name", "status", "total_amount"],
    detailsField: [
      "order_number",
      "supplier",
      "supplier_name",
      "branch",
      "branch_name",
      "status",
      "status_display",
      "order_date",
      "expected_date",
      "received_date",
      "subtotal",
      "tax_amount",
      "total_amount",
      "notes",
      "created_by_name",
      "approved_by_name",
      "items_count",
      "created_at",
    ],
  },
  "stock-movements": {
    schemaName: "StockMovementRequest",
    listAlias: "products_stock_movements_list",
    createAlias: "products_stock_movements_create",
    retrieveAlias: "products_stock_movements_retrieve",
    partialUpdateAlias: "products_stock_movements_partial_update",
    hardDeleteAlias: "products_stock_movements_destroy",
    filterAlias: "products_stock_movements_filter_options_retrieve",
    fields: ["product_name", "movement_type", "quantity", "date"],
    detailsField: [
      "product_name",
      "movement_type",
      "quantity",
      "date",
      "reference",
      "description",
    ],
  },
  stocks: {
    schemaName: "StockRequest",
    listAlias: "products_stocks_list",
    createAlias: "products_stocks_create",
    retrieveAlias: "products_stocks_retrieve",
    partialUpdateAlias: "products_stocks_partial_update",
    hardDeleteAlias: "products_stocks_destroy",
    filterAlias: "products_stocks_filter_options_retrieve",
    fields: ["product_name", "warehouse", "quantity_on_hand"],
    detailsField: [
      "product_name",
      "warehouse",
      "quantity_on_hand",
      "quantity_reserved",
      "reorder_level",
    ],
  },
  suppliers: {
    schemaName: "SupplierRequest",
    listAlias: "products_suppliers_list",
    createAlias: "products_suppliers_create",
    retrieveAlias: "products_suppliers_retrieve",
    partialUpdateAlias: "products_suppliers_partial_update",
    hardDeleteAlias: "products_suppliers_destroy",
    filterAlias: "products_suppliers_filter_options_retrieve",
    fields: ["name", "email", "phone"],
    detailsField: [
      "name",
      "contact_person",
      "email",
      "phone",
      "address",
      "country",
      "website",
      "payment_terms",
    ],
  },
  "flexible-prices": {
    schemaName: "FlexiblePriceRequest",
    listAlias: "products_flexible_prices_list",
    createAlias: "products_flexible_prices_create",
    retrieveAlias: "products_flexible_prices_retrieve",
    partialUpdateAlias: "products_flexible_prices_partial_update",
    hardDeleteAlias: "products_flexible_prices_destroy",
    filterAlias: "products_flexible_prices_filter_options_retrieve",
    fields: ["variant", "special_price", "partner"],
    detailsField: [
      "variant",
      "special_price",
      "partner",
      "customer",
      "pricing_tier",
      "start_date",
      "end_date",
    ],
  },

  // SALES APP
  "invoice-types": {
    schemaName: "InvoiceTypeRequest",
    listAlias: "sales_invoice_types_list",
    createAlias: "sales_invoice_types_create",
    retrieveAlias: "sales_invoice_types_retrieve",
    partialUpdateAlias: "sales_invoice_types_partial_update",
    hardDeleteAlias: "sales_invoice_types_destroy",
    filterAlias: "sales_invoice_types_filter_options_retrieve",
    fields: ["name", "code", "is_active", "pricing_policy"],
    detailsField: ["name", "code", "is_active", "pricing_policy", "revenue_account"],
  },
  invoices: {
    schemaName: "InvoiceRequest",
    listAlias: "sales_invoices_list",
    createAlias: "sales_invoices_create",
    retrieveAlias: "sales_invoices_retrieve",
    partialUpdateAlias: "sales_invoices_partial_update",
    hardDeleteAlias: "sales_invoices_destroy",
    filterAlias: "sales_invoices_filter_options_retrieve",
    fields: [
      "invoice_number",
      "customer_name",
      "total_amount",
      "status",
      "due_date",
    ],
    detailsField: [
      "invoice_number",
      "customer_name",
      "total_amount",
      "status",
      "issue_date",
      "due_date",
      "is_paid",
    ],
  },
  orders: {
    schemaName: "OrderRequest",
    listAlias: "sales_orders_list",
    createAlias: "sales_orders_create",
    retrieveAlias: "sales_orders_retrieve",
    partialUpdateAlias: "sales_orders_partial_update",
    hardDeleteAlias: "sales_orders_destroy",
    filterAlias: "sales_orders_filter_options_retrieve",
    fields: ["order_number", "customer_name", "total_amount", "status", "payment_method"],
    detailsField: [
      "order_number",
      "customer_name",
      "total_amount",
      "status",
      "payment_status",
      "payment_method",
      "order_date",
      "delivery_date",
    ],
  },
  "payment-methods": {
    schemaName: "PaymentMethodRequest",
    listAlias: "sales_payment_methods_list",
    createAlias: "sales_payment_methods_create",
    retrieveAlias: "sales_payment_methods_retrieve",
    partialUpdateAlias: "sales_payment_methods_partial_update",
    hardDeleteAlias: "sales_payment_methods_destroy",
    filterAlias: "sales_payment_methods_filter_options_retrieve",
    fields: ["name_ar", "name_en", "code", "is_active"],
    detailsField: [
      "name_ar",
      "name_en",
      "code",
      "is_active",
      "is_installment",
      "provider_fees_percent",
    ],
  },
  payments: {
    schemaName: "PaymentRequest",
    listAlias: "sales_payments_list",
    createAlias: "sales_payments_create",
    retrieveAlias: "sales_payments_retrieve",
    partialUpdateAlias: "sales_payments_partial_update",
    hardDeleteAlias: "sales_payments_destroy",
    filterAlias: "sales_payments_filter_options_retrieve",
    fields: [
      "payment_number",
      "invoice_number",
      "amount",
      "payment_method_display",
      "status",
      "transaction_id",
      "paid_at"
    ],
    detailsField: [
      "payment_number",
      "invoice_number",
      "amount",
      "currency",
      "payment_method_display",
      "status",
      "transaction_id",
      "paid_at",
      "notes",
      "created_by"
    ],
  },
  "sales-payments": {
    // Alias to avoid conflict with tenant payments
    schemaName: "PaymentRequest",
    listAlias: "sales_payments_list",
    createAlias: "sales_payments_create",
    retrieveAlias: "sales_payments_retrieve",
    partialUpdateAlias: "sales_payments_partial_update",
    hardDeleteAlias: "sales_payments_destroy",
    filterAlias: "sales_payments_filter_options_retrieve",
    fields: ["payment_number", "invoice_number", "amount", "payment_method", "payment_date"],
    detailsField: [
      "payment_number",
      "invoice_number",
      "amount",
      "payment_method",
      "payment_date",
      "reference_number",
    ],
  },
  "sales_installments": {
    schemaName: "InstallmentRequest",
    listAlias: "sales_installments_list",
    createAlias: "sales_installments_create",
    retrieveAlias: "sales_installments_retrieve",
    updateAlias: "sales_installments_update",
    partialUpdateAlias: "sales_installments_partial_update",
    hardDeleteAlias: "sales_installments_destroy",
    filterAlias: "sales_installments_filter_options_retrieve",
    fields: ["installment_number", "amount", "due_date", "status"],
    detailsField: [
      "installment_number",
      "amount",
      "due_date",
      "status",
      "paid_at",
      "paid_amount",
      "payment",
    ],
  },
  "sales_installments_mark_paid": {
    "createAlias": "sales_installments_mark_paid_create"
  },
  "sales_installments_overdue": {
    createAlias: "sales_installments_overdue_list",
  },
  "sales_inventory_damage": {
    createAlias: "sales_inventory_damage_create",
  },
  "sales_invoices_by_order": {
    listAlias: "sales_invoices_by_order_list",
  },
  "sales_invoices_calculate_totals": {
    createAlias: "sales_invoices_calculate_totals_create",
  },
  "sales_invoices_choices": {
    retrieveAlias: "sales_invoices_choices_retrieve",
  },
  "sales_invoices_confirm": {
    createAlias: "sales_invoices_confirm_create",
  },
  "sales_orders_bulk_update_status": {
    createAlias: "sales_orders_bulk_update_status_create",
  },
  "sales_orders_calculate_totals": {
    createAlias: "sales_orders_calculate_totals_create",
  },
  "sales_orders_cancel": {
    createAlias: "sales_orders_cancel_create",
  },
  "sales_orders_choices": {
    retrieveAlias: "sales_orders_choices_retrieve",
  },
  "sales_orders_confirm": {
    createAlias: "sales_orders_confirm_create",
  },
  "sales_orders_deliver": {
    createAlias: "sales_orders_deliver_create",
  },
  "sales_orders_ready": {
    createAlias: "sales_orders_ready_create",
  },
  "sales_orders_return": {
    createAlias: "sales_orders_return_create",
  },
  "sales_payment_methods": {
    updateAlias: "sales_payment_methods_update",
  },
  "sales_payments": {
    updateAlias: "sales_payments_update",
  },
  "sales_payments_bnpl_callback": {
    createAlias: "sales_payments_bnpl_callback_create",
  },
  "sales_payments_choices": {
    retrieveAlias: "sales_payments_choices_retrieve",
  },
  "sales_payments_create_bnpl_session": {
    createAlias: "sales_payments_create_bnpl_session_create",
  },
  "sales_payments_mark_completed": {
    createAlias: "sales_payments_mark_completed_create",
  },
  "sales_payments_mark_failed": {
    createAlias: "sales_payments_mark_failed_create"
  },
  "sales_payments_refund": {
    createAlias: "sales_payments_refund_create",
  },
  "sales_payments_summary": {
    retrieveAlias: "sales_payments_summary_retrieve",
  },
  "sales_reports_branch_comparison": {
    listAlias: "sales_reports_branch_comparison_list",
  },
  "sales_reports_financial_dashboard": {
    retrieveAlias: "sales_reports_financial_dashboard_retrieve",
  },
  "sales_reports_inventory_summary": {
    retrieveAlias: "sales_reports_inventory_summary_retrieve",
  },
  "sales_reports_pending_orders": {
    retrieveAlias: "sales_reports_pending_orders_retrieve",
  },
  "sales_reports_receivables_aging": {
    retrieveAlias: "sales_reports_receivables_aging_retrieve",
  },
  "sales_reports_sales_by_date": {
    listAlias: "sales_reports_sales_by_date_list",
  },
  "sales_reports_sales_summary": {
    retrieveAlias: "sales_reports_sales_summary_retrieve",
  },
  "sales_reports_stock_movements": {
    retrieveAlias: "sales_reports_stock_movements_retrieve",
  },
  "sales_reports_top_products": {
    listAlias: "sales_reports_top_products_list",
  },
  "sales_wholesale_create_order": {
    createAlias: "sales_wholesale_create_order_create",
  },
  "sales_wholesale_customer_credit": {
    createAlias: "sales_wholesale_customer_credit_create",
  },
  "sales_wholesale_customer_statement": {
    retrieveAlias: "sales_wholesale_customer_statement_retrieve",
  },
  "sales_wholesale_customers": {
    listAlias: "sales_wholesale_customers_list",
  },
  "sales_wholesale_dashboard": {
    retrieveAlias: "sales_wholesale_dashboard_retrieve",
  },
  "sales_wholesale_pricing": {
    createAlias: "sales_wholesale_pricing_create",
  },
  "sales_wholesale_validate": {
    createAlias: "sales_wholesale_validate_create",
  },

  // ACCOUNTING APP
  "accounting-categories": {
    schemaName: "AccountingCategoryRequest",
    listAlias: "accounting_categories_list",
    createAlias: "accounting_categories_create",
    retrieveAlias: "accounting_categories_retrieve",
    partialUpdateAlias: "accounting_categories_partial_update",
    hardDeleteAlias: "accounting_categories_destroy",
    filterAlias: "accounting_categories_filter_options_retrieve",
    fields: ["name", "category_type", "parent"],
    detailsField: [
      "name",
      "category_type",
      "parent",
      "description",
      "is_active",
    ],
  },
  "accounting-taxes": {
    schemaName: "TaxRequest",
    listAlias: "accounting_taxes_list",
    createAlias: "accounting_taxes_create",
    retrieveAlias: "accounting_taxes_retrieve",
    partialUpdateAlias: "accounting_taxes_partial_update",
    hardDeleteAlias: "accounting_taxes_destroy",
    filterAlias: "accounting_taxes_filter_options_retrieve",
    fields: ["name", "rate", "effective_date", "is_active"],
    detailsField: [
      "name",
      "rate",
      "effective_date",
      "description",
      "is_active",
    ],
  },
  "accounting_chart_of_accounts": {
    createAlias: "accounting_chart_of_accounts_update",
  },
  "accounting_chart_of_accounts_by_type": {
    createAlias: "accounting_chart_of_accounts_by_type_list",
  },
  "accounting_chart_of_accounts_choices": {
    createAlias: "accounting_chart_of_accounts_choices_retrieve",
  },
  "accounting_chart_of_accounts_setup_defaults": {
    createAlias: "accounting_chart_of_accounts_setup_defaults_create",
  },
  "accounting_chart_of_accounts_tree": {
    createAlias: "accounting_chart_of_accounts_tree_list",
  },
  "accounting_financial_periods_current": {
    createAlias: "accounting_financial_periods_current_retrieve",
  },
  "accounting_journal_entries": {
    createAlias: "accounting_journal_entries_update",
  },
  "accounting_journal_entries_by_source": {
    createAlias: "accounting_journal_entries_by_source_list",
  },
  "accounting_journal_entries_choices": {
    createAlias: "accounting_journal_entries_choices_retrieve",
  },
  "accounting_journal_entries_post_entry": {
    createAlias: "accounting_journal_entries_post_entry_create",
  },
  "accounting_journal_entries_reverse_entry": {
    createAlias: "accounting_journal_entries_reverse_entry_create",
  },
  "accounting_journal_entries_unposted": {
    createAlias: "accounting_journal_entries_unposted_list",
  },
  "accounting_reports_balance_sheet": {
    createAlias: "accounting_reports_balance_sheet_retrieve",
  },
  "accounting_reports_income_statement": {
    createAlias: "accounting_reports_income_statement_retrieve",
  },
  "accounting_reports_ledger": {
    createAlias: "accounting_reports_ledger_retrieve"
  },
  "accounting_reports_trial_balance": {
    createAlias: "accounting_reports_trial_balance_retrieve",
  },
  "chart-of-accounts": {
    schemaName: "ChartOfAccountsRequest",
    listAlias: "accounting_chart_of_accounts_list",
    createAlias: "accounting_chart_of_accounts_create",
    retrieveAlias: "accounting_chart_of_accounts_retrieve",
    partialUpdateAlias: "accounting_chart_of_accounts_partial_update",
    hardDeleteAlias: "accounting_chart_of_accounts_destroy",
    filterAlias: "accounting_chart_of_accounts_filter_options_retrieve",
    fields: ["code", "name", "account_type", "current_balance"],
    detailsField: [
      "code",
      "name",
      "name_en",
      "account_type",
      "account_subtype",
      "parent_name",
      "normal_balance",
      "opening_balance",
      "current_balance",
      "description",
      "is_header",
      "is_active",
    ],
  },
  "financial-periods": {
    schemaName: "FinancialPeriodRequest",
    listAlias: "accounting_financial_periods_list",
    createAlias: "accounting_financial_periods_create",
    retrieveAlias: "accounting_financial_periods_retrieve",
    partialUpdateAlias: "accounting_financial_periods_partial_update",
    hardDeleteAlias: "accounting_financial_periods_destroy",
    filterAlias: "accounting_financial_periods_filter_options_retrieve",
    fields: ["name", "start_date", "end_date", "is_closed"],
    detailsField: ["name", "start_date", "end_date", "is_closed", "is_active"],
  },
  "journal-entries": {
    schemaName: "GeneralJournalRequest",
    listAlias: "accounting_journal_entries_list",
    createAlias: "accounting_journal_entries_create",
    retrieveAlias: "accounting_journal_entries_retrieve",
    partialUpdateAlias: "accounting_journal_entries_partial_update",
    hardDeleteAlias: "accounting_journal_entries_destroy",
    filterAlias: "accounting_journal_entries_filter_options_retrieve",
    fields: ["entry_number", "entry_date", "entry_type", "total_debit", "is_posted"],
    detailsField: [
      "entry_number",
      "entry_date",
      "entry_type",
      "source_type",
      "source_document",
      "description",
      "total_debit",
      "total_credit",
      "is_posted",
      "posted_by_name",
      "posted_at",
      "notes",
    ],
  },

  // BRANCHES APP
  "branch-users": {
    schemaName: "BranchUsersRequest",
    listAlias: "branches_branch_users_list",
    createAlias: "branches_branch_users_create",
    retrieveAlias: "branches_branch_users_retrieve",
    partialUpdateAlias: "branches_branch_users_partial_update",
    filterAlias: "branches_branch_users_filter_options_retrieve",
    hardDeleteAlias: "branches_branch_users_destroy",
    fields: ["branch__name", "employee__name", "is_active"],
    detailsField: [
      "branch__name",
      "notes",
      "employee__name",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  branches: {
    schemaName: "BranchRequest",
    listAlias: "branches_branches_list",
    createAlias: "branches_branches_create",
    retrieveAlias: "branches_branches_retrieve",
    partialUpdateAlias: "branches_branches_partial_update",
    filterAlias: "branches_branches_filter_options_retrieve",
    hardDeleteAlias: "branches_branches_destroy",
    fields: ["name", "branch_type", "email", "phone"],
    detailsField: [
      "name",
      "branch_code",
      "branch_type",
      "allows_online_orders",
      "is_main_branch",
      "email",
      "phone",
      "address",
      "city",
      "country",
      "is_active",
      "allows_online_orders",
      "operating_hours",
    ],
  },
  "branches-shift": {
    schemaName: "ShiftRequest",
    listAlias: "branches_shifts_list",
    createAlias: "branches_shifts_create",
    retrieveAlias: "branches_shifts_retrieve",
    partialUpdateAlias: "branches_shifts_partial_update",
    filterAlias: "branches_shifts_filter_options_retrieve",
    hardDeleteAlias: "branches_shifts_destroy",
    fields: ["branch_name", "employee_name", "shift_template__name", "is_active"],
    detailsField: [
      "branch_name",
      "employee_name",
      "shift_template__name",
      "start_time",
      "end_time",
      "notes",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },
  "branch-shift-templates": {
    schemaName: "BranchShiftTemplateRequest",
    listAlias: "branches_branch_shift_templates_list",
    createAlias: "branches_branch_shift_templates_create",
    retrieveAlias: "branches_branch_shift_templates_retrieve",
    partialUpdateAlias: "branches_branch_shift_templates_partial_update",
    filterAlias: "branches_branch_shift_templates_filter_options_retrieve",
    hardDeleteAlias: "branches_branch_shift_templates_destroy",
    fields: ["name", "branch_name", "day_of_week", "start_time", "end_time", "is_active"],
    detailsField: [
      "name",
      "branch_name",
      "day_of_week",
      "start_time",
      "end_time",
      "is_active",
      "created_at",
      "updated_at",
    ],
  },

  // MOBILE APP
  "mobile_customers_search": {
    listAlias: "mobile_customers_search_list",
  },
  "mobile_dashboard": {
    retrieveAlias: "mobile_dashboard_retrieve",
  },
  "mobile_orders": {
    retrieveAlias: "mobile_orders_retrieve",
  },
  "mobile_products_search": {
    listAlias: "mobile_products_search_list",
  },
  "mobile_quick_sale": {
    createAlias: "mobile_quick_sale_create",
  },
  "mobile_sync": {
    retrieveAlias: "mobile_sync_retrieve",
  },

  "core_import_csv": {
    createAlias: "core_import_csv_create",
  },
  "prescriptions": {
    schemaName: "PrescriptionRequest",
    listAlias: "prescriptions_prescription_list",
    createAlias: "prescriptions_prescription_create",
    retrieveAlias: "prescriptions_prescription_retrieve",
    partialUpdateAlias: "prescriptions_prescription_partial_update",
    hardDeleteAlias: "prescriptions_prescription_destroy",
    filterAlias: "prescriptions_prescription_filter_options_retrieve",
    fields: ["customer_name", "notes", "user_name"],
    detailsField: ["customer_name", "notes", "user_name", "is_active"],
  },
 
};
