# Generated by Django 5.2.1 on 2025-06-13 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRM', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('right_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_axis', models.IntegerField(blank=True, null=True)),
                ('left_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_axis', models.IntegerField(blank=True, null=True)),
                ('right_reading_add', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_reading_add', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_pupillary_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_pupillary_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('prescription_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='CRM.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
