# Generated by Django 5.2.1 on 2025-09-18 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescriptionrecord_left_axis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='left_axis',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='left_pupillary_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='right_axis',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='right_pupillary_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
