# Generated by Django 5.2.1 on 2025-09-18 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_prescriptionrecord_left_axis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionrecord',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='prescriptionrecord',
            name='prescription_date',
        ),
        migrations.AddField(
            model_name='prescriptionrecord',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_prescriptions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
