# Generated by Django 5.2.1 on 2025-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_remove_prescriptionrecord_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrecord',
            name='vertical_distance_left',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionrecord',
            name='vertical_distance_right',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
