# Generated by Django 5.2.1 on 2025-09-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_prescriptionrecord_vertical_distance_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='a_v_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='a_v_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='sigmant_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='sigmant_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='vertical_distance_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='vertical_distance_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
