# Generated by Django 5.2.9 on 2026-01-24 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_client_plan_alter_payment_amount_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us Messages'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'Page Content', 'verbose_name_plural': 'Page Contents'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['code'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Role Permission', 'verbose_name_plural': 'Role Permissions'},
        ),
        migrations.AlterModelOptions(
            name='tenantsettings',
            options={'verbose_name': 'Tenant Settings', 'verbose_name_plural': 'Tenant Settings'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='page',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='page',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2, verbose_name='Default Language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='users.RolePermission', to='users.permission', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.permission', verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='business_name',
            field=models.CharField(default='Optics Tenant', max_length=255, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='description',
            field=models.TextField(blank=True, default='Default description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.facebook.com', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com', verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='seo_description',
            field=models.TextField(blank=True, default='', verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SEO Keywords'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='swift_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SWIFT Code'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='tiktok',
            field=models.URLField(blank=True, default='https://www.tiktok.com', verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='twitter',
            field=models.URLField(blank=True, default='https://www.twitter.com', verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users_list', to='users.role', verbose_name='Roles'),
        ),
    ]
