# Generated by Django 5.2.6 on 2025-10-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='pagecontent',
            old_name='page',
            new_name='page_id',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='permission',
            new_name='permission_id',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='role',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_id',
        ),
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together={('page_id', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role_id', 'permission_id')},
        ),
    ]
