# Generated by Django 5.2.9 on 2026-06-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='page',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='client',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.DeleteModel(
            name='TenantSettings',
        ),
    ]
