# Generated by Django 5.2.9 on 2026-01-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_client_plan_alter_payment_amount_and_more'),
        ('users', '0002_alter_contactus_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsettings',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.client', verbose_name='Client'),
        ),
    ]
