import { ProductForginKeyConfigType } from "@/src/features/product/types";
import { generateLensOptions } from "@/src/features/product/utils/generateLensOptions";

export const TEXTFIELDDATA = [
  { "label": "Model", "name": "model", "type": "text" },
  { "label": "Name", "name": "name", "type": "text" },
  { "label": "Sku", "name": "sku", "type": "text" },
  { "label": "Last purchase price", "name": "last_purchase_price", "type": "text" },
  { "label": "Sell price", "name": "selling_price", "type": "text" },
  { "label": "Discount percentage", "name": "discount_percentage", "type": "text" },
  { "label": "Description", "name": "description", "type": "textarea", "rows": 5, "placeholder": "Description..." },
]

export const checkBox = [
  { "label": "Is Active", "name": "is_active", type: "checkbox" },
  { "label": "Is Deleted", "name": "is_deleted", type: "checkbox" },
]

export const TypeEnum = [{ value: "CL", label: "Contact Lens" }, { value: "SL", label: "Spectacle Lens" }, { value: "FR", label: "Frames" }, { value: "AX", label: "Accessories" }, { value: "DV", label: "Devices" }, { value: "OT", label: "Other" }]

// export const ProductConfig: ProductForginKeyConfigType[] = [
//   {
//     "name": "category_id", "role": "all", "filter": "Category", "entityName": "categories", "mapOnly": true, "subFilter="",
// hent": "Category", "fieldName": "name", "type": "foreignkey", "required": true },
//   {
//       "name": "supplier_id", "role": "all", "filter": "Supplier", "entityName": "suppliers", "mapOnly": true, "subFilter="",
// hent": "Supplier", "fieldName": "name", "type": "foreignkey", "required": true },
//   {
//         "name": "manufacturer_id", "role": "all", "filter": "Manufacturer", "entityName": "manufacturers", "mapOnly": true, "subFilter="",
// hent": "Manufacturer", "fieldName": "name", "type": "foreignkey", "required": true },
//   {
//           "name": "brand_id", "role": "all", "filter": "Brand", "entityName": "brands", "mapOnly": true, "subFilter="",
// hent": "Brand", "fieldName": "name", "type": "foreignkey", "required": true },
//   { "label": "Model", "name": "model", "type": "text", "role": "all", "filter": "Model", "entityName": "attribute-values", "fieldName": "attribute_name", "placeholder": "Model...", "required": true },
//   { "label": "Name", "name": "name", "type": "text", "role": "all", "filter": "Name", "entityName": "attribute-values", "fieldName": "attribute_name", "placeholder": "Name...", "required": true },
//   // { "label": "Description", "name": "description", "type": "textarea", "rows": 5, "placeholder": "Description..." ,"role": "all", "filter": "Description", "entityName": "attribute-values" ,"fieldName":"attribute_name" },
// ]
// name:string,
// label?:string,
// role:string,
// filter:string,
// subFilter="",
// hent ?: string,
//   // subFilter="",
//   hent: "",
// entityName: string,

// fieldName:string,
// type?:string,
// placeholder?:string,
// required:boolean,


// options?:any[],
// rows?:number,

// schemaName?: string;
// mapOnly?:boolean,


export const ProductVariantConfig: ProductForginKeyConfigType[] = [
  // 🧩 Product Type
  {
    name: "product_type_id",
    label: "Product Type",
    role: "all",
    filter: "Product Type",
    subFilter: "",
    hent: "Product Type Sun Glasses ,Color Contact lens",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select product type...",
    required: true,
  },

  // 🕶️ Frame Attributes (FR)
  {
    name: "frame_shape_id",
    label: "Frame Shape",
    role: "FR",
    filter: "Shape",
    subFilter: "",
    hent: "Frame Shape | Circle | Oval | Square | Rectangle",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select shape...",
    required: true,
  },
  {
    name: "frame_material_id",
    label: "Frame Material",
    role: "FR",
    filter: "Material",
    subFilter: "",
    hent: "Frame Material | Metal | Plastic | Wood | Glass",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select material...",
    required: true,
  },
  {
    name: "frame_color_id",
    label: "Frame Color",
    role: "FR",
    filter: "Color",
    subFilter: "",
    hent: "Frame Color | Black | White | Brown | Green |...",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select color...",
    required: true,
  },
  {
    name: "temple_length_id",
    label: "Temple Length",
    role: "FR",
    filter: "Length",
    subFilter: "",
    hent: "Frame Temple Length ",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select length...",
    required: true,
  },
  {
    name: "bridge_width_id",
    label: "Bridge Width",
    role: "FR",
    filter: "Width",
    subFilter: "",
    hent: "Frame Bridge Width",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select width...",
    required: true,
  },

  // 👁️ Lens Attributes (All)
  {
    name: "lens_base_curve_id",
    label: "Lens Base Curve",
    role: "all",
    filter: "Base Curve",
    subFilter: "RX-CL",
    hent: "Lens Base Curve",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select base curve...",
    required: true,
  },
  {
    name: "lens_color_id",
    label: "Lens Color",
    role: "all",
    filter: "Color",
    subFilter: "",
    hent: "Lens Color | Brown | Green | Blue |...",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select lens color...",
    required: true,
  },
  {
    name: "lens_material_id",
    label: "Lens Material",
    role: "all",
    filter: "Material",
    subFilter: "",
    hent: "Lens Material | Polycarbonate | CR-39 | Silicone |...",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select lens material...",
    required: true,
  },
  {
    name: "lens_diameter_id",
    label: "Lens Diameter",
    role: "all",
    filter: "Diameter",
    subFilter: "",
    hent: "Lens Diameter | 12mm | 13mm | 14mm |...",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select diameter...",
    required: true,
  },

  // 👁‍🗨 Contact Lens (CL)
  {
    name: "unit_id",
    label: "Unit",
    role: "CL",
    filter: "Unit",
    subFilter: "",
    hent: "Items in box | 1piece | 2piece | 3piece |...",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select unit...",
    required: true,
  },
  {
    name: "lens_water_content_id",
    label: "Lens Water Content",
    role: "CL",
    filter: "Water Content",
    subFilter: "",
    hent: "Lens Water Content | 12% | 13% | 14% |...",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select water content...",
    required: true,
  },
  {
    name: "replacement_schedule_id",
    label: "Replacement Schedule",
    role: "CL",
    filter: "Replacement Schedule",
    subFilter: "",
    hent: "Replacement Schedule | Daily | Weekly | Monthly |...",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select schedule...",
    required: true,
  },

  // ⚙️ Common Attributes
  {
    name: "warranty_id",
    label: "Warranty",
    role: "all",
    filter: "Warranty",
    subFilter: "",
    hent: "",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select warranty...",
    required: true,
  },
  {
    name: "dimensions_id",
    label: "Dimensions",
    role: "all",
    filter: "Dimensions",
    subFilter: "",
    hent: "",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select dimensions...",
    required: true,
  },
  {
    name: "weight_id",
    label: "Weight",
    role: "all",
    filter: "Weight",
    subFilter: "",
    hent: "",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "foreignkey",
    placeholder: "Select weight...",
    required: true,
  },
  {
    name: "lens_coatings_id",
    label: "Lens Coatings",
    role: "all",
    filter: "Coatings",
    subFilter: "",
    hent: "",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "checkbox",
    placeholder: "Select coatings...",
    required: true,
  },

  // 💰 Pricing
  {
    label: "SKU",
    name: "sku",
    role: "all",
    filter: "SKU",
    subFilter: "",
    hent: "",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "text",
    placeholder: "Enter SKU...",
    required: true,
  },
  {
    label: "Last Purchase Price",
    name: "last_purchase_price",
    role: "all",
    filter: "Last Purchase Price",
    subFilter: "",
    hent: "",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "text",
    placeholder: "Enter last purchase price...",
    required: true,
  },
  {
    label: "Selling Price",
    name: "selling_price",
    role: "all",
    filter: "Selling Price",
    subFilter: "",
    hent: "",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "text",
    placeholder: "Enter selling price...",
    required: true,
  },
  {
    label: "Discount Percentage",
    name: "discount_percentage",
    role: "all",
    filter: "Discount Percentage",
    subFilter: "",
    hent: "",
    entityName: "attribute-values",
    fieldName: "attribute_name",
    type: "number",
    placeholder: "Enter discount percentage (%)",
    required: true,
  },

  // 🧮 Optical Lens (SL)
  {
    name: "spherical",
    label: "SPH",
    role: "SL",
    filter: "",
    subFilter: "",
    hent: "",
    entityName: "products",
    fieldName: "spherical",
    options: generateLensOptions(-60, 60),
    type: "select",
    placeholder: "Select SPH...",
    required: true,
  },
  {
    name: "cylinder",
    label: "CYL",
    role: "SL",
    filter: "",
    subFilter: "",
    hent: "",
    entityName: "products",
    fieldName: "cylinder",
    options: generateLensOptions(-12, 12),
    type: "select",
    placeholder: "Select CYL...",
    required: true,
  },
  {
    name: "axis",
    label: "AXIS",
    role: "SL",
    filter: "",
    subFilter: "",
    hent: "",
    entityName: "products",
    fieldName: "axis",
    options: generateLensOptions(0, 180, 1, false),
    type: "select",
    placeholder: "Select AXIS...",
    required: true,
  },
  {
    name: "addition",
    label: "ADD",
    role: "SL",
    filter: "",
    subFilter: "",
    hent: "",
    entityName: "products",
    fieldName: "addition",
    options: generateLensOptions(1, 6),
    type: "select",
    placeholder: "Select ADD...",
    required: true,
  },
];
