# Generated by Django 5.2.1 on 2025-06-13 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_customer_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identification_number',
            field=models.CharField(help_text='Enter a valid identification number 10 digits.', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
