# Generated by Django 5.2.1 on 2025-06-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_customer_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
