# Generated by Django 5.2.1 on 2025-06-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_customergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
