# Generated by Django 5.2.9 on 2026-01-19 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('crm', '0002_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_customers', to=settings.AUTH_USER_MODEL, verbose_name='مندوب المبيعات'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='customers',
            field=models.ManyToManyField(related_name='groups', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='customerpartnerlink',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='customer_partner_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='crm.customerpartnerlink'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='sales.order'),
        ),
        migrations.AddField(
            model_name='claimitem',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.insuranceclaim'),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_documents', to='crm.insuranceclaim'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='crm.partner'),
        ),
        migrations.AddField(
            model_name='customerpartnerlink',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='crm.partner'),
        ),
        migrations.AddField(
            model_name='partnerbranch',
            name='branch',
            field=models.ForeignKey(help_text='الفرع المرتبط بهذا الشريك', on_delete=django.db.models.deletion.CASCADE, related_name='partner_agreements', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='partnerbranch',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='crm.partner'),
        ),
        migrations.AddField(
            model_name='partnerpricelist',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='crm.partner'),
        ),
        migrations.AddField(
            model_name='partnerpricelistitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='partnerpricelistitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.partnerpricelist'),
        ),
        migrations.AddField(
            model_name='partnerpricelistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='partnerpricelistitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='partnersettlement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='crm.partner'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='task',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.opportunity'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['status'], name='crm_insuran_status_398b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['claim_date'], name='crm_insuran_claim_d_eb750e_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['partner', 'status'], name='crm_insuran_partner_5d3911_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerpartnerlink',
            unique_together={('customer', 'partner')},
        ),
        migrations.AlterUniqueTogether(
            name='partnerbranch',
            unique_together={('partner', 'branch')},
        ),
    ]
