# Generated by Django 5.2.9 on 2026-06-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contract_start_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='minimum_order_amount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment_terms_days',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pricing_tier',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sales_representative',
        ),
        migrations.AddField(
            model_name='partner',
            name='credit_status',
            field=models.CharField(choices=[('none', 'No Credit'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='none', max_length=15, verbose_name='Credit Status'),
        ),
        migrations.AddField(
            model_name='partner',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Order Amount'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pricing_tier',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale_1', 'Wholesale - Level 1'), ('wholesale_2', 'Wholesale - Level 2'), ('wholesale_3', 'Wholesale - Level 3 (VIP)'), ('distributor', 'Distributor'), ('special', 'Special Price')], default='retail', max_length=20, verbose_name='Pricing Tier'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=15, verbose_name='Customer Type'),
        ),
    ]
