# Generated by Django 5.2.9 on 2026-01-10 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_partner_and_insurance_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية التعاقد'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التعاقد'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حد الائتمان'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الائتمان'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_status',
            field=models.CharField(choices=[('none', 'بدون ائتمان'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('suspended', 'موقوف')], default='none', max_length=15, verbose_name='حالة الائتمان'),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد الحالي'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم الافتراضية'),
        ),
        migrations.AddField(
            model_name='customer',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للطلب'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0, help_text='عدد أيام السداد للآجل', verbose_name='شروط الدفع (أيام)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pricing_tier',
            field=models.CharField(choices=[('retail', 'تجزئة'), ('wholesale_1', 'جملة - المستوى 1'), ('wholesale_2', 'جملة - المستوى 2'), ('wholesale_3', 'جملة - المستوى 3 (VIP)'), ('distributor', 'موزع'), ('special', 'سعر خاص')], default='retail', max_length=20, verbose_name='مستوى التسعير'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_customers', to=settings.AUTH_USER_MODEL, verbose_name='مندوب المبيعات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة'), ('agent', 'وكيل'), ('supplier', 'مورد'), ('wholesaler', 'تاجر جملة'), ('retailer', 'تاجر تجزئة'), ('distributor', 'موزع')], default='individual', max_length=15),
        ),
    ]
