# Generated by Django 5.2.9 on 2026-01-24 20:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_options_alter_branchusers_options_and_more'),
        ('crm', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='claimdocument',
            options={'verbose_name': 'Claim Document', 'verbose_name_plural': 'Claim Documents'},
        ),
        migrations.AlterModelOptions(
            name='claimitem',
            options={'verbose_name': 'Claim Item', 'verbose_name_plural': 'Claim Items'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='customerpartnerlink',
            options={'verbose_name': 'Customer-Partner Link', 'verbose_name_plural': 'Customer-Partner Links'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='insuranceclaim',
            options={'ordering': ['-claim_date'], 'verbose_name': 'Insurance Claim', 'verbose_name_plural': 'Insurance Claims'},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='partnerbranch',
            options={'verbose_name': 'Partner Branch Link', 'verbose_name_plural': 'Partner Branch Links'},
        ),
        migrations.AlterModelOptions(
            name='partnerpricelist',
            options={'ordering': ['partner', 'name'], 'verbose_name': 'Partner Price List', 'verbose_name_plural': 'Partner Price Lists'},
        ),
        migrations.AlterModelOptions(
            name='partnerpricelistitem',
            options={'verbose_name': 'Price List Item', 'verbose_name_plural': 'Price List Items'},
        ),
        migrations.AlterModelOptions(
            name='partnersettlement',
            options={'ordering': ['-settlement_date'], 'verbose_name': 'Partner Settlement', 'verbose_name_plural': 'Partner Settlements'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='document_type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('invoice', 'Invoice'), ('report', 'Medical Report'), ('authorization', 'Pre-Authorization'), ('other', 'Other')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='file',
            field=models.FileField(upload_to='claims/documents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Approved Amount'),
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Claim Amount'),
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='insurance_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Insurance Code'),
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accepts_marketing',
            field=models.BooleanField(default=True, verbose_name='Accepts Marketing'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract End Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract Start Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_notes',
            field=models.TextField(blank=True, verbose_name='Credit Notes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_status',
            field=models.CharField(choices=[('none', 'No Credit'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='none', max_length=15, verbose_name='Credit Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('agent', 'Agent'), ('supplier', 'Supplier'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('distributor', 'Distributor')], default='individual', max_length=15, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Default Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification_number',
            field=models.CharField(help_text='Enter a valid identification number (10 digits)', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Identification Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_vip',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is VIP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Loyalty Points'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Order Amount'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of days for deferred payment', verbose_name='Payment Terms (Days)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS')], default='email', max_length=10, verbose_name='Preferred Contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pricing_tier',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale_1', 'Wholesale - Level 1'), ('wholesale_2', 'Wholesale - Level 2'), ('wholesale_3', 'Wholesale - Level 3 (VIP)'), ('distributor', 'Distributor'), ('special', 'Special Price')], default='retail', max_length=20, verbose_name='Pricing Tier'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_customers', to=settings.AUTH_USER_MODEL, verbose_name='Sales Representative'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Limit'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='copay_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixed Copay Amount'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='copay_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Copay Percentage %'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='coverage_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='Coverage Class'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='coverage_end',
            field=models.DateField(blank=True, null=True, verbose_name='Coverage End'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='coverage_start',
            field=models.DateField(blank=True, null=True, verbose_name='Coverage Start'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='member_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Member ID / Policy Number'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Policy Number'),
        ),
        migrations.AlterField(
            model_name='customerpartnerlink',
            name='remaining_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Remaining Limit'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Approved Amount'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount requested from insurance company', max_digits=12, verbose_name='Claim Amount'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='claim_date',
            field=models.DateField(auto_now_add=True, verbose_name='Claim Date'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='external_claim_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='External Claim Number'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='partial_reason',
            field=models.TextField(blank=True, verbose_name='Partial Approval Reason'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='patient_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Patient Share'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='response_date',
            field=models.DateField(blank=True, null=True, verbose_name='Response Date'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('partial', 'Partially Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submission Date'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting')], max_length=10, verbose_name='Interaction Type'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('lead', 'Lead'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='lead', max_length=20, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Partner Code'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='Contract End Date'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='Contract Start Date'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount due from/to partner', max_digits=12, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='default_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Default Discount %'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Partner Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('insurance', 'Insurance Company'), ('bnpl', 'BNPL Provider'), ('corporate', 'Corporate Client'), ('wholesaler', 'Wholesaler'), ('agent', 'Agent')], max_length=20, verbose_name='Partner Type'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='patient_share_percentage',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Percentage paid by the patient (for insurance)', max_digits=5, verbose_name='Patient Share %'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='payment_terms',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('7_days', '7 Days'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('60_days', '60 Days'), ('90_days', '90 Days')], default='30_days', max_length=20, verbose_name='Payment Terms'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='partnerbranch',
            name='branch',
            field=models.ForeignKey(help_text='Branch associated with this partner', on_delete=django.db.models.deletion.CASCADE, related_name='partner_agreements', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='partnerbranch',
            name='special_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Branch Special Discount %'),
        ),
        migrations.AlterField(
            model_name='partnerpricelist',
            name='adjustment_value',
            field=models.DecimalField(decimal_places=2, help_text='Percentage for discount/markup, amount for fixed price', max_digits=10, verbose_name='Adjustment Value'),
        ),
        migrations.AlterField(
            model_name='partnerpricelist',
            name='applies_to_all',
            field=models.BooleanField(default=False, verbose_name='Applies to All Products'),
        ),
        migrations.AlterField(
            model_name='partnerpricelist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partnerpricelist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='List Name'),
        ),
        migrations.AlterField(
            model_name='partnerpricelist',
            name='price_type',
            field=models.CharField(choices=[('discount', 'Discount on Original Price'), ('fixed', 'Fixed Price'), ('markup', 'Markup on Cost')], default='discount', max_length=20, verbose_name='Price Type'),
        ),
        migrations.AlterField(
            model_name='partnerpricelist',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='partnerpricelist',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Valid Until'),
        ),
        migrations.AlterField(
            model_name='partnerpricelistitem',
            name='special_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Special Discount %'),
        ),
        migrations.AlterField(
            model_name='partnerpricelistitem',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Special Price'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='adjustments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Adjustments'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Amount'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payment Reference'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='period_end',
            field=models.DateField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='period_start',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='settlement_date',
            field=models.DateField(auto_now_add=True, verbose_name='Settlement Date'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='settlement_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Settlement Number'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='partnersettlement',
            name='total_claims',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Claims'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
