# Generated by Django 5.2.9 on 2026-02-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_campaign_options_alter_claimdocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpricelistitem',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='partnerpricelistitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='partnerpricelistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='partnerpricelistitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='PartnerPriceList',
        ),
        migrations.DeleteModel(
            name='PartnerPriceListItem',
        ),
    ]
