# Generated by Django 5.2.9 on 2026-02-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_partnerpricelistitem_price_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpartnerlink',
            name='copay_fixed',
        ),
        migrations.RemoveField(
            model_name='customerpartnerlink',
            name='copay_percentage',
        ),
        migrations.RemoveField(
            model_name='customerpartnerlink',
            name='coverage_class',
        ),
        migrations.RemoveField(
            model_name='customerpartnerlink',
            name='member_id',
        ),
        migrations.AddField(
            model_name='customerpartnerlink',
            name='insurance_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='Insurance Class'),
        ),
        migrations.AddField(
            model_name='customerpartnerlink',
            name='max_patient_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Patient Share (Cap)'),
        ),
        migrations.AddField(
            model_name='customerpartnerlink',
            name='membership_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Membership Number'),
        ),
        migrations.AddField(
            model_name='customerpartnerlink',
            name='patient_share_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Patient Share %'),
        ),
    ]
