# Generated by Django 5.2.9 on 2026-01-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.subscriptionplan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('egp', 'EGP'), ('sar', 'SAR'), ('aud', 'AUD'), ('eur', 'EUR')], default='USD', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('manual', 'Manual'), ('another', 'Another')], default='paypal', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.subscriptionplan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='pendingtenantrequest',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.subscriptionplan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.PositiveIntegerField(default=30, verbose_name='Duration Months'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_years',
            field=models.PositiveIntegerField(default=365, verbose_name='Duration Years'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_crm_module',
            field=models.BooleanField(default=True, verbose_name='Has CRM Module'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_eye_test_module',
            field=models.BooleanField(default=True, verbose_name='Has Eye Test Module'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_hr_module',
            field=models.BooleanField(default=True, verbose_name='Has HR Module'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_inventory_module',
            field=models.BooleanField(default=True, verbose_name='Has Inventory Module'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='month_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Month Price'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='year_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Year Price'),
        ),
    ]
