# Generated by Django 5.2.9 on 2026-06-18 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('business_name', models.CharField(default='Optics Tenant', max_length=255, verbose_name='Business Name')),
                ('description', models.TextField(blank=True, default='Default description.', verbose_name='Description')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com', verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com', verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('twitter', models.URLField(blank=True, default='https://www.twitter.com', verbose_name='Twitter')),
                ('tiktok', models.URLField(blank=True, default='https://www.tiktok.com', verbose_name='TikTok')),
                ('linkedin', models.URLField(blank=True, default='https://www.linkedin.com', verbose_name='LinkedIn')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO Description')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO Keywords')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Country')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Account Number')),
                ('iban', models.CharField(blank=True, default='', max_length=100, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, default='', max_length=100, verbose_name='SWIFT Code')),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
            },
        ),
    ]
