import { FormConfig } from "@/src/shared/types/formConfig";
export const formsConfig: Record<string, FormConfig> = {
// TENANT APP
  "clients":{
    // schemaName: 'ClientRequest',
    listAlias: 'tenants_clients_list',
    // createAlias: 'tenants_register_create',
    retrieveAlias: 'tenants_clients_retrieve',
    // updateAlias: 'tenants_clients_partial_update',
    filterAlias: "tenants_clients_filter_options_retrieve",
    // hardDeleteAlias: 'tenants_clients_destroy',
    fields:["name","max_branches","max_users"],
    detailsField:[ "name","max_branches","max_users","website","is_active","paid_until", ],
    isViweOnly:true
  },
  "register-tenants":{
    schemaName: 'RegisterTenantRequest',
    listAlias: 'tenants_register_list',
    createAlias: 'tenants_register_create',
    retrieveAlias: 'tenants_register_retrieve',
    updateAlias: 'tenants_register_partial_update',
    filterAlias: "tenants_register_filter_options_retrieve",
    hardDeleteAlias: 'tenants_register_destroy',
    fields:["name","email"],
    detailsField:["name","email",],
  },
  'domains':{
    schemaName: 'DomainRequest',
    listAlias: 'tenants_domain_list',
    createAlias: 'tenants_domain_create',
    updateAlias: 'tenants_domain_partial_update',
    hardDeleteAlias: 'tenants_domain_destroy',
    retrieveAlias: 'tenants_domain_retrieve',
    filterAlias: "tenants_domain_filter_options_retrieve",
    fields:["domain"],
    detailsField:["domain","is_active"],
  },
  'payments':{
    // schemaName: 'PaymentRequest',
    listAlias: 'tenants_payments_list',
    // createAlias: 'tenants_payments_create',
    // updateAlias: 'tenants_payments_partial_update',
    // hardDeleteAlias: 'tenants_payments_destroy',
    retrieveAlias: 'tenants_payments_retrieve',
    filterAlias: "tenants_payments_filter_options_retrieve",
    fields:["amount","transaction_id","status","client"],
    detailsField:["amount","transaction_id","status","client","created_at","updated_at","method","currency"],
    isViweOnly:true
  },
  "subscription-plans":{
    schemaName: 'SubscriptionPlanRequest',
    listAlias: 'tenants_subscription_plans_list',
    createAlias: 'tenants_subscription_plans_create',
    updateAlias: 'tenants_subscription_plans_update',
    retrieveAlias: 'tenants_subscription_plans_retrieve',
    hardDeleteAlias: 'tenants_subscription_plans_destroy',
    filterAlias: "tenants_subscription_plans_filter_options_retrieve",
    fields:["name","max_users","max_branches","description"],
    detailsField:["name","max_users","max_branches","description","month_price","year_price","currency","discount"],
  },
    // USERS APP
  'roles':{
    schemaName: 'PatchedRoleRequest',
    listAlias: 'users_roles_list',
    createAlias: 'users_roles_create',
    retrieveAlias: 'users_roles_retrieve',
    filterAlias: 'users_roles_filter_options_retrieve',
    updateAlias: 'users_roles_partial_update',
    hardDeleteAlias: 'users_roles_destroy',
    fields:["name","description"],
    detailsField:["name","description","permissions","is_active","is_deleted"],
  },
  'users': {
    schemaName: 'UserRequest',
    listAlias: 'users_users_list',
    createAlias: 'users_users_create',
    retrieveAlias: 'users_users_retrieve',
    updateAlias: 'users_users_partial_update',
    hardDeleteAlias: 'users_users_destroy',
    filterAlias: "users_users_filter_options_retrieve",
    fields:["username","email","phone","role","is_active"],
    detailsField:["username","email","phone","role","is_active","address","website"],
  },
  'permissions':{
    schemaName: 'PermissionRequest',
    listAlias: 'users_permissions_list',
    createAlias: 'users_permissions_create',
    retrieveAlias: 'users_permissions_retrieve',
    updateAlias: 'users_permissions_partial_update',
    hardDeleteAlias: 'users_permissions_destroy',
    filterAlias: "users_permissions_filter_options_retrieve",
    fields:["code","description"],
    detailsField:["code","description","is_active"],
  },
  'role-permissions':{
    schemaName: 'RolePermissionRequest',
    listAlias: 'users_role_permissions_list',
    createAlias: 'users_role_permissions_create',
    retrieveAlias: 'users_role_permissions_retrieve',
    updateAlias: 'users_role_permissions_partial_update',
    hardDeleteAlias: 'users_role_permissions_destroy',
    filterAlias: "users_role_permissions_filter_options_retrieve",
    fields:["role_name","permission_name"],
    detailsField:["role_name","permission_name","is_active"],
  },
  'contact-us':{
    schemaName: 'ContactUsRequest',
    listAlias: 'users_contact_us_list',
    createAlias: 'users_contact_us_create',
    retrieveAlias: 'users_contact_us_retrieve',
    updateAlias: 'users_contact_us_partial_update',
    hardDeleteAlias: 'users_contact_us_destroy',
    filterAlias: "users_contact_us_filter_options_retrieve",
    fields:["name","email","phone","message"],
    detailsField:["name","email","phone","message","created_at","updated_at","is_deleted","is_active"],
  },
  'tenant-settings':{
    schemaName: 'TenantSettingsRequest',
    listAlias: 'users_tenant_settings_list',
    createAlias: 'users_tenant_settings_create',
    retrieveAlias: 'users_tenant_settings_retrieve',
    updateAlias: 'users_tenant_settings_partial_update',
    hardDeleteAlias: 'users_tenant_settings_destroy',
    filterAlias: "users_tenant_settings_filter_options_retrieve",
    fields:["business_name","phone","email"],
    detailsField:["business_name","phone","email","facebook","instagram","twitter","linkedin","website","description","is_active","is_deleted"],
  },
  'departments': {
    schemaName: 'Department',
    createAlias: 'hrm_departments_create',
    listAlias: 'hrm_departments_list',
    retrieveAlias: 'hrm_departments_retrieve',
    updateAlias: 'hrm_departments_partial_update',
    hardDeleteAlias: 'hrm_departments_destroy',
    filterAlias: "hrm_departments_filter_options_retrieve",
    createSuccessMessage: 'Department created successfully',
    createErrorMessage: 'Failed to create department',
    updateSuccessMessage: 'Department updated successfully',
    updateErrorMessage: 'Failed to update department',
    title: 'Department',
    detailsTitle: 'Department Details',
    createTitle: 'Add Department',
    updateTitle: 'Update Department',
    fields:["name","description"],
    detailsField:["name","description","is_active","is_deleted"],
    showResetButton:true,
    showBackButton:true,
    className:"",
    userConfig:{},

  },
  'employees':{
    schemaName: 'EmployeeRequest',
    listAlias: 'hrm_employees_list',
    createAlias: 'hrm_employees_create',
    retrieveAlias: 'hrm_employees_retrieve',
    updateAlias: 'hrm_employees_partial_update',
    hardDeleteAlias: 'hrm_employees_destroy',
    filterAlias: "hrm_employees_filter_options_retrieve",
    createSuccessMessage: 'Employee created successfully',
    createErrorMessage: 'Failed to create employee',
    updateSuccessMessage: 'Employee updated successfully',
    updateErrorMessage: 'Failed to update employee',
    title: 'Employee',
    detailsTitle: 'Employee Details',
    createTitle: 'Add Employee',
    updateTitle: 'Update Employee',
    fields:["name","email","phone"],
    detailsField:["name","email","phone","address","is_active","is_deleted"],
    showResetButton:true,
    showBackButton:true,
    className:"",
    userConfig:{},
  },
  'customers':{
    schemaName: 'CustomerRequest',
    listAlias: 'crm_customers_list',
    createAlias: 'crm_customers_create',
    retrieveAlias: 'crm_customers_retrieve',
    updateAlias: 'crm_customers_partial_update',
    hardDeleteAlias: 'crm_customers_destroy',
    filterAlias: "crm_customers_filter_options_retrieve",
    fields:["name","email","phone"],
    detailsField:["name","email","phone","address","is_active","is_deleted"],
  },
  'prescriptions':{
    schemaName: 'PrescriptionRequest',
    listAlias: 'prescriptions_prescription_list',
    createAlias: 'prescriptions_prescription_create',
    retrieveAlias: 'prescriptions_prescription_retrieve',
    updateAlias: 'prescriptions_prescription_partial_update',
    hardDeleteAlias: 'prescriptions_prescription_destroy',
    filterAlias: 'prescriptions_prescription_filter_options_retrieve',
    fields:["customer_name","notes","user_name"],
    detailsField:["customer_name","notes","user_name","is_active","is_deleted"],
  },
  "branch-users":{
    schemaName: 'BranchUsersRequest',
    listAlias: 'branches_branch_users_list',
    createAlias: 'branches_branch_users_create',
    retrieveAlias: 'branches_branch_users_retrieve',
    updateAlias: 'branches_branch_users_partial_update',
    filterAlias: 'branches_branch_users_filter_options_retrieve',
    hardDeleteAlias: 'branches_branch_users_destroy',
    fields:["branch_name","employee_name","status"],
    detailsField:["branch_name","employee_name","status","is_active","is_deleted"],
  },
  'branches':{
    schemaName: 'BranchRequest',
    listAlias: 'branches_branches_list',
    createAlias: 'branches_branches_create',
    retrieveAlias: 'branches_branches_retrieve',
    updateAlias: 'branches_branches_partial_update',
    filterAlias: 'branches_branches_filter_options_retrieve',
    hardDeleteAlias: 'branches_branches_destroy',
    fields:["name","email","phone"],
    detailsField:["name","email","phone","address","city","country","is_active","is_deleted"],
  },
  'attributes':{
    schemaName: 'AttributesRequest',
    listAlias: 'products_attributes_list',
    createAlias: 'products_attributes_create',
    retrieveAlias: 'products_attributes_retrieve',
    updateAlias: 'products_attributes_partial_update',
    hardDeleteAlias: 'products_attributes_destroy',
    filterAlias: 'products_attributes_filter_options_retrieve',
    fields:["name","is_active"],
    detailsField:["name","description","values","is_active","is_deleted"],
  },
  "attribute-values":{
    schemaName: 'AttributeValueRequest',
    listAlias: 'products_attribute_values_list',
    createAlias: 'products_attribute_values_create',
    retrieveAlias: 'products_attribute_values_retrieve',
    updateAlias: 'products_attribute_values_partial_update',
    hardDeleteAlias: 'products_attribute_values_destroy',
    filterAlias: 'products_attribute_values_filter_options_retrieve',
    fields:["attribute_id","value","attribute_name"],
    detailsField:["attribute_id","value","attribute_name","is_active","is_deleted"],
  },
  'suppliers':{
    schemaName: 'SupplierRequest',
    listAlias: 'products_suppliers_list',
    createAlias: 'products_suppliers_create',
    retrieveAlias: 'products_suppliers_retrieve',
    updateAlias: 'products_suppliers_partial_update',
    hardDeleteAlias: 'products_suppliers_destroy',
    filterAlias: 'products_suppliers_filter_options_retrieve',
    fields:["name","email","phone"],
    detailsField:["name","contact_person","email","phone","address","country","website","payment_terms","is_active","is_deleted"],
  },
  "manufacturers":{
    schemaName: 'ManufacturerRequest',
    listAlias: 'products_manufacturers_list',
    createAlias: 'products_manufacturers_create',
    retrieveAlias: 'products_manufacturers_retrieve',
    updateAlias: 'products_manufacturers_partial_update',
    hardDeleteAlias: 'products_manufacturers_destroy',
    filterAlias: 'products_manufacturers_filter_options_retrieve',
    fields:["name","email","phone"],
    detailsField:["name","email","phone","country","website","is_active","is_deleted"],
  },
  "brands":{
    schemaName: 'BrandRequest',
    listAlias: 'products_brands_list',
    createAlias: 'products_brands_create',
    retrieveAlias: 'products_brands_retrieve',
    updateAlias: 'products_brands_partial_update',
    hardDeleteAlias: 'products_brands_destroy',
    filterAlias: 'products_brands_filter_options_retrieve',
    fields:["name","email","phone"],
    detailsField:["name","country","website","description","logo","is_active","is_deleted"],
  },
  "categories":{
    schemaName: 'CategoryRequest',
    listAlias: 'products_categories_list',
    createAlias: 'products_categories_create',
    retrieveAlias: 'products_categories_retrieve',
    updateAlias: 'products_categories_partial_update',
    hardDeleteAlias: 'products_categories_destroy',
    filterAlias: 'products_categories_filter_options_retrieve',
    fields:["name","description","parent_name"],
    detailsField:["name","description","parent_id","parent_name","is_active","is_deleted"],
  },
  // 'lens-coatings':{
  //   schemaName: 'LensCoatingRequest',
  //   listAlias: 'products_lens_coatings_list',
  //   createAlias: 'products_lens_coatings_create',
  //   retrieveAlias: 'products_lens_coatings_retrieve',
  //   updateAlias: 'products_lens_coatings_partial_update',
  //   hardDeleteAlias: 'products_lens_coatings_destroy',
  //   filterAlias: 'products_lens_coatings_filter_options_retrieve',
  //   fields:["name","description"],
  //   detailsField:["name","description","is_active","is_deleted"],
  // },
  "products":{
    schemaName: 'ProductRequest',
    listAlias: 'products_products_list',
    createAlias: 'products_products_create',
    retrieveAlias: 'products_products_retrieve',
    updateAlias: 'products_products_partial_update',
    hardDeleteAlias: 'products_products_destroy',
    filterAlias: 'products_products_filter_options_retrieve',
    fields:["name","category_name","brand_name",],
    detailsField:["name","description","category_name","category_id","brand_name","brand_id","manufacturer_name","manufacturer_id","supplier_name","supplier_id","model","type","is_active","is_deleted"],
  },
  'product-variants':{
    schemaName: 'ProductVariantRequest',
    listAlias: 'products_product_variants_list',
    createAlias: 'products_product_variants_create',
    retrieveAlias: 'products_product_variants_retrieve',
    updateAlias: 'products_product_variants_partial_update',
    hardDeleteAlias: 'products_product_variants_destroy',
    filterAlias: 'products_product_variants_filter_options_retrieve',
    fields:["name","category_name","brand_name",],
    detailsField:["name","description","category_name","category_id","brand_name","brand_id","manufacturer_name","manufacturer_id","supplier_name","supplier_id","model","type","is_active","is_deleted"],
  },
  "product-images":{
    schemaName: 'ProductImageRequest',
    listAlias: 'products_product_images_list',
    createAlias: 'products_product_images_create',
    retrieveAlias: 'products_product_images_retrieve',
    updateAlias: 'products_product_images_partial_update',
    hardDeleteAlias: 'products_product_images_destroy',
    filterAlias: 'products_product_images_filter_options_retrieve',
    fields:["name","category_name","brand_name",],
    detailsField:["name","description","category_name","category_id","brand_name","brand_id","manufacturer_name","manufacturer_id","supplier_name","supplier_id","model","type","is_active","is_deleted"],
  },
  "flexible-prices":{
    schemaName: 'FlexiblePriceRequest',
    listAlias: 'products_flexible_prices_list',
    createAlias: 'products_flexible_prices_create',
    retrieveAlias: 'products_flexible_prices_retrieve',
    updateAlias: 'products_flexible_prices_partial_update',
    hardDeleteAlias: 'products_flexible_prices_destroy',
    filterAlias: 'products_flexible_prices_filter_options_retrieve',
    fields:["name","category_name","brand_name",],
    detailsField:["name","description","category_name","category_id","brand_name","brand_id","manufacturer_name","manufacturer_id","supplier_name","supplier_id","model","type","is_active","is_deleted"],
  },
};


export const featuresConfig : Record<string, FormConfig> = {
  "pages":{
  schemaName: 'PageRequest',
  listAlias: 'users_pages_list',
  createAlias: 'users_pages_create',
  retrieveAlias: 'users_pages_retrieve',
  updateAlias: 'users_pages_partial_update',
  hardDeleteAlias: 'users_pages_destroy',
  fields:["name","slug","is_published",],
  filterAlias: 'users_pages_filter_options_retrieve',
  detailsField:["name","slug","is_published","is_active","is_deleted"],
}
}
