# Generated by Django 5.2.9 on 2026-04-27 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='accountingcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountingcategory', verbose_name='Parent Category'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.chartofaccounts', verbose_name='Parent Account'),
        ),
        migrations.AddField(
            model_name='generaljournal',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journals', to=settings.AUTH_USER_MODEL, verbose_name='Posted By'),
        ),
        migrations.AddField(
            model_name='generaljournal',
            name='reversed_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='accounting.generaljournal', verbose_name='Reversed Entry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccounts', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.generaljournal', verbose_name='Journal Entry'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='gl_account',
            field=models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='accounting.chartofaccounts', verbose_name='GL Account (VAT Payable)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountingcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.financialperiod', verbose_name='Financial Period'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.tax', verbose_name='Tax Rate'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.transaction', verbose_name='Transaction'),
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['code'], name='accounting__code_19d47d_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['account_type'], name='accounting__account_7d8a06_idx'),
        ),
        migrations.AddIndex(
            model_name='generaljournal',
            index=models.Index(fields=['entry_date'], name='accounting__entry_d_bb10e1_idx'),
        ),
        migrations.AddIndex(
            model_name='generaljournal',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__b7fac6_idx'),
        ),
    ]
