# Generated by Django 5.2.9 on 2026-01-24 20:05

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountingcategory',
            options={'verbose_name': 'Accounting Category', 'verbose_name_plural': 'Accounting Categories'},
        ),
        migrations.AlterModelOptions(
            name='chartofaccounts',
            options={'ordering': ['code'], 'verbose_name': 'Chart of Accounts', 'verbose_name_plural': 'Chart of Accounts'},
        ),
        migrations.AlterModelOptions(
            name='financialperiod',
            options={'verbose_name': 'Financial Period', 'verbose_name_plural': 'Financial Periods'},
        ),
        migrations.AlterModelOptions(
            name='generaljournal',
            options={'ordering': ['-entry_date', '-entry_number'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='journalline',
            options={'verbose_name': 'Journal Line', 'verbose_name_plural': 'Journal Lines'},
        ),
        migrations.AlterModelOptions(
            name='recurringtransaction',
            options={'verbose_name': 'Recurring Transaction', 'verbose_name_plural': 'Recurring Transactions'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Tax', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', help_text='Current account balance', max_digits=19, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('SAR', 'SAR')], default='USD', help_text='Account currency', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='accountingcategory',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7, verbose_name='Category Type'),
        ),
        migrations.AlterField(
            model_name='accountingcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accountingcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='accountingcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountingcategory', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_subtype',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank'), ('receivable', 'Accounts Receivable'), ('inventory', 'Inventory'), ('prepaid', 'Prepaid Expenses'), ('fixed_asset', 'Fixed Assets'), ('payable', 'Accounts Payable'), ('accrued', 'Accrued Expenses'), ('tax_payable', 'Taxes Payable'), ('deferred', 'Deferred Revenue'), ('loan', 'Loans'), ('capital', 'Capital'), ('retained', 'Retained Earnings'), ('reserves', 'Reserves'), ('sales', 'Sales'), ('service', 'Services'), ('other_income', 'Other Income'), ('salary', 'Salaries'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('supplies', 'Supplies'), ('marketing', 'Marketing'), ('other_expense', 'Other Expenses'), ('cost_of_goods', 'Cost of Goods Sold')], max_length=20, verbose_name='Account Subtype'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('cogs', 'Cost of Goods Sold')], max_length=20, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='code',
            field=models.CharField(help_text='Example: 1100 for Cash', max_length=10, unique=True, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='is_header',
            field=models.BooleanField(default=False, help_text='Header accounts are not used for journal entries', verbose_name='Is Header Account'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='normal_balance',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10, verbose_name='Normal Balance'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Opening Balance'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.chartofaccounts', verbose_name='Parent Account'),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='end_date',
            field=models.DateField(help_text='Period end date', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Whether the period is closed', verbose_name='Is Closed'),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='name',
            field=models.CharField(help_text='Name of the financial period', max_length=50, verbose_name='Period Name'),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='start_date',
            field=models.DateField(help_text='Period start date', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='entry_date',
            field=models.DateField(verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='entry_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Entry Number'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='entry_type',
            field=models.CharField(choices=[('standard', 'Standard Entry'), ('adjustment', 'Adjustment Entry'), ('closing', 'Closing Entry'), ('opening', 'Opening Entry'), ('reversal', 'Reversal Entry')], default='standard', max_length=20, verbose_name='Entry Type'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='Is Posted'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Posted At'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journals', to=settings.AUTH_USER_MODEL, verbose_name='Posted By'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='reversed_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='accounting.generaljournal', verbose_name='Reversed Entry'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='source_document',
            field=models.CharField(blank=True, max_length=100, verbose_name='Source Document Number'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Source Document ID'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('return', 'Return'), ('adjustment', 'Inventory Adjustment'), ('payroll', 'Payroll')], default='manual', max_length=20, verbose_name='Source Type'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Credit'),
        ),
        migrations.AlterField(
            model_name='generaljournal',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Debit'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='credit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.transaction', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccounts', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='cost_center',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cost Center'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.generaljournal', verbose_name='Journal Entry'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Recurrence interval', max_length=10, verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='next_execution',
            field=models.DateField(help_text='Next execution date', verbose_name='Next Execution'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='effective_date',
            field=models.DateField(help_text='Date when tax rate becomes effective', verbose_name='Effective Date'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tax Name'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Tax rate percentage (e.g., 5.00%)', max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(currency_field_name='amount_currency', decimal_places=2, default_currency='USD', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountingcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.financialperiod', verbose_name='Financial Period'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.tax', verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
