# Generated by Django 5.2.9 on 2026-06-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountingcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='period',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tax_rate',
        ),
        migrations.DeleteModel(
            name='RecurringTransaction',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountingCategory',
        ),
        migrations.DeleteModel(
            name='FinancialPeriod',
        ),
    ]
