# Generated by Django 5.2.6 on 2025-10-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='AccountingCategory',
        ),
    ]
