# Generated by Django 5.2.9 on 2026-01-10 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('code', models.CharField(help_text='مثال: 1100 للنقدية', max_length=10, unique=True, verbose_name='رمز الحساب')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('account_type', models.CharField(choices=[('asset', 'أصل'), ('liability', 'التزام'), ('equity', 'حقوق الملكية'), ('revenue', 'إيراد'), ('expense', 'مصروف'), ('cogs', 'تكلفة البضاعة')], max_length=20, verbose_name='نوع الحساب')),
                ('account_subtype', models.CharField(blank=True, choices=[('cash', 'نقدية'), ('bank', 'بنك'), ('receivable', 'ذمم مدينة'), ('inventory', 'مخزون'), ('prepaid', 'مصروفات مقدمة'), ('fixed_asset', 'أصول ثابتة'), ('payable', 'ذمم دائنة'), ('accrued', 'مصروفات مستحقة'), ('tax_payable', 'ضرائب مستحقة'), ('deferred', 'إيرادات مقدمة'), ('loan', 'قروض'), ('capital', 'رأس المال'), ('retained', 'أرباح مبقاة'), ('reserves', 'احتياطيات'), ('sales', 'مبيعات'), ('service', 'خدمات'), ('other_income', 'إيرادات أخرى'), ('salary', 'رواتب'), ('rent', 'إيجار'), ('utilities', 'مرافق'), ('supplies', 'مستلزمات'), ('marketing', 'تسويق'), ('other_expense', 'مصروفات أخرى'), ('cost_of_goods', 'تكلفة بضاعة مباعة')], max_length=20, verbose_name='النوع الفرعي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الحالي')),
                ('is_header', models.BooleanField(default=False, help_text='الحسابات الرئيسية لا تستخدم للقيود', verbose_name='حساب رئيسي (عنوان)')),
                ('normal_balance', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], default='debit', max_length=10, verbose_name='الطبيعة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.chartofaccounts', verbose_name='الحساب الرئيسي')),
            ],
            options={
                'verbose_name': 'حساب في دليل الحسابات',
                'verbose_name_plural': 'دليل الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GeneralJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('entry_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم القيد')),
                ('entry_date', models.DateField(verbose_name='تاريخ القيد')),
                ('entry_type', models.CharField(choices=[('standard', 'قيد عادي'), ('adjustment', 'قيد تسوية'), ('closing', 'قيد إقفال'), ('opening', 'قيد افتتاحي'), ('reversal', 'قيد عكسي')], default='standard', max_length=20, verbose_name='نوع القيد')),
                ('source_type', models.CharField(choices=[('manual', 'يدوي'), ('sales_invoice', 'فاتورة مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('payment', 'دفعة'), ('receipt', 'قبض'), ('return', 'مرتجع'), ('adjustment', 'تسوية مخزون'), ('payroll', 'رواتب')], default='manual', max_length=20, verbose_name='مصدر القيد')),
                ('source_document', models.CharField(blank=True, max_length=100, verbose_name='رقم المستند المصدر')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف المستند')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الدائن')),
                ('is_posted', models.BooleanField(default=False, verbose_name='مرحّل')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journals', to=settings.AUTH_USER_MODEL)),
                ('reversed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='accounting.generaljournal')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-entry_date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='دائن')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('cost_center', models.CharField(blank=True, max_length=50, verbose_name='مركز تكلفة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccounts', verbose_name='الحساب')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.generaljournal', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'سطور القيود',
            },
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['code'], name='accounting__code_19d47d_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['account_type'], name='accounting__account_7d8a06_idx'),
        ),
        migrations.AddIndex(
            model_name='generaljournal',
            index=models.Index(fields=['entry_date'], name='accounting__entry_d_bb10e1_idx'),
        ),
        migrations.AddIndex(
            model_name='generaljournal',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__b7fac6_idx'),
        ),
    ]
