# Generated by Django 5.2.9 on 2026-06-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_account_user_remove_journalentry_account_and_more'),
        ('hrm', '0004_alter_payroll_journal_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
