# Generated by Django 5.2.9 on 2026-02-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=50, verbose_name='Tax Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax Rate %')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('gl_account', models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='accounting.chartofaccounts', verbose_name='GL Account (VAT Payable)')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
            },
        ),
    ]
