# Generated by Django 5.2.1 on 2025-08-05 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRM', '0002_initial'),
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantanswer',
            name='answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariantmarketing',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariantoffer',
            name='ProductVariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariantquestion',
            name='ProductVariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariantquestion',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.customer'),
        ),
        migrations.AddField(
            model_name='productvariantanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='products.productvariantquestion'),
        ),
        migrations.AddField(
            model_name='productvariantreview',
            name='ProductVariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariantreview',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.customer'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='stockmovements',
            name='stocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.stocks'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'is_active'], name='products_ca_name_752bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['usku'], name='products_pr_usku_0d67b5_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product_id'], name='products_pr_product_cee51f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('usku',), name='unique_variant_by_hash'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['order'], name='products_pr_order_2597cf_idx'),
        ),
        migrations.AddIndex(
            model_name='stocks',
            index=models.Index(fields=['branch', 'quantity_in_stock'], name='products_st_branch__d94047_idx'),
        ),
        migrations.AddIndex(
            model_name='stocks',
            index=models.Index(fields=['branch', 'is_active'], name='products_st_branch__4a0583_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocks',
            unique_together={('branch', 'variant')},
        ),
        migrations.AddIndex(
            model_name='stockmovements',
            index=models.Index(fields=['stocks', '-created_at'], name='products_st_stocks__aaa873_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovements',
            index=models.Index(fields=['movement_type', '-created_at'], name='products_st_movemen_beddec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('type', 'brand', 'model')},
        ),
    ]
