# Generated by Django 5.2.1 on 2025-08-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
