# Generated by Django 5.2.1 on 2025-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_flexibleprice'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_variant_by_hash',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_unique__276ddd_idx',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='unique_hash',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='usku',
            field=models.CharField(default=2, editable=False, help_text='Unique USKU', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['usku'], name='products_pr_usku_0d67b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('usku',), name='unique_variant_by_hash'),
        ),
    ]
