# Generated by Django 5.2.1 on 2025-06-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_options_remove_attributes_type_and_more'),
        ('users', '0003_employee_branch_is_deleted_branchusers_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='variant_id',
            new_name='variant',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('adjustment', 'Adjustment'), ('transfer_in', 'transfer_in'), ('transfer_out', 'transfer_out'), ('return', 'Return'), ('damage', 'Damage')], max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('document_type', models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sale Issue'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('return', 'Return'), ('damage', 'Damage')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='products.inventorydocument')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_items', to='users.branch')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_items', to='users.branch')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
        ),
    ]
