# Generated by Django 5.2.1 on 2025-06-10 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_invoice_invoiceitem_order_orderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Lens Coatings',
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_axis',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_coating',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_power_addition',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_power_cylinder',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='lens_power_spherical',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='addition',
            field=models.CharField(blank=True, choices=[('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='axis',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cylinder',
            field=models.CharField(blank=True, choices=[('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='spherical',
            field=models.CharField(blank=True, choices=[('-30.00', '-30.00'), ('-29.75', '-29.75'), ('-29.50', '-29.50'), ('-29.25', '-29.25'), ('-29.00', '-29.00'), ('-28.75', '-28.75'), ('-28.50', '-28.50'), ('-28.25', '-28.25'), ('-28.00', '-28.00'), ('-27.75', '-27.75'), ('-27.50', '-27.50'), ('-27.25', '-27.25'), ('-27.00', '-27.00'), ('-26.75', '-26.75'), ('-26.50', '-26.50'), ('-26.25', '-26.25'), ('-26.00', '-26.00'), ('-25.75', '-25.75'), ('-25.50', '-25.50'), ('-25.25', '-25.25'), ('-25.00', '-25.00'), ('-24.75', '-24.75'), ('-24.50', '-24.50'), ('-24.25', '-24.25'), ('-24.00', '-24.00'), ('-23.75', '-23.75'), ('-23.50', '-23.50'), ('-23.25', '-23.25'), ('-23.00', '-23.00'), ('-22.75', '-22.75'), ('-22.50', '-22.50'), ('-22.25', '-22.25'), ('-22.00', '-22.00'), ('-21.75', '-21.75'), ('-21.50', '-21.50'), ('-21.25', '-21.25'), ('-21.00', '-21.00'), ('-20.75', '-20.75'), ('-20.50', '-20.50'), ('-20.25', '-20.25'), ('-20.00', '-20.00'), ('-19.75', '-19.75'), ('-19.50', '-19.50'), ('-19.25', '-19.25'), ('-19.00', '-19.00'), ('-18.75', '-18.75'), ('-18.50', '-18.50'), ('-18.25', '-18.25'), ('-18.00', '-18.00'), ('-17.75', '-17.75'), ('-17.50', '-17.50'), ('-17.25', '-17.25'), ('-17.00', '-17.00'), ('-16.75', '-16.75'), ('-16.50', '-16.50'), ('-16.25', '-16.25'), ('-16.00', '-16.00'), ('-15.75', '-15.75'), ('-15.50', '-15.50'), ('-15.25', '-15.25'), ('-15.00', '-15.00'), ('-14.75', '-14.75'), ('-14.50', '-14.50'), ('-14.25', '-14.25'), ('-14.00', '-14.00'), ('-13.75', '-13.75'), ('-13.50', '-13.50'), ('-13.25', '-13.25'), ('-13.00', '-13.00'), ('-12.75', '-12.75'), ('-12.50', '-12.50'), ('-12.25', '-12.25'), ('-12.00', '-12.00'), ('-11.75', '-11.75'), ('-11.50', '-11.50'), ('-11.25', '-11.25'), ('-11.00', '-11.00'), ('-10.75', '-10.75'), ('-10.50', '-10.50'), ('-10.25', '-10.25'), ('-10.00', '-10.00'), ('-09.75', '-09.75'), ('-09.50', '-09.50'), ('-09.25', '-09.25'), ('-09.00', '-09.00'), ('-08.75', '-08.75'), ('-08.50', '-08.50'), ('-08.25', '-08.25'), ('-08.00', '-08.00'), ('-07.75', '-07.75'), ('-07.50', '-07.50'), ('-07.25', '-07.25'), ('-07.00', '-07.00'), ('-06.75', '-06.75'), ('-06.50', '-06.50'), ('-06.25', '-06.25'), ('-06.00', '-06.00'), ('-05.75', '-05.75'), ('-05.50', '-05.50'), ('-05.25', '-05.25'), ('-05.00', '-05.00'), ('-04.75', '-04.75'), ('-04.50', '-04.50'), ('-04.25', '-04.25'), ('-04.00', '-04.00'), ('-03.75', '-03.75'), ('-03.50', '-03.50'), ('-03.25', '-03.25'), ('-03.00', '-03.00'), ('-02.75', '-02.75'), ('-02.50', '-02.50'), ('-02.25', '-02.25'), ('-02.00', '-02.00'), ('-01.75', '-01.75'), ('-01.50', '-01.50'), ('-01.25', '-01.25'), ('-01.00', '-01.00'), ('-00.75', '-00.75'), ('-00.50', '-00.50'), ('-00.25', '-00.25'), ('-00.00', '-00.00'), ('+00.25', '+00.25'), ('+00.50', '+00.50'), ('+00.75', '+00.75'), ('+01.00', '+01.00'), ('+01.25', '+01.25'), ('+01.50', '+01.50'), ('+01.75', '+01.75'), ('+02.00', '+02.00'), ('+02.25', '+02.25'), ('+02.50', '+02.50'), ('+02.75', '+02.75'), ('+03.00', '+03.00'), ('+03.25', '+03.25'), ('+03.50', '+03.50'), ('+03.75', '+03.75'), ('+04.00', '+04.00'), ('+04.25', '+04.25'), ('+04.50', '+04.50'), ('+04.75', '+04.75'), ('+05.00', '+05.00'), ('+05.25', '+05.25'), ('+05.50', '+05.50'), ('+05.75', '+05.75'), ('+06.00', '+06.00'), ('+06.25', '+06.25'), ('+06.50', '+06.50'), ('+06.75', '+06.75'), ('+07.00', '+07.00'), ('+07.25', '+07.25'), ('+07.50', '+07.50'), ('+07.75', '+07.75'), ('+08.00', '+08.00'), ('+08.25', '+08.25'), ('+08.50', '+08.50'), ('+08.75', '+08.75'), ('+09.00', '+09.00'), ('+09.25', '+09.25'), ('+09.50', '+09.50'), ('+09.75', '+09.75'), ('+10.00', '+10.00'), ('+10.25', '+10.25'), ('+10.50', '+10.50'), ('+10.75', '+10.75'), ('+11.00', '+11.00'), ('+11.25', '+11.25'), ('+11.50', '+11.50'), ('+11.75', '+11.75'), ('+12.00', '+12.00'), ('+12.25', '+12.25'), ('+12.50', '+12.50'), ('+12.75', '+12.75'), ('+13.00', '+13.00'), ('+13.25', '+13.25'), ('+13.50', '+13.50'), ('+13.75', '+13.75'), ('+14.00', '+14.00'), ('+14.25', '+14.25'), ('+14.50', '+14.50'), ('+14.75', '+14.75'), ('+15.00', '+15.00'), ('+15.25', '+15.25'), ('+15.50', '+15.50'), ('+15.75', '+15.75'), ('+16.00', '+16.00'), ('+16.25', '+16.25'), ('+16.50', '+16.50'), ('+16.75', '+16.75'), ('+17.00', '+17.00'), ('+17.25', '+17.25'), ('+17.50', '+17.50'), ('+17.75', '+17.75'), ('+18.00', '+18.00'), ('+18.25', '+18.25'), ('+18.50', '+18.50'), ('+18.75', '+18.75'), ('+19.00', '+19.00'), ('+19.25', '+19.25'), ('+19.50', '+19.50'), ('+19.75', '+19.75'), ('+20.00', '+20.00'), ('+20.25', '+20.25'), ('+20.50', '+20.50'), ('+20.75', '+20.75'), ('+21.00', '+21.00'), ('+21.25', '+21.25'), ('+21.50', '+21.50'), ('+21.75', '+21.75'), ('+22.00', '+22.00'), ('+22.25', '+22.25'), ('+22.50', '+22.50'), ('+22.75', '+22.75'), ('+23.00', '+23.00'), ('+23.25', '+23.25'), ('+23.50', '+23.50'), ('+23.75', '+23.75'), ('+24.00', '+24.00'), ('+24.25', '+24.25'), ('+24.50', '+24.50'), ('+24.75', '+24.75'), ('+25.00', '+25.00'), ('+25.25', '+25.25'), ('+25.50', '+25.50'), ('+25.75', '+25.75'), ('+26.00', '+26.00'), ('+26.25', '+26.25'), ('+26.50', '+26.50'), ('+26.75', '+26.75'), ('+27.00', '+27.00'), ('+27.25', '+27.25'), ('+27.50', '+27.50'), ('+27.75', '+27.75'), ('+28.00', '+28.00'), ('+28.25', '+28.25'), ('+28.50', '+28.50'), ('+28.75', '+28.75'), ('+29.00', '+29.00'), ('+29.25', '+29.25'), ('+29.50', '+29.50'), ('+29.75', '+29.75'), ('+30.00', '+30.00')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('CL', 'Contact Lenses'), ('SL', 'Spectacle Lenses'), ('SG', 'Sunglasses'), ('EW', 'Eyewear'), ('AX', 'Accessories'), ('OT', 'Other'), ('DV', 'Devices')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='bridge_width',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Width'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bridge_width', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='dimensions',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Dimensions'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='frame_color',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_color', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='frame_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Material'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_frame_material', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='frame_shape',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Shape'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_frame_shape', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='lens_base_curve',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Base Curve'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_base_curve', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='lens_color',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_color', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='lens_diameter',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Diameter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_diameter', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='lens_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Material'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_material', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='lens_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Lens Type'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_type', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='lens_water_content',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Water Content'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lens_water_content', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='replacement_schedule',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Replacement Schedule'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_replacement_schedule', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(editable=False, help_text='SKU (Stock Keeping Unit)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='temple_length',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Length'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_temple_length', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unique_hash',
            field=models.CharField(editable=False, help_text='Unique Hash', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='warranty',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Warranty'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_warranty', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.ForeignKey(blank=True, limit_choices_to={'attribute__name': 'Weight'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_weight', to='products.attributevalue'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('type', 'brand', 'model')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'is_active'], name='products_ca_name_752bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['order'], name='products_pr_order_2597cf_idx'),
        ),
        migrations.AddIndex(
            model_name='lenscoating',
            index=models.Index(fields=['name'], name='products_le_name_8da045_idx'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='lens_coatings',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_lens_coatings', to='products.lenscoating'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['unique_hash'], name='products_pr_unique__276ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product_id'], name='products_pr_product_cee51f_idx'),
        ),
    ]
