# Generated by Django 5.2.1 on 2025-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_lenscoating_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
